import { Platform, StyleSheet } from "react-native";
export const palette = {
  paper: "#FAF7F3",
  ink: "#352C32",
  muted: "#81737B",
  plum: "#785067",
  line: "#E8DFE4",
  tint: "#F0E6ED",
};
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.paper },
  content: { padding: 22, gap: 16, paddingBottom: 48 },
  row: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 2,
    color: palette.plum,
    fontWeight: "700",
  },
  title: {
    fontFamily: Platform.OS === "ios" ? "Georgia" : "serif",
    fontSize: 36,
    lineHeight: 43,
    color: palette.ink,
  },
  heading: {
    fontFamily: Platform.OS === "ios" ? "Georgia" : "serif",
    fontSize: 25,
    lineHeight: 32,
    color: palette.ink,
  },
  body: { fontSize: 16, lineHeight: 25, color: palette.ink },
  muted: { fontSize: 13, lineHeight: 20, color: palette.muted },
  card: {
    padding: 22,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.line,
    backgroundColor: "#FFFFFF",
    gap: 10,
  },
  cover: {
    padding: 22,
    borderRadius: 18,
    backgroundColor: palette.tint,
    gap: 12,
  },
  input: {
    minHeight: 48,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.line,
    color: palette.ink,
    backgroundColor: "#FFFFFF",
    fontSize: 16,
  },
  notice: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: palette.tint,
    gap: 8,
  },
  button: {
    minHeight: 44,
    paddingHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: palette.tint,
    justifyContent: "center",
    alignItems: "center",
  },
  primary: { backgroundColor: palette.plum },
  buttonText: { fontSize: 14, fontWeight: "600", color: palette.plum },
  white: { color: "#FFFFFF" },
  disabled: { opacity: 0.45 },
  separator: { height: 1, backgroundColor: palette.line },
  article: {
    color: palette.ink,
    lineHeight: 31,
    fontSize: 19,
    fontFamily: Platform.OS === "ios" ? "Georgia" : "serif",
  },
});
