// Generated by scripts/generate-chat-agent-inspirations.mjs from the public research inventory.
// Keep this metadata-only: third-party private prompts are not copied into Matrix.
export type AgentInspiration = {
  id: string; name: string; creatorName: string; categories: string[]; description: string;
  skills: string[]; routines: string[]; integrations: string[]; sourceUrl: string;
};

export const agentInspirations: AgentInspiration[] = [
  {
    "id": "account-book",
    "name": "Account Research Desk",
    "creatorName": "Anoop Baliga",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Researches the companies you sell to and writes your pre-call brief and account plan. Works from the public web and the notes you paste, and never sends without you.",
    "skills": [
      "Account brief before a call",
      "Account plan",
      "Account signals refresh",
      "Account usage and health",
      "Build the account list",
      "Getting started",
      "Incumbent and competitor check",
      "Open threads and next steps",
      "Outreach and follow-up drafts",
      "Stakeholder map",
      "Week ahead call prep"
    ],
    "routines": [
      "Friday open threads review",
      "Weekday call prep",
      "Weekly account signals"
    ],
    "integrations": [
      "Databricks SQL",
      "Gmail",
      "Google Calendar",
      "Google Drive",
      "Google Sheets",
      "Granola",
      "hex",
      "linear",
      "notion-workspace",
      "Salesforce",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/account-book"
  },
  {
    "id": "fuse",
    "name": "Ad Spend Watch",
    "creatorName": "Miguel Cruz",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Watches your ad spend and performance and flags what's breaking before it burns budget. Works from a pasted export, and never pauses a campaign without your yes.",
    "skills": [
      "Answer a spend question",
      "Check budget pace",
      "Diagnose what broke",
      "Getting started",
      "Pull numbers from a connected source",
      "Read an ad platform export",
      "Run the spend and performance check",
      "Set accounts and thresholds",
      "Write the fix list"
    ],
    "routines": [
      "Daily spend and performance check",
      "Midday burn check",
      "Weekly budget pace check"
    ],
    "integrations": [
      "datadog",
      "figma",
      "Gmail",
      "Google Sheets",
      "hex",
      "linear",
      "notion-workspace",
      "sentry",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/fuse"
  },
  {
    "id": "ai-search-visibility",
    "name": "AI Search Visibility",
    "creatorName": "Adam Tanguay",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Checks whether AI assistants and Google recommend you, and who they name instead. Starts from a handful of questions your buyers actually ask.",
    "skills": [
      "Build the prompt list",
      "Capture a pasted answer",
      "Citation source audit",
      "Draft the fix",
      "Getting started",
      "Run a visibility check",
      "Share of answer comparison",
      "Weekly visibility brief"
    ],
    "routines": [
      "Top prompt spot check",
      "Weekly visibility brief"
    ],
    "integrations": [
      "Google Sheets",
      "hex",
      "linear",
      "notion-workspace",
      "Profound",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/ai-search-visibility"
  },
  {
    "id": "alfred",
    "name": "Alfred",
    "creatorName": "Robin Delta",
    "categories": [
      "Operations"
    ],
    "description": "Designs, audits, and governs your Grok Bot organization so it matches real company outcomes, with clear human owners and no duplicate jobs. Recommends the smallest useful structure, defaults new bots to zero, and never creates or changes anything without your exact yes.",
    "skills": [
      "Audit, Repair & Govern",
      "Grok Bot Organization Discovery & Architecture",
      "Grok Bot System Design",
      "Pilot, Test & Activate",
      "Public Share & Security Audit",
      "Workflow & Automation Decision"
    ],
    "routines": [
      "Monthly Bot Portfolio Strategy Review",
      "Quarterly Company & AI Operating Model Review",
      "Weekly Company & Grok Bot Improvement Review"
    ],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/alfred"
  },
  {
    "id": "apple-search-ads-review",
    "name": "Apple Search Ads Review",
    "creatorName": "Chris Everett",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Reviews your Apple Search Ads spend against your cost per install target. Drafts the keyword, bid, and budget changes, and never touches your account.",
    "skills": [
      "Bids and budgets",
      "Change sheet",
      "Getting started",
      "Search terms and negatives",
      "Set spend targets",
      "Spend review",
      "Weekly ad review"
    ],
    "routines": [
      "Daily spend check",
      "Weekly ad review"
    ],
    "integrations": [
      "Databricks SQL",
      "Gmail",
      "Google Sheets",
      "hex",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/apple-search-ads-review"
  },
  {
    "id": "call-follow-ups",
    "name": "Call Follow-Ups",
    "creatorName": "Daniel Brill",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Turns each recorded call into a follow-up email in your voice, a next-steps note, and the CRM updates, including the qualification fields your team runs on. Watches Gong and Granola for new calls, and nothing sends or saves without your yes.",
    "skills": [
      "crm-update-proposal",
      "getting-started",
      "next-steps-note",
      "promise-tracker",
      "recap-email",
      "voice-profile"
    ],
    "routines": [
      "New call watch"
    ],
    "integrations": [
      "Attio",
      "Gmail",
      "Gong",
      "Google Calendar",
      "Granola",
      "Hex",
      "HubSpot",
      "Linear",
      "Notion",
      "Outlook",
      "Salesforce",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/call-follow-ups"
  },
  {
    "id": "chief-health",
    "name": "Chief Health Officer",
    "creatorName": "AJAC",
    "categories": [
      "Personal"
    ],
    "description": "You're the Chief Health Officer. Every day, ask if training happened. If it did not, rewrite the next session so the week still holds. Read whatever workout app, nutrition app, wearable, or lab source is connected. Do not invent numbers. Never diagnose, prescribe, or post.",
    "skills": [],
    "routines": [
      "Daily train check",
      "Sunday health review"
    ],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/chief-health"
  },
  {
    "id": "clip-bot",
    "name": "Clip Bot",
    "creatorName": "This Week in AI",
    "categories": [
      "Marketing"
    ],
    "description": "Finds the best moments in a long recording and cuts them into short captioned clips. Works from an upload or a link, with transcript and timestamps on every clip.",
    "skills": [
      "Clip captions and post copy",
      "Clip pack from one recording",
      "Cut a clip",
      "Find the clippable moments",
      "Getting started",
      "Transcribe a recording"
    ],
    "routines": [
      "Clip queue pass",
      "Friday clip recap"
    ],
    "integrations": [
      "figma",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/clip-bot"
  },
  {
    "id": "company-docs-q-a",
    "name": "Company Docs Q&A",
    "creatorName": "Anoop Baliga",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Answers product and how-to questions from live docs first, then connected knowledge sources, and always cites sources. Built for anyone who wants a trustworthy internal knowledge bot.",
    "skills": [],
    "routines": [],
    "integrations": [
      "Notion",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/company-docs-q-a"
  },
  {
    "id": "competitor-watching",
    "name": "Competitor Watch",
    "creatorName": "Shimecki",
    "categories": [
      "Product"
    ],
    "description": "Tracks competitor pricing, product, and hiring pages and briefs you on real changes. Starts from a list of URLs you paste.",
    "skills": [
      "Build the watch list",
      "Competitor page diff",
      "Getting started",
      "Pricing and packaging comparison",
      "Weekly competitor brief"
    ],
    "routines": [
      "Daily launch check",
      "Weekly competitor brief"
    ],
    "integrations": [
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/competitor-watching"
  },
  {
    "id": "cooper",
    "name": "Cooper",
    "creatorName": "Tommy Hansen",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "News agent for AI, tech, venture capital, and business. Delivers a tight daily Slack briefing of top stories at 8am, plus weekday mid-day competitor alerts only when something truly clears the bar.",
    "skills": [],
    "routines": [
      "Afternoon competitor alert",
      "Daily AI/tech/VC briefing",
      "Midday competitor alert"
    ],
    "integrations": [
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/cooper"
  },
  {
    "id": "human-copywriter",
    "name": "Copy Humanizer",
    "creatorName": "Massimo De Luisa",
    "categories": [
      "Marketing"
    ],
    "description": "Edits and rewrites drafts, emails, and pages so they read like a person wrote them. Keeps your voice, shows every change and why, and never invents a fact.",
    "skills": [
      "Anti-slop pass",
      "Build the voice profile",
      "Draft for a channel",
      "Edit a draft",
      "Getting started",
      "Learn from what shipped",
      "Rewrite a draft"
    ],
    "routines": [
      "Weekly shipped check"
    ],
    "integrations": [
      "figma",
      "Gmail",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/human-copywriter"
  },
  {
    "id": "credit-card-max",
    "name": "Credit Card Max",
    "creatorName": "Trevin Chow",
    "categories": [
      "Personal"
    ],
    "description": "Advises which credit card to use for a given purchase to maximize points, cash back, and perks. Tracks cards, unused benefits, and misrouted recurring charges, and runs a monthly utilization review.",
    "skills": [],
    "routines": [
      "Monthly card rollup"
    ],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/credit-card-max"
  },
  {
    "id": "critiquito",
    "name": "Critiquito: Design Critique",
    "creatorName": "Manuel Muñoz Solera",
    "categories": [
      "Design",
      "From Grok Bot Team"
    ],
    "description": "Turns a screenshot or Figma link into a design critique with ranked, concrete fixes. Covers hierarchy, type, color, copy, and accessibility, and never edits your files.",
    "skills": [
      "Accessibility pass",
      "Compare versions",
      "Flow critique",
      "Getting started",
      "Hand off the fixes",
      "Screen critique",
      "UI copy pass"
    ],
    "routines": [
      "Weekly open fixes"
    ],
    "integrations": [
      "figma",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/critiquito"
  },
  {
    "id": "customer-call-coach",
    "name": "Customer Call Coach & Assistant",
    "creatorName": "Anoop Baliga",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Briefs you before customer calls and coaches you after based on your performance.",
    "skills": [],
    "routines": [
      "Friday Coach Refresh"
    ],
    "integrations": [
      "Gmail",
      "Granola",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/customer-call-coach"
  },
  {
    "id": "customer-stories",
    "name": "Customer Proof Desk",
    "creatorName": "Anoop Baliga",
    "categories": [
      "Sales"
    ],
    "description": "Turns call notes and transcripts into case studies, testimonials, and proof points. Quotes stay word for word from what you paste, and nothing publishes without your yes.",
    "skills": [
      "Add sources to the proof bank",
      "Build a deal proof one-pager",
      "Check a draft against the bank",
      "Get the customer's approval",
      "Getting started",
      "Lay out the case study",
      "Mine a batch of calls",
      "Pull proof for a claim",
      "Run the case study pipeline",
      "Testimonials and pull quotes",
      "Write a case study"
    ],
    "routines": [
      "Monthly proof refresh",
      "Weekly proof roundup"
    ],
    "integrations": [
      "figma",
      "Gmail",
      "Granola",
      "hex",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/customer-stories"
  },
  {
    "id": "deal-hunting",
    "name": "Deal Hunting",
    "creatorName": "Shimecki",
    "categories": [
      "Personal"
    ],
    "description": "Landed-cost shopping: real prices, shipping and tax, preferred retailers. Watchlist optional. Never buys unless asked.",
    "skills": [],
    "routines": [
      "Watchlist check",
      "Weekly process note"
    ],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/deal-hunting"
  },
  {
    "id": "deal-qualification",
    "name": "Deal Inspector",
    "creatorName": "Jon Grigull",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Checks every deal that moved stage against your qualification criteria using the actual call transcripts. Quotes the evidence, flags what is missing, recommends promote or close, and proposes the CRM updates for your approval.",
    "skills": [
      "crm-writeback",
      "getting-started",
      "qualification-frameworks",
      "stage-gate-audit"
    ],
    "routines": [
      "Friday stage audit"
    ],
    "integrations": [
      "Attio",
      "Gmail",
      "Gong",
      "Google Sheets",
      "Granola",
      "HubSpot",
      "Notion",
      "Salesforce",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/deal-qualification"
  },
  {
    "id": "dial-bot",
    "name": "dial bot",
    "creatorName": "Matt Palmer",
    "categories": [
      "From Grok Bot Team",
      "Personal"
    ],
    "description": "Places outbound Bland AI phone calls when you ask, then reports what happened. On first use it asks for a Bland API key and voice.",
    "skills": [
      "Bland phone calls"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/dial-bot"
  },
  {
    "id": "dr-eggbot-v2",
    "name": "dr eggbot",
    "creatorName": "Lauren Tan",
    "categories": [
      "From Grok Bot Team"
    ],
    "description": "Designs high-quality Grok Bots. Asks a few preference questions, then creates them with CreateAgent. Coding bots get the poteto-mode bar (one job, unslopped, verified). Non-coding bots get the same tightness: one job, one voice, explicit anti-jobs, no leftover tools. Casual, a little mad-scientist, short lowercase. Bias to act once the job is clear. Does not default to shareable templates.",
    "skills": [
      "Design a Grok Bot",
      "Make Bot UI",
      "Routine healthcheck",
      "Transcript healthcheck"
    ],
    "routines": [
      "routine-healthcheck",
      "transcript-healthcheck"
    ],
    "integrations": [
      "pstack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/dr-eggbot-v2"
  },
  {
    "id": "ebr-value-deck-builder",
    "name": "EBR & Value Deck Builder",
    "creatorName": "Krista Letz",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Builds an executive business review or value deck for a named account from your CRM, call history, and usage data, on your brand, and hands you an editable file. Never invents a number, and nothing goes to the customer without your yes.",
    "skills": [
      "brand-kit",
      "ebr-deck",
      "getting-started",
      "pptx-compat",
      "three-whys"
    ],
    "routines": [
      "Renewal deck reminder"
    ],
    "integrations": [
      "Attio",
      "Gong",
      "Google Drive",
      "HubSpot",
      "Mixpanel",
      "OneDrive",
      "Salesforce"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/ebr-value-deck-builder"
  },
  {
    "id": "event-producer",
    "name": "Event Producer",
    "creatorName": "Jenna Nanpei",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Turns your event details into a run of show, guest list, and day-of checklist. Tracks vendors, guests, dietary needs, and travel, and never sends a message without you.",
    "skills": [
      "Build the event brief",
      "Day-of checklist",
      "Getting started",
      "Guest list and invites",
      "Guest travel and hotels",
      "Post-event recap",
      "Run of show",
      "Vendor and venue tracker"
    ],
    "routines": [
      "Day-of brief",
      "Event countdown check",
      "Post-event recap draft"
    ],
    "integrations": [
      "figma",
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/event-producer"
  },
  {
    "id": "event-request-desk",
    "name": "Event Request Desk",
    "creatorName": "Emma Weyrauch",
    "categories": [
      "From Grok Bot Team",
      "Operations"
    ],
    "description": "Scores every event, sponsorship, and speaking ask, then drafts your yes or no. Works from a Slack channel or a paste, and never sends without you.",
    "skills": [
      "Draft the reply",
      "Event spend and yes rate",
      "Getting started",
      "Log a new event request",
      "Queue review",
      "Score an event request",
      "Track what you owe after a yes",
      "Tune the decision rubric"
    ],
    "routines": [
      "Weekday intake sweep",
      "Weekly commitment check",
      "Weekly queue review"
    ],
    "integrations": [
      "figma",
      "Gmail",
      "Google Calendar",
      "Google Drive",
      "Google Sheets",
      "hex",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/event-request-desk"
  },
  {
    "id": "frank",
    "name": "Executive Assistant",
    "creatorName": "Natasha Kuo",
    "categories": [
      "From Grok Bot Team",
      "Operations"
    ],
    "description": "EA chief-of-staff bot for exec support: conference rooms, interview prep, leadership outreach, Slack channel inventories, sheet↔calendar checks, and birthday/anniversary calendar loads.",
    "skills": [],
    "routines": [
      "Exec conference-room rundown (2 business days ahead)",
      "Exec interview-prep reminder",
      "Exec same-day conference-room check",
      "Weekly leadership-outreach check"
    ],
    "integrations": [
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "Notion",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/frank"
  },
  {
    "id": "figma-bro",
    "name": "figma bro",
    "creatorName": "John Bai",
    "categories": [
      "Design",
      "From Grok Bot Team"
    ],
    "description": "Turns a Figma frame into a build spec, and audits your components, tokens, and motion. Builds screens from a brief too, and works from a pasted link when Figma isn't connected.",
    "skills": [
      "Build a screen from a brief",
      "Component library audit",
      "Design to code handoff notes",
      "Design token audit",
      "File structure cleanup plan",
      "Frame to build spec",
      "Getting started",
      "Motion and prototype notes"
    ],
    "routines": [
      "Ready for dev sweep",
      "Weekly library check"
    ],
    "integrations": [
      "figma",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/figma-bro"
  },
  {
    "id": "flora",
    "name": "Flora: Plant Care Log",
    "creatorName": "Rich Silver",
    "categories": [
      "Personal"
    ],
    "description": "Flora keeps a private houseplant care log and weekly reminders. She builds a plant journal on her computer that you can page through, and your plants do not copy if someone else installs her.",
    "skills": [
      "Houseplant care card",
      "Houseplant care first-run",
      "Houseplant weekly collection news",
      "Private houseplant journal"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/flora"
  },
  {
    "id": "sable-game-art",
    "name": "Game Art Director",
    "creatorName": "Danny Limanseta",
    "categories": [
      "Design"
    ],
    "description": "Turns a game concept into a style guide, palettes, and prompt sheets for your image tool. Slices sprite sheets and checks your art for palette and grid drift.",
    "skills": [
      "Asset consistency check",
      "Getting started",
      "Prompt sheets",
      "Sprite and tile specs",
      "Sprite sheet toolkit",
      "Style guide"
    ],
    "routines": [
      "Weekly art review",
      "Weekly reference sweep"
    ],
    "integrations": [
      "figma",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/sable-game-art"
  },
  {
    "id": "account-research",
    "name": "GTM Account Research",
    "creatorName": "Stefan Markarian",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Researches one account before a meeting, deal review, or account plan. Brings together company changes, key people, relationship history, open questions, and the sources behind every finding.",
    "skills": [
      "account-research",
      "account-sot-sync",
      "agent-orchestration",
      "humanizer"
    ],
    "routines": [
      "Weekly account monitor"
    ],
    "integrations": [
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "Granola",
      "Notion",
      "Salesforce",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/account-research"
  },
  {
    "id": "warm-intro-finder",
    "name": "GTM Connections",
    "creatorName": "Brian Joseph",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Finds credible ways into a target account through mutual contacts, past conversations, shared history, and prior meetings. Ranks the best paths, drafts the introduction ask, and tracks what happened.",
    "skills": [
      "agent-orchestration",
      "connections-and-intros",
      "humanizer"
    ],
    "routines": [
      "Warm-path follow-through queue"
    ],
    "integrations": [
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "Notion",
      "Salesforce",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/warm-intro-finder"
  },
  {
    "id": "follow-through-agent",
    "name": "GTM Loop Closer",
    "creatorName": "Jon Grigull",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Finds promises, follow-ups, and customer details left behind in meetings, email, Slack, CRM, or task tools. Shows the evidence and prepares the reply, task, or update needed to close each loop.",
    "skills": [
      "agent-orchestration",
      "conversation-to-action",
      "follow-through-drafts",
      "humanizer",
      "open-loop-audit"
    ],
    "routines": [
      "Commitment-strand audit"
    ],
    "integrations": [
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "Granola",
      "Notion",
      "Salesforce",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/follow-through-agent"
  },
  {
    "id": "prospector",
    "name": "GTM Prospecting",
    "creatorName": "Caro Scalercio",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Turns an ideal customer profile into a focused prospect list, adds useful context, and checks for existing relationships. Drafts first-touch email and LinkedIn messages for your review.",
    "skills": [
      "agent-orchestration",
      "humanizer",
      "prospecting-loop"
    ],
    "routines": [
      "Weekly prospecting hygiene"
    ],
    "integrations": [
      "Gmail",
      "Google Sheets",
      "Notion",
      "Salesforce"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/prospector"
  },
  {
    "id": "haggle-bot",
    "name": "Haggle Bot",
    "creatorName": "Daniel Gartshein",
    "categories": [
      "From Grok Bot Team"
    ],
    "description": "Inventories your SaaS spend from Ramp and bills, finds evidence-backed savings (unused seats, duplicates, cheaper alternatives), and drafts vendor counters for your review. Never spends, signs, or sends without you.",
    "skills": [
      "build-spend-inventory",
      "draft-vendor-counter",
      "Google Sheets final check",
      "haggle-setup",
      "research-alternatives",
      "score-savings-opportunity"
    ],
    "routines": [
      "Monthly inventory refresh",
      "Renewal window watch"
    ],
    "integrations": [
      "Gmail",
      "Google Drive",
      "Google Sheets",
      "Granola",
      "Notion",
      "Ramp",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/haggle-bot"
  },
  {
    "id": "hiring-activity-monitor",
    "name": "Hiring Signals",
    "creatorName": "Simon Lackowski",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Tracks hiring activity across selected companies and job sources. Highlights meaningful changes, matches them to accounts and owners, and passes the right context into research or prospecting workflows.",
    "skills": [
      "agent-orchestration",
      "hiring-signals",
      "humanizer"
    ],
    "routines": [
      "Weekday hiring signal digest"
    ],
    "integrations": [
      "Google Sheets",
      "Notion",
      "Salesforce",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/hiring-activity-monitor"
  },
  {
    "id": "home-robots",
    "name": "Home robots",
    "creatorName": "Sawyer Merritt",
    "categories": [
      "Personal"
    ],
    "description": "Control home robots from chat: a Segway Navimow, a Matic vacuum, and other official vacuums, mowers, and Matter robots. Connect each once, then say start, pause, dock, or how's it doing.",
    "skills": [
      "Connect home robot",
      "Connect Matic",
      "Connect Navimow",
      "Control home robot",
      "Control Matic",
      "Control Navimow",
      "Share this bot"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/home-robots"
  },
  {
    "id": "imogen",
    "name": "Imogen",
    "creatorName": "Kent C. Dodds",
    "categories": [
      "Design"
    ],
    "description": "Imogen the Impala Image Interpreter writes brief, copyable alt text focused on the most important part of an image, so images are accessible to blind people.",
    "skills": [],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/imogen"
  },
  {
    "id": "last30days",
    "name": "last30days",
    "creatorName": "Matt Van Horn",
    "categories": [
      "Marketing",
      "Product"
    ],
    "description": "Research what people actually say about any topic in the last 30 days. Installs the latest last30days skill from GitHub, walks first-run setup (ScrapeCreators via GitHub for the full free credits, X, YouTube, and the free CLIs), then writes a grounded brief from Reddit, X, YouTube, TikTok, Hacker News, Polymarket, GitHub, and the web. Checks GitHub for a new skill version every 30 days.",
    "skills": [
      "last30days"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/last30days"
  },
  {
    "id": "leadsworth",
    "name": "Lead Pipeline Desk",
    "creatorName": "Miguel Cruz",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Scores your inbound leads, merges duplicates, assigns an owner, and flags what's stuck. Works from a CRM export, a sheet, or a paste, and never sends anything without you.",
    "skills": [
      "Build the lead ledger",
      "Connect a tool or change the source",
      "Getting started",
      "Merge duplicate leads",
      "Pipeline health report",
      "Route leads and draft the first reply",
      "Score and qualify leads"
    ],
    "routines": [
      "Daily lead triage",
      "Weekly pipeline report"
    ],
    "integrations": [
      "Databricks SQL",
      "Gmail",
      "Google Sheets",
      "hex",
      "linear",
      "notion-workspace",
      "Salesforce",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/leadsworth"
  },
  {
    "id": "engineer-bot",
    "name": "Lingxi's Engineer Bot",
    "creatorName": "Lingxi Li",
    "categories": [
      "Engineering",
      "From Grok Bot Team"
    ],
    "description": "A hands-off engineering supervisor. Boards work, launches cloud agents on the repo you name, watches PRs on a 30-minute cadence, and only asks you to merge.",
    "skills": [
      "Engineering playbook"
    ],
    "routines": [],
    "integrations": [
      "Notion"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/engineer-bot"
  },
  {
    "id": "love",
    "name": "Love ❤️",
    "creatorName": "Danny Buck",
    "categories": [
      "Personal"
    ],
    "description": "Takes the admin out of being a good Partner so the attention can go where it counts. Reminds, researches, and queues dates, tables, and presents; you book, buy, and show up.",
    "skills": [],
    "routines": [
      "Monday date check",
      "Monthly small gift",
      "Wednesday question"
    ],
    "integrations": [
      "Google Calendar"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/love"
  },
  {
    "id": "luma-pages",
    "name": "Luma Pages",
    "creatorName": "Jenna Nanpei",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Builds and updates private Luma event pages for field marketers — copy, branding, registration settings, capacity and waitlist, and registration-list hygiene. Pairs with a Notion docs agent so the event brief and Luma page stay in sync.",
    "skills": [],
    "routines": [],
    "integrations": [
      "Notion"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/luma-pages"
  },
  {
    "id": "echo",
    "name": "Meeting Recap Deck",
    "creatorName": "Krista Letz",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Turns your meeting notes into a recap deck in your slide template. Works from notes you paste or upload, and never invents a quote.",
    "skills": [
      "Build the recap deck",
      "Getting started",
      "Next steps to tickets",
      "Read the slide template",
      "Recap note without slides",
      "Share the approved recap",
      "Themes across meetings",
      "Update one slide"
    ],
    "routines": [
      "Friday recap roundup",
      "Post-meeting recap draft"
    ],
    "integrations": [
      "figma",
      "Gmail",
      "Gong",
      "Google Calendar",
      "Google Slides",
      "Granola",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/echo"
  },
  {
    "id": "nightly-audit-engineer",
    "name": "Nightly Audit Engineer",
    "creatorName": "Lingxi Li",
    "categories": [
      "Engineering",
      "From Grok Bot Team"
    ],
    "description": "A nightly engineering auditor that researches a whole codebase, then ships one cleanup PR per area. Defaults to 4am and asks when to run before it starts.",
    "skills": [],
    "routines": [
      "Nightly code-quality audit (4am)"
    ],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/nightly-audit-engineer"
  },
  {
    "id": "nyc-parent",
    "name": "NYC Parent",
    "creatorName": "Dennison",
    "categories": [
      "Personal"
    ],
    "description": "A family chief of staff for New York City parents. It tracks school, calendar, activities, and household logistics, turns incoming information into next actions, and keeps adults in control of spending, messages, and private information.",
    "skills": [],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/nyc-parent"
  },
  {
    "id": "office-ops-desk",
    "name": "Office Ops Desk",
    "creatorName": "Erika Cabrera",
    "categories": [
      "From Grok Bot Team",
      "Operations"
    ],
    "description": "Tracks office shipments, facilities issues, and team birthdays, then writes the digests. Works from a pasted list or a spreadsheet, and never sends without you.",
    "skills": [
      "Build the office ops ledger",
      "Getting started",
      "Late shipment follow-up",
      "New hire setup",
      "Sync to Notion, Linear, and Slack",
      "Team celebrations list",
      "Weekly facilities digest"
    ],
    "routines": [
      "Daily shipment status",
      "Team celebrations reminder",
      "Weekly facilities digest"
    ],
    "integrations": [
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/office-ops-desk"
  },
  {
    "id": "pg",
    "name": "Outbound Prospecting",
    "creatorName": "Krista Letz",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Finds prospects that match your ideal customer, then drafts a first message to each one. Every name is researched on the public web, and nothing sends without your yes.",
    "skills": [
      "Build the target list",
      "Draft a first touch",
      "Draft a follow-up",
      "Getting started",
      "Handle a reply",
      "Research a prospect",
      "Sharpen what is working",
      "Weekly prospecting recap"
    ],
    "routines": [
      "Friday prospecting recap",
      "Monday list top-up",
      "Weekday draft batch"
    ],
    "integrations": [
      "Gmail",
      "Google Sheets",
      "linear",
      "notion-workspace",
      "Salesforce",
      "slack",
      "X"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/pg"
  },
  {
    "id": "overheard",
    "name": "Overheard",
    "creatorName": "Lenny Rachitsky",
    "categories": [],
    "description": "Watches Reddit, Hacker News, news sites, and X for third-party mentions of your name, brand, and URLs, then sends a short weekday digest when something clears the bar. Stays quiet on dead days and never posts on your behalf.",
    "skills": [
      "overheard",
      "overheard-setup"
    ],
    "routines": [
      "Daily mention monitor"
    ],
    "integrations": [
      "Slack",
      "X"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/overheard"
  },
  {
    "id": "tally",
    "name": "Paid Media Report Desk",
    "creatorName": "Miguel Cruz",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Turns your Google Ads, Meta, and LinkedIn exports into one weekly report with commentary. Answers reporting asks in Slack with real numbers, and never posts without your yes.",
    "skills": [
      "Answer a reporting ask",
      "Getting started",
      "Map an export",
      "Monthly paid media report",
      "Weekly paid media report",
      "What moved and why"
    ],
    "routines": [
      "Monthly paid media report",
      "Reporting ask watch",
      "Weekly paid media report"
    ],
    "integrations": [
      "Databricks SQL",
      "Gmail",
      "Google Sheets",
      "hex",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/tally"
  },
  {
    "id": "dan-lanning",
    "name": "Partnerships Call Coach",
    "creatorName": "Jenna Nanpei",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Pitch and delivery coach for partnership, sponsorship, and high-stakes discovery calls. Reviews real call transcripts and returns sharp, evidence-based coaching — what landed, what to tighten, and exact phrasing upgrades — so feedback compounds over time.",
    "skills": [],
    "routines": [
      "Post-pitch call review"
    ],
    "integrations": [
      "Google Calendar",
      "Notion"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/dan-lanning"
  },
  {
    "id": "pipeline-health-and-forecast",
    "name": "Pipeline Pulse",
    "creatorName": "Krista Letz",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Scans your full pipeline for movement, stale next steps, forecast risk, and CRM gaps. Shows what changed across the book and drafts the updates needed to keep the forecast honest.",
    "skills": [
      "agent-orchestration",
      "humanizer",
      "pipeline-pulse"
    ],
    "routines": [
      "Weekday pipeline pulse"
    ],
    "integrations": [
      "Gmail",
      "Google Sheets",
      "Granola",
      "Notion",
      "Salesforce",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/pipeline-health-and-forecast"
  },
  {
    "id": "pitch-deck-coach",
    "name": "Pitch Deck Coach",
    "creatorName": "Hiten Shah",
    "categories": [
      "Sales"
    ],
    "description": "Reviews a pitch deck and reports what an investor is likely to understand, believe, question, and remember, then helps strengthen the story, evidence, and slides.",
    "skills": [
      "pdc-methodology",
      "pdc-modes",
      "pdc-workspace",
      "Pitch Deck Coach"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/pitch-deck-coach"
  },
  {
    "id": "product-idea-stress-test",
    "name": "Product Idea Stress Test",
    "creatorName": "Hiten Shah",
    "categories": [
      "Product"
    ],
    "description": "Investigates a product or startup idea for founders. Surfaces what has to be true, evidence for and against, the assumption most likely to kill it, and what to test next.",
    "skills": [
      "pist-evidence-investigator",
      "pist-experiment-designer",
      "pist-method-codifier"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/product-idea-stress-test"
  },
  {
    "id": "customer-question-drafter",
    "name": "Product Support Inbox Assistant",
    "creatorName": "Anoop Baliga",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Helps you find and draft answers to product questions. Never sends emails without you.",
    "skills": [],
    "routines": [],
    "integrations": [
      "Gmail",
      "Granola",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/customer-question-drafter"
  },
  {
    "id": "projects-manager",
    "name": "Projects Manager",
    "creatorName": "Eric Zakariasson",
    "categories": [
      "Engineering",
      "From Grok Bot Team"
    ],
    "description": "Runs your team's projects from Notion: one row per project, a channel per project, and tasks your specialist bots claim. You decide, agents execute, and it never does the specialist work itself.",
    "skills": [
      "Grok Bot project ops"
    ],
    "routines": [],
    "integrations": [
      "Notion",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/projects-manager"
  },
  {
    "id": "mr-toms",
    "name": "Recruiting Coordinator",
    "creatorName": "Tommy Hansen",
    "categories": [
      "From Grok Bot Team",
      "Recruiting & People"
    ],
    "description": "Schedules interview loops, preps your interviewers, and chases what's stalled. Works from your calendar or a pasted list, and never emails a candidate without you.",
    "skills": [
      "Build the hiring tracker",
      "Candidate message drafts",
      "Getting started",
      "Interviewer coaching",
      "Interviewer prep packet",
      "Run the debrief",
      "Schedule an interview loop",
      "Stalled loop follow-ups"
    ],
    "routines": [
      "Afternoon loop check",
      "Candidate reply drafts",
      "Daily hiring brief",
      "Evening interview prep",
      "Interview coaching review",
      "Urgent thread check",
      "Weekly pipeline review"
    ],
    "integrations": [
      "Ashby",
      "figma",
      "Gmail",
      "Google Calendar",
      "Google Sheets",
      "Granola",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/mr-toms"
  },
  {
    "id": "researchy",
    "name": "Researchy",
    "creatorName": "Farzad",
    "categories": [
      "Engineering"
    ],
    "description": "A research and fact-check desk that runs every pass on the latest Grok model with live web search. For anyone who needs sourced, dated claims instead of a training-only answer.",
    "skills": [
      "Grok CLI research pass"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/researchy"
  },
  {
    "id": "sales-call-coach",
    "name": "Sales Call Coach",
    "creatorName": "Daniel Brill",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Scores your sales calls and tells you what to fix before the next one. Works from a pasted transcript or an uploaded recording.",
    "skills": [
      "Call scorecard",
      "Coaching trends",
      "Discovery question bank",
      "Filler and pacing check",
      "Getting started",
      "Next step repair",
      "Objection replay",
      "Pre-call plan"
    ],
    "routines": [
      "Objection drill",
      "Weekly coaching recap"
    ],
    "integrations": [
      "Gong",
      "Google Calendar",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/sales-call-coach"
  },
  {
    "id": "seo-aeo-desk",
    "name": "SEO & AEO Desk",
    "creatorName": "Adam Tanguay",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Turns your keywords into content ideas and writer-ready briefs for search and AI answers. Works from a pasted keyword list or your Search Console.",
    "skills": [
      "Answer engine question map",
      "Extra recurring checks",
      "Getting started",
      "Keyword and question research",
      "Page audit and refresh plan",
      "Weekly search report",
      "Writer content brief"
    ],
    "routines": [
      "Content ideas digest",
      "Topic watch",
      "Weekly search report"
    ],
    "integrations": [
      "Google Sheets",
      "hex",
      "linear",
      "notion-workspace",
      "Profound",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/seo-aeo-desk"
  },
  {
    "id": "signal-prospector",
    "name": "Signal Prospector",
    "creatorName": "Krista Letz",
    "categories": [
      "From Grok Bot Team",
      "Sales"
    ],
    "description": "Finds the accounts and people in your CRM and product data that just showed intent, ranks them, and drafts the first touch. Runs on a schedule, explains every signal, and nothing sends without your yes.",
    "skills": [
      "account-tiering",
      "contact-ranking",
      "first-touch-drafts",
      "getting-started",
      "signal-scan"
    ],
    "routines": [
      "Monday signal digest"
    ],
    "integrations": [
      "Attio",
      "Clay",
      "Gmail",
      "HubSpot",
      "Hunter",
      "Mixpanel",
      "Salesforce",
      "Slack",
      "X"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/signal-prospector"
  },
  {
    "id": "site-audit",
    "name": "Site Audit",
    "creatorName": "Shimecki",
    "categories": [
      "Marketing"
    ],
    "description": "SEO + content + speed + a11y + CRO + schema audit. Scored, P0/P1/P2, evidence URLs. Monthly diff. No invented metrics.",
    "skills": [],
    "routines": [
      "Monthly site re-audit",
      "Weekly audit self-improve"
    ],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/site-audit"
  },
  {
    "id": "skippy",
    "name": "skippy",
    "creatorName": "Matt Palmer",
    "categories": [
      "From Grok Bot Team",
      "Personal"
    ],
    "description": "A San Francisco street-cleaning assistant. Paste a Maps pin, address, or intersection and it tells you the next posted sweep on that curb. Uses public city data. Never claims a stall is legal.",
    "skills": [
      "SF street cleaning lookup"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/skippy"
  },
  {
    "id": "image-gen-bot",
    "name": "Stills & Clips Desk",
    "creatorName": "Matt Palmer",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "Pulls stills, thumbnails, and short clips out of your footage, sized for where they go. Cleans up screenshots for docs too, and writes the caption and alt text.",
    "skills": [
      "Export sizes, captions, and alt text",
      "Getting started",
      "Look and size sheet",
      "Pull a short clip",
      "Pull a still from footage",
      "Screenshot cleanup for docs"
    ],
    "routines": [
      "Weekly pull queue"
    ],
    "integrations": [
      "figma",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/image-gen-bot"
  },
  {
    "id": "sherlock",
    "name": "Talent Discovery",
    "creatorName": "Tommy Hansen",
    "categories": [
      "From Grok Bot Team",
      "Recruiting & People"
    ],
    "description": "Finds candidates for open roles that match your criteria and aren't already in your ATS.",
    "skills": [
      "Dedupe against your pipeline",
      "Draft outreach",
      "Getting started",
      "Lookalike search",
      "Read the role",
      "Role market read",
      "Share the shortlist",
      "Shortlist review",
      "Source a batch"
    ],
    "routines": [
      "Daily candidate batch",
      "Weekly sourcing recap"
    ],
    "integrations": [
      "Ashby",
      "figma",
      "Gmail",
      "Google Sheets",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/sherlock"
  },
  {
    "id": "tech-demos",
    "name": "Tech Demos",
    "creatorName": "Matt Palmer",
    "categories": [
      "From Grok Bot Team",
      "Personal"
    ],
    "description": "Weekday X-bookmark scout that picks one new library to demo, asks for approval, then plans and builds it in a sticky monorepo with a Cursor cloud agent. For anyone who wants a daily public-tech playground, not a changelog digest.",
    "skills": [
      "Project planning"
    ],
    "routines": [
      "Daily X tech scout"
    ],
    "integrations": [
      "X"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/tech-demos"
  },
  {
    "id": "the-morning-newspaper",
    "name": "The Morning Newspaper",
    "creatorName": "Karen X. Cheng",
    "categories": [
      "Personal"
    ],
    "description": "A newspaper customized to you. It pulls from your email and calendar, lays it out for you, and prints while you sleep. Created by @karenxcheng",
    "skills": [
      "Morning newspaper bootstrap"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/the-morning-newspaper"
  },
  {
    "id": "tinkabot",
    "name": "tinkabot",
    "creatorName": "Lauren Tan",
    "categories": [
      "Engineering",
      "From Grok Bot Team"
    ],
    "description": "Wraps an API into a Cursor/Agent Plugin (MCP + skills). Data shape first, smallest scaffold that works, prove locally, then ask once for affiliation and publish to Marketplace or cursor.directory.",
    "skills": [
      "prove-plugin-local",
      "publish-cursor-plugin",
      "wrap-api-as-plugin"
    ],
    "routines": [],
    "integrations": [
      "pstack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/tinkabot"
  },
  {
    "id": "tradbot-2",
    "name": "Tradbot",
    "creatorName": "Claire Vo",
    "categories": [],
    "description": "Watches your personal email and calendar so school forms, bills, and RSVPs don't slip. Drafts the reply, catches the pickup clash, and never sends without you.",
    "skills": [
      "Family calendar briefs",
      "Kitchen table newspaper",
      "Monthly parent note"
    ],
    "routines": [
      "Afternoon pickup check",
      "Kitchen table newspaper",
      "Monthly parent note",
      "Weekday family digest",
      "Weekend preview"
    ],
    "integrations": [
      "Gmail",
      "Google Calendar",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/tradbot-2"
  },
  {
    "id": "best-video-editor",
    "name": "Video Edit Desk",
    "creatorName": "X Freeze",
    "categories": [
      "Marketing"
    ],
    "description": "Turns uploaded footage into cut clips, burned-in captions, and platform-sized exports. Works from your notes and never overwrites the original.",
    "skills": [
      "Captions and transcript",
      "Cut from your notes",
      "Footage intake",
      "Getting started",
      "Platform versions and delivery check",
      "Short clips from a long video"
    ],
    "routines": [
      "Weekly cut queue"
    ],
    "integrations": [
      "figma",
      "linear",
      "notion-workspace",
      "slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/best-video-editor"
  },
  {
    "id": "webby",
    "name": "Webby",
    "creatorName": "Farzad",
    "categories": [
      "Personal"
    ],
    "description": "Website admin. Owns a personal site (rebuild + live fallback, exclusive long-form and newsletter) and a public weekday dashboard. Also owns newsletter sends: exclusive the same day a new piece ships; digest the next morning after that day's social pulse is finished. Create-only, no deletes. Strip AI-isms. Cost-lean. An orchestrator routes; this bot ships.",
    "skills": [
      "Strip AI-isms"
    ],
    "routines": [
      "Daily Digest social pulse",
      "Daily Exclusive long-form check",
      "Post-fill dashboard ship",
      "Site PR follow-up",
      "Weekday close dashboard book",
      "Weekday hourly dashboard book"
    ],
    "integrations": [
      "X"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/webby"
  },
  {
    "id": "writing-bot",
    "name": "Writing Bot",
    "creatorName": "Matt Palmer",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "A writing partner for drafting and revising essays, emails, docs, and other prose. It uses a structured revision workflow so the result is clearer and better organized while keeping the writer's meaning, facts, and voice.",
    "skills": [
      "Writing revision"
    ],
    "routines": [],
    "integrations": [],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/writing-bot"
  },
  {
    "id": "wtd",
    "name": "WTD",
    "creatorName": "Jenna Nanpei",
    "categories": [
      "From Grok Bot Team",
      "Marketing"
    ],
    "description": "WTD is a VIP hospitality planning partner for marketing ops — project-plan and status rhythm across tentpoles and ticket banks, nomination-sheet tracking, marketing-visible status hubs, and decks or agendas. Sales owns guest inviting; this bot keeps the plan and status clean without dumping private notes onto shared pages.",
    "skills": [
      "Comms source of truth",
      "Deck QA standards",
      "Email reply standards",
      "GTM branded deck",
      "Outstanding asks review",
      "VIP AE nomination sheet"
    ],
    "routines": [
      "VIP Plan status refresh"
    ],
    "integrations": [
      "Gmail",
      "Google Drive",
      "Notion",
      "Slack"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/wtd"
  },
  {
    "id": "x-brief",
    "name": "X Brief",
    "creatorName": "Dan McAteer",
    "categories": [
      "Marketing"
    ],
    "description": "Turns the accounts and topics you pick on X into one short daily brief. Reads your X connection or handles you paste, and never posts on your behalf.",
    "skills": [
      "Build the X watch list",
      "Daily X brief",
      "Draft a post or reply",
      "Getting started",
      "Read a thread or post",
      "Weekly X recap"
    ],
    "routines": [
      "Daily X brief",
      "Weekly X recap"
    ],
    "integrations": [
      "linear",
      "notion-workspace",
      "slack",
      "X"
    ],
    "sourceUrl": "https://x.ai/bot/marketplace/bots/x-brief"
  }
];
