import { describe, it, expect, vi } from "vitest";
import { classifyArchivedMail, buildMailEvidence } from "../../packages/gateway/src/mail/classify.js";
import { JEV_EMAIL_TRIAGE_ANSWER_IDS } from "@matrix-os/contracts";
const result = { requestId: "jev_req_1234567890", recipe: "email-triage-v1", model: "typesafe/jev", latencyMs: 1, answers: JEV_EMAIL_TRIAGE_ANSWER_IDS.map(id => ({ id, type: "boolean", probability: id === "newsletter" ? .98 : 0 })) };
describe("archive Jev", () => {
    it("reuses persisted validated seven scores and keeps correction", async () => { let row: any; const store = { get: async () => row, save: vi.fn(async (_key: string, value: any) => { row = value; }) }; const jev = { evaluate: vi.fn(async () => result) }; const input = { ownerId: "owner", accountId: "account", messageId: "m1", contentDigest: "a".repeat(64), mail: { subject: "Title", sender: "Publisher", text: "Hello", html: "" }, modelPolicy: "funded-v1", store, jev, correction: "excluded" as const }; expect((await classifyArchivedMail(input)).category).toBe("excluded"); await classifyArchivedMail(input); expect(jev.evaluate).toHaveBeenCalledTimes(1); expect(row.result.answers).toHaveLength(7); });
    it("retains deterministic paid idempotency key after ambiguous provider error", async () => { const evaluate = vi.fn().mockRejectedValue(Object.assign(Error(), { code: "unknown" })); const input = { ownerId: "o", accountId: "a", messageId: "m", contentDigest: "b".repeat(64), mail: { subject: "", sender: "", text: "Hello", html: "" }, modelPolicy: "v1", store: { get: async () => null, save: vi.fn() }, jev: { evaluate } }; await expect(classifyArchivedMail(input)).rejects.toThrow(); await expect(classifyArchivedMail(input)).rejects.toThrow(); expect(evaluate.mock.calls[0][1].idempotencyKey).toBe(evaluate.mock.calls[1][1].idempotencyKey); expect(input.store.save).not.toHaveBeenCalled(); });
    it("bounds unicode evidence at32KiB and declares truncated context unverified", () => { const evidence = buildMailEvidence({ subject: "日".repeat(10000), sender: "sender", text: "😀".repeat(20000), html: "" }); expect(Buffer.byteLength(evidence.state)).toBeLessThanOrEqual(32768); expect(evidence.verified).toBe(false); expect(evidence.state).toContain('"truncated":true'); });
});
it("uses inert HTML evidence and never treats missing or partial body as verified", () => { expect(buildMailEvidence({ subject: '', sender: '', text: '', html: '<p>hello</p>' }).verified).toBe(true); expect(buildMailEvidence({ subject: '', sender: '', text: '', html: '' }).verified).toBe(false); expect(buildMailEvidence({ subject: '', sender: '', text: 'Hello', html: '', partial: true }).state).toContain('"partial":true'); });
