import {describe,it,expect,vi} from 'vitest';
import {createMailService} from '../../packages/gateway/src/mail/service.js';
const source={ownerId:'owner',accountId:'account',connectionId:'gmail-connection',email:'a@example.com',accountLabel:'Primary',group:'personal',namespace:'a'.repeat(64),revision:1};
function setup(){const repo={listGrantedSources:vi.fn(async()=>[source]),getGrantedMessageById:vi.fn(async()=>null),getSyncJob:vi.fn(async()=>null),registerSource:vi.fn(async()=>source),grantConsumer:vi.fn(),revokeConsumer:vi.fn(),kysely:{transaction:()=>({execute:async(fn:Function)=>fn({})})}};const transport={inventory:vi.fn(async()=>[]),call:vi.fn()};const sync=vi.fn();return{repo,transport,sync,service:createMailService({repository:repo as never,objects:{} as never,transport,ownerId:'owner',sync,notify:vi.fn()})};}
describe('mail service scopes',()=>{
 it('does not reveal account metadata or bodies without grants',async()=>{const t=setup();t.repo.listGrantedSources.mockResolvedValue([]);expect(await t.service.handle('owner',{appId:'folio',action:'sources',payload:{}},AbortSignal.timeout(1000))).toMatchObject({sources:[]});await expect(t.service.handle('owner',{appId:'edition',action:'message',payload:{id:'one'}},AbortSignal.timeout(1000))).rejects.toMatchObject({status:404});});
 it('rejects rebound email before any account grant or worker enqueue',async()=>{const t=setup();t.transport.inventory.mockResolvedValue([{id:'gmail-connection',service:'gmail',account_label:'Primary',account_email:'other@example.com',status:'active'}] as never);await expect(t.service.handle('owner',{appId:'edition',action:'connect',payload:{connectionId:'gmail-connection',expectedEmail:'a@example.com',scope:'work',historyMonths:3}},AbortSignal.timeout(1000))).rejects.toMatchObject({status:403});expect(t.repo.registerSource).not.toHaveBeenCalled();expect(t.sync).not.toHaveBeenCalled();});
 it('rejects cross-owner and consumer writes independently of renderer',async()=>{const t=setup();await expect(t.service.handle('other',{appId:'edition',action:'sources',payload:{}},AbortSignal.timeout(1000))).rejects.toMatchObject({status:403});await expect(t.service.handle('owner',{appId:'atlas',action:'sync',payload:{sourceId:'account'}},AbortSignal.timeout(1000))).rejects.toMatchObject({status:403});});
});
