substitutions:
  _IMAGE: europe-west3-docker.pkg.dev/matrix-os-1144/matrix-os/matrix-platform:manual
  _CACHE_IMAGE: europe-west3-docker.pkg.dev/matrix-os-1144/matrix-os/matrix-platform:buildcache
  _NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ''
  _NEXT_PUBLIC_CLERK_SIGN_IN_URL: '/sign-in'
  _NEXT_PUBLIC_CLERK_SIGN_UP_URL: '/sign-up'
  _NEXT_PUBLIC_POSTHOG_KEY: ''
  _NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN: ''
  _NEXT_PUBLIC_POSTHOG_HOST: ''
  _NEXT_PUBLIC_POSTHOG_API_HOST: ''
  _NEXT_PUBLIC_MATRIX_APP_URL: 'https://app.matrix-os.com'

steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - -f
      - Dockerfile.platform
      - --build-arg
      - BUILDKIT_INLINE_CACHE=1
      - --cache-from
      - ${_CACHE_IMAGE}
      - --build-arg
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - --build-arg
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${_NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      - --build-arg
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${_NEXT_PUBLIC_CLERK_SIGN_UP_URL}
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_KEY=${_NEXT_PUBLIC_POSTHOG_KEY}
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN=${_NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN}
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_HOST=${_NEXT_PUBLIC_POSTHOG_HOST}
      - --build-arg
      - NEXT_PUBLIC_POSTHOG_API_HOST=${_NEXT_PUBLIC_POSTHOG_API_HOST}
      - --build-arg
      - NEXT_PUBLIC_MATRIX_APP_URL=${_NEXT_PUBLIC_MATRIX_APP_URL}
      - -t
      - ${_IMAGE}
      - -t
      - ${_CACHE_IMAGE}
      - .

images:
  - ${_IMAGE}
  - ${_CACHE_IMAGE}
