import { _electron } from "playwright";
const app = await _electron.launch({ args: ["desktop/out/main/index.js"], env: { ...process.env, OPERATOR_GATEWAY_URL: "https://app.matrix-os.com", OPERATOR_USER_DATA_DIR: process.env.HOME + "/.matrixos-operator-live" } });
const page = await app.firstWindow();
const errs = [];
page.on("pageerror", (e) => errs.push(e.message.slice(0,120)));
await page.waitForTimeout(4500);
const body = (await page.textContent("body").catch(()=>"")) ?? "";
await page.screenshot({ path: "desktop/screenshots/live/new-ui.png" }).catch(()=>{});
console.log("RESULT signedIn=" + /Welcome|Home|Agents|Projects|Sessions/.test(body) + " errors=" + (errs.length?errs.join("|"):"none"));
await app.close();
