import type { Theme } from "@/hooks/useTheme";

const FONTS = {
  mono: "JetBrains Mono, monospace",
  sans: "Inter, system-ui, sans-serif",
};

export const MATRIX_OS_LIGHT_THEME: Theme = {
  name: "light",
  mode: "light",
  colors: {
    background: "#FAFAF9",
    foreground: "#32352E",
    card: "#FCFCF8",
    "card-foreground": "#32352E",
    popover: "#FCFCF8",
    "popover-foreground": "#32352E",
    primary: "#434E3F",
    "primary-foreground": "#F8F7EF",
    secondary: "#F1F0E3",
    "secondary-foreground": "#3E4339",
    muted: "#E1E1D0",
    "muted-foreground": "#747668",
    accent: "#F1F0E3",
    "accent-foreground": "#3E4339",
    destructive: "#D74A3A",
    success: "#3A7D44",
    warning: "#E0A12E",
    border: "#D8D6C7",
    input: "#D8D6C7",
    ring: "#D06F25",
  },
  fonts: { ...FONTS },
  radius: "0.75rem",
};

export const MATRIX_OS_DARK_THEME: Theme = {
  name: "matrix-dark",
  mode: "dark",
  colors: {
    background: "#1C2019",
    foreground: "#F0EFE5",
    card: "#20241C",
    "card-foreground": "#F0EFE5",
    popover: "#20241C",
    "popover-foreground": "#F0EFE5",
    primary: "#9CB77A",
    "primary-foreground": "#15180F",
    secondary: "#2A2E22",
    "secondary-foreground": "#C9C7B7",
    muted: "#2A2E22",
    "muted-foreground": "#858578",
    accent: "#2A2E22",
    "accent-foreground": "#F0EFE5",
    destructive: "#D85E5E",
    success: "#5FB85F",
    warning: "#E0A12E",
    border: "#2D3127",
    input: "#2D3127",
    ring: "#CF7835",
  },
  fonts: { ...FONTS },
  radius: "0.75rem",
};

export const MATRIX_OS_NEON_THEME: Theme = {
  name: "matrix",
  mode: "dark",
  colors: {
    background: "#020A02",
    foreground: "#D8FFD9",
    card: "#04140A",
    "card-foreground": "#D8FFD9",
    popover: "#04140A",
    "popover-foreground": "#D8FFD9",
    primary: "#39FF6A",
    "primary-foreground": "#020A02",
    secondary: "#0A1F10",
    "secondary-foreground": "#5BF08A",
    muted: "#0A1F10",
    "muted-foreground": "#2FBF55",
    accent: "#0A1F10",
    "accent-foreground": "#D8FFD9",
    destructive: "#FF5D5D",
    success: "#39FF6A",
    warning: "#A5FF5C",
    border: "#0E5A26",
    input: "#0E5A26",
    ring: "#39FF6A",
  },
  fonts: { ...FONTS },
  radius: "0.75rem",
};

export const MATRIX_OS_APP_THEME_OPTIONS = [
  {
    id: "light",
    label: "Light",
    description: "Warm paper",
    theme: MATRIX_OS_LIGHT_THEME,
    preview: {
      background: "#FAFAF9",
      border: "#00000014",
      stripe: "#3E4339",
      dotA: "#3A7D44",
      dotB: "#D06F25",
    },
  },
  {
    id: "matrix-dark",
    label: "Matrix OS Dark",
    description: "Warm dark",
    theme: MATRIX_OS_DARK_THEME,
    preview: {
      background: "#15180F",
      border: "#2D3127",
      stripe: "#C9C7B7",
      dotA: "#5FB85F",
      dotB: "#CF7835",
    },
  },
  {
    id: "matrix",
    label: "Matrix",
    description: "Phosphor green",
    theme: MATRIX_OS_NEON_THEME,
    preview: {
      background: "#050805",
      border: "#16271B",
      stripe: "#39FF6A",
      dotA: "#5BF08A",
      dotB: "#2ECC5A",
    },
  },
] as const;

export const THEME_PRESETS: Theme[] = [
  MATRIX_OS_LIGHT_THEME,
  MATRIX_OS_DARK_THEME,
  MATRIX_OS_NEON_THEME,
  {
    name: "default",
    mode: "light",
    colors: {
      background: "#FAFAF9",
      foreground: "#32352E",
      card: "#FCFCF8",
      "card-foreground": "#32352E",
      popover: "#FCFCF8",
      "popover-foreground": "#32352E",
      primary: "#434E3F",
      "primary-foreground": "#FAFAF5",
      secondary: "#F1F0E3",
      "secondary-foreground": "#3E4339",
      muted: "#E1E1D0",
      "muted-foreground": "#747668",
      accent: "#F1F0E3",
      "accent-foreground": "#3E4339",
      destructive: "#D74A3A",
      success: "#3A7D44",
      warning: "#E0A12E",
      border: "#D8D6C7",
      input: "#D8D6C7",
      ring: "#D06F25",
    },
    fonts: { ...FONTS },
    radius: "0.75rem",
  },
  {
    name: "dark",
    mode: "dark",
    colors: {
      background: "#1a1a2e",
      foreground: "#e0e0e0",
      card: "#232340",
      "card-foreground": "#e0e0e0",
      popover: "#232340",
      "popover-foreground": "#e0e0e0",
      primary: "#7c6ff7",
      "primary-foreground": "#ffffff",
      secondary: "#2a2a45",
      "secondary-foreground": "#b0b0c0",
      muted: "#2a2a45",
      "muted-foreground": "#8888a0",
      accent: "#2a2a45",
      "accent-foreground": "#b0b0c0",
      destructive: "#ef4444",
      success: "#34d399",
      warning: "#fbbf24",
      border: "#3a3a5c",
      input: "#3a3a5c",
      ring: "#7c6ff7",
    },
    fonts: { ...FONTS },
    radius: "0.75rem",
  },
  {
    name: "nord",
    mode: "dark",
    colors: {
      background: "#2e3440",
      foreground: "#eceff4",
      card: "#3b4252",
      "card-foreground": "#eceff4",
      popover: "#3b4252",
      "popover-foreground": "#eceff4",
      primary: "#88c0d0",
      "primary-foreground": "#2e3440",
      secondary: "#434c5e",
      "secondary-foreground": "#d8dee9",
      muted: "#434c5e",
      "muted-foreground": "#81a1c1",
      accent: "#434c5e",
      "accent-foreground": "#d8dee9",
      destructive: "#bf616a",
      success: "#a3be8c",
      warning: "#ebcb8b",
      border: "#434c5e",
      input: "#434c5e",
      ring: "#88c0d0",
    },
    fonts: { ...FONTS },
    radius: "0.75rem",
  },
  {
    name: "dracula",
    mode: "dark",
    colors: {
      background: "#282a36",
      foreground: "#f8f8f2",
      card: "#44475a",
      "card-foreground": "#f8f8f2",
      popover: "#44475a",
      "popover-foreground": "#f8f8f2",
      primary: "#bd93f9",
      "primary-foreground": "#282a36",
      secondary: "#44475a",
      "secondary-foreground": "#f8f8f2",
      muted: "#44475a",
      "muted-foreground": "#6272a4",
      accent: "#44475a",
      "accent-foreground": "#f8f8f2",
      destructive: "#ff5555",
      success: "#50fa7b",
      warning: "#f1fa8c",
      border: "#6272a4",
      input: "#6272a4",
      ring: "#bd93f9",
    },
    fonts: { ...FONTS },
    radius: "0.75rem",
  },
  {
    name: "solarized-light",
    mode: "light",
    colors: {
      background: "#fdf6e3",
      foreground: "#073642",
      card: "#eee8d5",
      "card-foreground": "#073642",
      popover: "#eee8d5",
      "popover-foreground": "#073642",
      primary: "#268bd2",
      "primary-foreground": "#fdf6e3",
      secondary: "#eee8d5",
      "secondary-foreground": "#586e75",
      muted: "#eee8d5",
      "muted-foreground": "#93a1a1",
      accent: "#eee8d5",
      "accent-foreground": "#586e75",
      destructive: "#dc322f",
      success: "#859900",
      warning: "#b58900",
      border: "#93a1a1",
      input: "#93a1a1",
      ring: "#268bd2",
    },
    fonts: { ...FONTS },
    radius: "0.75rem",
  },
  {
    name: "solarized-dark",
    mode: "dark",
    colors: {
      background: "#002b36",
      foreground: "#fdf6e3",
      card: "#073642",
      "card-foreground": "#fdf6e3",
      popover: "#073642",
      "popover-foreground": "#fdf6e3",
      primary: "#268bd2",
      "primary-foreground": "#fdf6e3",
      secondary: "#073642",
      "secondary-foreground": "#93a1a1",
      muted: "#073642",
      "muted-foreground": "#586e75",
      accent: "#073642",
      "accent-foreground": "#93a1a1",
      destructive: "#dc322f",
      success: "#859900",
      warning: "#b58900",
      border: "#586e75",
      input: "#586e75",
      ring: "#268bd2",
    },
    fonts: { ...FONTS },
    radius: "0.75rem",
  },
];

export const RETRO_THEME: Theme = {
  name: "retro",
  mode: "light",
  style: "neumorphic",
  colors: {
    background: "#D4D4D4",
    foreground: "#2D2D2D",
    card: "#D4D4D4",
    "card-foreground": "#2D2D2D",
    popover: "#D4D4D4",
    "popover-foreground": "#2D2D2D",
    primary: "#008080",
    "primary-foreground": "#ffffff",
    secondary: "#DCDCDC",
    "secondary-foreground": "#3A3A3A",
    muted: "#C8C8C8",
    "muted-foreground": "#5A5A5A",
    accent: "#DCDCDC",
    "accent-foreground": "#3A3A3A",
    destructive: "#C42B1C",
    success: "#16825D",
    warning: "#9D8500",
    border: "#BEBEBE",
    input: "#C8C8C8",
    ring: "#008080",
    // Neumorphic shadow tokens — auto-become CSS vars via applyTheme()
    "neu-shadow-light": "rgba(255, 255, 255, 0.7)",
    "neu-shadow-dark": "rgba(163, 163, 163, 0.5)",
    "neu-distance": "5px",
    "neu-blur": "10px",
  },
  fonts: {
    mono: "JetBrains Mono, monospace",
    sans: "Tahoma, Geneva, sans-serif",
  },
  radius: "0.5rem",
};

export const MACOS_GLASS_THEME: Theme = {
  name: "macos-glass",
  mode: "light",
  style: "macos-glass",
  colors: {
    background: "#F5F5F7",
    foreground: "#1D1D1F",
    card: "#FFFFFF",
    "card-foreground": "#1D1D1F",
    popover: "#FFFFFF",
    "popover-foreground": "#1D1D1F",
    primary: "#0A84FF",
    "primary-foreground": "#FFFFFF",
    secondary: "#E8E8ED",
    "secondary-foreground": "#3A3A3C",
    muted: "#F2F2F7",
    "muted-foreground": "#6E6E73",
    accent: "#E8E8ED",
    "accent-foreground": "#1D1D1F",
    destructive: "#FF3B30",
    success: "#34C759",
    warning: "#FF9500",
    border: "#D1D1D6",
    input: "#D1D1D6",
    ring: "#0A84FF",
  },
  fonts: {
    mono: "SF Mono, Menlo, monospace",
    sans: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", sans-serif',
  },
  radius: "0.875rem", // 14px
};

export const WINXP_THEME: Theme = {
  name: "winxp",
  mode: "light",
  style: "winxp",
  colors: {
    background: "#ECE9D8",
    foreground: "#1F1F1F",
    card: "#FFFFFF",
    "card-foreground": "#1F1F1F",
    popover: "#FFFFFF",
    "popover-foreground": "#1F1F1F",
    primary: "#0058E6",
    "primary-foreground": "#FFFFFF",
    secondary: "#ECE9D8",
    "secondary-foreground": "#3B3B3B",
    muted: "#ECE9D8",
    "muted-foreground": "#716F64",
    accent: "#316AC5",
    "accent-foreground": "#FFFFFF",
    destructive: "#C42B1C",
    success: "#3A7D44",
    warning: "#B88A00",
    border: "#7F9DB9",
    input: "#7F9DB9",
    ring: "#0058E6",
  },
  fonts: {
    mono: "Courier New, monospace",
    sans: 'Tahoma, Geneva, "Segoe UI", sans-serif',
  },
  radius: "0.1875rem", // 3px
};

export const WIN11_THEME: Theme = {
  name: "win11",
  mode: "light",
  style: "win11",
  colors: {
    background: "#F3F3F3",
    foreground: "#1B1B1B",
    card: "#FAFAFA",
    "card-foreground": "#1B1B1B",
    popover: "#FAFAFA",
    "popover-foreground": "#1B1B1B",
    primary: "#0067C0",
    "primary-foreground": "#FFFFFF",
    secondary: "#EAEAEA",
    "secondary-foreground": "#3A3A3A",
    muted: "#EAEAEA",
    "muted-foreground": "#616161",
    accent: "#EAEAEA",
    "accent-foreground": "#1B1B1B",
    destructive: "#C42B1C",
    success: "#0F7B0F",
    warning: "#9D5D00",
    border: "#D6D6D6",
    input: "#D6D6D6",
    ring: "#0067C0",
  },
  fonts: {
    mono: "Cascadia Code, Consolas, monospace",
    sans: '"Segoe UI Variable", "Segoe UI", system-ui, sans-serif',
  },
  radius: "0.5rem", // 8px
};

/** Design-system presets — full OS chrome restyles keyed on Theme.style. */
export const DESIGN_SYSTEM_PRESETS: Theme[] = [MACOS_GLASS_THEME, WINXP_THEME, WIN11_THEME];

THEME_PRESETS.push(RETRO_THEME, ...DESIGN_SYSTEM_PRESETS);

export function getPreset(name: string): Theme | undefined {
  return THEME_PRESETS.find((p) => p.name === name);
}
