import { viewerScript } from "./viewer.js";
import { createHash } from "node:crypto";
import type { BenchmarkReport } from "../../packages/kernel/src/memory-evaluation/runner.js";

const css = `:root{color-scheme:dark;font-family:system-ui;background:#101416;color:#e5ebe8}*{box-sizing:border-box}body{margin:0}header{padding:28px 32px;border-bottom:1px solid #314039}h1{font-size:26px;margin:0 0 8px}h2{font-size:18px}p{color:#abbab3;line-height:1.5}.layout{display:grid;grid-template-columns:290px 1fr;min-height:75vh}aside{padding:20px;border-right:1px solid #314039}main{padding:24px;min-width:0}.cards{display:flex;flex-wrap:wrap;gap:12px}.card{background:#1a2420;border:1px solid #344c40;border-radius:10px;padding:16px;min-width:180px}.card strong{display:block;font-size:24px;color:#a5e8bd}button,select,input{font:inherit;border:1px solid #476451;border-radius:6px;background:#1b2821;color:#e5ebe8;padding:9px}button{cursor:pointer;text-align:left}button:hover{background:#2b4234}.case{display:block;width:100%;margin:6px 0}select,input{width:100%;margin-bottom:12px}table{border-collapse:collapse;width:100%;margin-top:18px;font-size:14px}td,th{padding:10px;text-align:left;border-bottom:1px solid #304438}th{color:#a5e8bd}pre,textarea{white-space:pre-wrap;overflow-wrap:anywhere;background:#18221d;color:#e5ebe8;border:1px solid #344c40;border-radius:8px;padding:14px;width:100%;font:13px/1.6 ui-monospace,monospace}textarea{min-height:170px}.bad{color:#ffb3a9}.good{color:#a5e8bd}.evidence{margin:14px 0;padding:16px;border:1px solid #344c40;border-radius:8px}.path{font:13px ui-monospace,monospace;color:#a5e8bd}.small{font-size:12px}.graph{display:flex;align-items:center;gap:14px;flex-wrap:wrap}.node{border:1px solid #53775f;border-radius:8px;padding:10px}.arrow{color:#a5e8bd}label{display:block}a{color:#a5e8bd}@media(max-width:800px){.layout{grid-template-columns:1fr}aside{border-right:0;border-bottom:1px solid #314039}header,main{padding:18px}}`;

const hash = (text: string) => createHash("sha256").update(text).digest("base64");
export interface RunFailure { status: "incomplete"; reason: "aggregate-report-limit" | "artifact-limit"; retainedRuns: number; plannedRuns: number; omittedArtifacts?: string[] }
export const incompleteReportPage = '<!doctype html><html lang="en"><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; base-uri \'none\'; form-action \'none\'"><title>Matrix memory benchmark</title><h1>Benchmark run incomplete</h1><p>Output limit reached. Completed scored traces remain in results.json. Some artifacts were omitted; see run-status.json.</p></html>';
export function renderReport(reports: BenchmarkReport[], failure?: RunFailure): string {
  if (!reports.length && failure) return incompleteReportPage;
  if (!reports.length) throw new Error("Report needs at least one run");
  const data = JSON.stringify(reports).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'sha256-${hash(viewerScript)}'; style-src 'sha256-${hash(css)}'; connect-src 'none'; base-uri 'none'; form-action 'none'"><title>Matrix memory benchmark</title><style>${css}</style></head><body><header><h1>Matrix memory benchmark</h1>${failure ? `<p class="bad">Benchmark run incomplete: ${failure.reason}. Retained ${failure.retainedRuns} of ${failure.plannedRuns} planned runs. See run-status.json.</p>` : ""}<p>Compare what the agent keeps, finds, and carries into a new Chat.</p><p class="small">Synthetic development probes. Hard gates and quality scores are separate. This report is an evidence explorer; it does not implement the production Memory app or prove agent learning.</p></header><div class="layout"><aside><h2>Evidence navigator</h2><label for="adapter">Benchmark run</label><select id="adapter"></select><label for="filter">Find a scenario</label><input id="filter" placeholder="Search cases or groups"><div id="cases"></div></aside><main><div id="cards" class="cards"></div><table><thead><tr><th>Group</th><th>Queries</th><th>Recall</th><th>Complete</th><th>Status</th><th>Retrieval p95</th><th>Violations</th></tr></thead><tbody id="groups"></tbody></table><div id="detail"></div><h2>New Chat context preview</h2><p>Inspect and copy source-backed evidence. Production attachment must recheck permissions and revisions when the Chat opens.</p><textarea id="context" readonly aria-label="New Chat context preview"></textarea><button id="copy">Copy context</button><p id="contextStatus" aria-live="polite"></p><details><summary>Reproducibility and configuration</summary><pre id="metadata"></pre></details></main></div><script type="application/json" id="data">${data}</script><script>${viewerScript}</script></body></html>`;
}
