// Trusted static viewer script. All source and model text is rendered with textContent.
export const viewerScript = `const reports=JSON.parse(document.getElementById('data').textContent);const $=id=>document.getElementById(id);
let current=0,copyDisabled=false;
const pct=x=>x==null?'Unmeasured':(100*x).toFixed(1)+'%';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e};

function showSummary(){const r=reports[current];$('cards').replaceChildren();for(const [label,value]of [['Evidence recall',pct(r.summary.recall)],['Admission precision',pct(r.summary.admissionPrecision)],['Placement accuracy',pct(r.summary.placementAccuracy)],['Hard violations',r.summary.hardFailures],['Retrieval p95',(r.summary.retrievalP95Ms??0).toFixed(1)+' ms'],['Total cost',r.summary.costUsd==null?'Unmeasured':'$'+r.summary.costUsd.toFixed(4)]]){const c=text('div','', 'card');c.append(text('span',label),text('strong',String(value)));$('cards').append(c)}$('metadata').textContent=JSON.stringify({suite:r.suite,adapter:r.adapter,runtime:r.runtime,hardGatePassed:r.passed,operationErrors:r.summary.operationErrors},null,2);$('groups').replaceChildren();for(const [group,s] of Object.entries(r.groups)){const tr=document.createElement('tr');for(const v of [group,s.queryCount,pct(s.recall),pct(s.completeRate),pct(s.statusAccuracy),s.retrievalP95Ms==null?"Unmeasured":s.retrievalP95Ms.toFixed(1)+" ms",s.hardFailures])tr.append(text('td',String(v)));$('groups').append(tr)}listCases()}

function listCases(){const r=reports[current],q=$('filter').value.toLowerCase();$('cases').replaceChildren();for(const c of r.cases){if(!(c.id+' '+c.group).toLowerCase().includes(q))continue;const b=text('button',c.id+' · '+c.group,'case');b.addEventListener('click',()=>showCase(c));$('cases').append(b)}}

function showCase(c){$('detail').replaceChildren(text('h2',c.id));$('context').value='';copyDisabled=false;$('copy').disabled=false;$('contextStatus').textContent='';for(const q of c.queries){const area=text('section','');area.append(text('h3',q.text),text('p','Recall '+pct(q.recall)+' · Complete '+q.complete+' · Retrieval '+q.latencyMs.toFixed(1)+' ms · Estimated context tokens '+q.estimatedTokens),text('p',q.violations.length?'Violations: '+q.violations.join(', '):'No observed hard violations',q.violations.length?'bad':'good'));const graph=text('div','','graph');graph.append(text('div','New Chat','node'),text('span','→','arrow'));for(const e of q.evidence)graph.append(text('div',e.sourceId,'node'));area.append(graph);for(const e of q.evidence){const box=text('div','','evidence');box.append(text('div',e.path,'path'),text('p','Source '+e.sourceId+' · UTF-16 span '+e.start+'–'+e.end,'small'),text('pre',e.text));const b=text('button','Preview source excerpt');b.addEventListener('click',()=>{copyDisabled=q.evidenceTruncated;$('copy').disabled=copyDisabled;$('context').value='[evidence:'+e.sourceId+':'+e.start+'-'+e.end+']\\n'+e.text;$('contextStatus').textContent=copyDisabled?'Evidence is clipped; it may omit text credited by the score.':'Source excerpt only. This does not create a Matrix Chat.'});box.append(b);area.append(box)}const b=text('button',q.evidenceTruncated?'Preview clipped context (copy unavailable)':'Preview complete retrieved context');b.addEventListener('click',()=>{copyDisabled=q.evidenceTruncated;$('copy').disabled=copyDisabled;$('context').value=q.context;$('contextStatus').textContent=copyDisabled?'Evidence is clipped; it may omit text credited by the score.':'Estimated '+q.estimatedTokens+' tokens. Retrieved source text remains untrusted data.'});area.append(b);$('detail').append(area)}const admission=text('details','');admission.append(text('summary','Admission decisions ('+c.admissions.length+')'));for(const a of c.admissions.slice(0,100)){admission.append(text('p',(a.path??a.sourceId??'Source')+' · '+(a.retained?'retain':'skip')+' · placed: '+(a.placements??[]).join(', ')+' · expected: '+(a.expectedRetain?'retain':'skip')+' / '+(a.expectedPlacements??[]).join(', ')+(a.violations?.length?' · '+a.violations.join(', '):''),a.violations?.length?'bad':'small'))}if(c.admissions.length>100)admission.append(text('p','First 100 decisions shown; complete trace is in results.json.'));$('detail').append(admission);const trace=text('details','');trace.append(text('summary','Orchestration and usage trace'));trace.append(text('pre',JSON.stringify(c.operations,null,2)));$('detail').append(trace);for(const o of c.operations.filter(o=>o.error))$('detail').append(text('p',o.kind+': '+o.error,'bad'))}

reports.forEach((r,i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=r.adapter.name+' · '+r.suite.name+' · run '+(i+1);$('adapter').append(o)});
$('adapter').addEventListener('change',()=>{current=Number($('adapter').value);showSummary();showCase(reports[current].cases[0])});
$('filter').addEventListener('input',listCases);$('copy').addEventListener('click',async()=>{if(copyDisabled)return;try{await navigator.clipboard.writeText($('context').value);$('contextStatus').textContent='Copied evidence context'}catch(error){$('context').focus();$('context').select();$('contextStatus').textContent='Select and copy the context manually'}});showSummary();showCase(reports[0].cases[0]);`;
