// Genuine catalog/vendor assets verified on 2026-10-07.
// Keep these available even when authenticated catalog enrichment is unavailable.
export const INTEGRATION_LOGOS: Readonly<Record<string, string>> = {
  "airtable": "https://pipedream.com/s.v0/app_XBxhAl/logo/96",
  "asana": "https://pipedream.com/s.v0/app_OVWhPX/logo/96",
  "box": "https://pipedream.com/s.v0/app_1RphyX/logo/96",
  "clickup": "https://pipedream.com/s.v0/app_1NohVg/logo/96",
  "discord": "https://pipedream.com/s.v0/app_13GhGn/logo/96",
  "dropbox": "https://pipedream.com/s.v0/app_XGehk1/logo/96",
  "figma": "https://pipedream.com/s.v0/app_OkrhRR/logo/96",
  "github": "https://pipedream.com/s.v0/app_OrZhaO/logo/96",
  "gmail": "https://pipedream.com/s.v0/app_OQYhq7/logo/96",
  "google_calendar": "https://pipedream.com/s.v0/app_13Gh2V/logo/96",
  "google_docs": "https://pipedream.com/s.v0/app_1pbh98/logo/96",
  "google_drive": "https://pipedream.com/s.v0/app_1lxhk1/logo/96",
  "google_slides": "https://pipedream.com/s.v0/app_OD5h5x/logo/96",
  "google_contacts": "https://pipedream.com/s.v0/app_1xohBe/logo/96",
  "google_sheets": "https://pipedream.com/s.v0/app_168hvn/logo/96",
  "microsoft_outlook_calendar": "https://pipedream.com/s.v0/app_XbPhEP/logo/96",
  "quickbooks": "https://pipedream.com/s.v0/app_m02hWG/logo/96",
  "xero_accounting_api": "https://pipedream.com/s.v0/app_1dBh9j/logo/96",
  "zendesk": "https://pipedream.com/s.v0/app_1pbhGX/logo/96",
  "intercom": "https://pipedream.com/s.v0/app_1pbh0B/logo/96",
  "loops": "https://pipedream.com/s.v0/app_WnhP8N/logo/96",
  "lemlist": "https://pipedream.com/s.v0/app_1gKhnN/logo/96",
  "bokio": "https://www.bokio.se/assets/images/icons/favicon.ico",
  "posthog_oauth": "https://pipedream.com/s.v0/app_mo7h7A/logo/96",
  "granola": "https://www.granola.ai/favicon/favicon-96x96.png",
  "hubspot": "https://pipedream.com/s.v0/app_OkrhlP/logo/96",
  "jira": "https://pipedream.com/s.v0/app_mArhw1/logo/96",
  "linear": "https://pipedream.com/s.v0/app_X7Lh0L/logo/96",
  "microsoft_onedrive": "https://pipedream.com/s.v0/app_mjEhWP/logo/96",
  "microsoft_outlook": "https://pipedream.com/s.v0/app_XbPhEP/logo/96",
  "microsoft_teams": "https://pipedream.com/s.v0/app_1M0hlk/logo/96",
  "notion": "https://pipedream.com/s.v0/app_X7Lhxr/logo/96",
  "posthog": "https://pipedream.com/s.v0/app_mo7h7A/logo/96",
  "slack": "https://pipedream.com/s.v0/app_M0hv7G/logo/96",
  "stripe": "https://pipedream.com/s.v0/app_OD5hrX/logo/96",
  "todoist": "https://pipedream.com/s.v0/app_mWnhpj/logo/96",
  "zoom": "https://pipedream.com/s.v0/app_m5ghAd/logo/96",
};
