// Existing CI source classification, extracted from the workflow for focused contracts.
import {spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
export const sourceChangeScript=[
  "set -euo pipefail",
  "",
  "# Main runs are admitted through the queue. Plan from the last",
  "# successful coverage-aware ancestor so failed or cancelled work is",
  "# automatically absorbed by the next run.",
  "if [ \"$GITHUB_EVENT_NAME\" = \"push\" ] && [ \"$GITHUB_REF\" = \"refs/heads/main\" ]; then",
  "  echo \"trigger_requested=true\" >> \"$GITHUB_OUTPUT\"",
  "  node scripts/ci/main-ci-coverage.mjs >> \"$GITHUB_OUTPUT\"",
  "  echo \"os_view_parity_tests=true\" >> \"$GITHUB_OUTPUT\"",
  "  exit 0",
  "fi",
  "",
  "# Manual and merge-queue runs must execute CI regardless of changed paths.",
  "if [ \"$GITHUB_EVENT_NAME\" = \"workflow_dispatch\" ] || [ \"$GITHUB_EVENT_NAME\" = \"merge_group\" ]; then",
  "  echo \"trigger_requested=true\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"should_run=true\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"docs_contract_tests=false\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"os_view_parity_tests=true\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"CI relevant changes: true ($GITHUB_EVENT_NAME always runs)\"",
  "  exit 0",
  "fi",
  "",
  "should_run_trigger=true",
  "if [ \"$GITHUB_EVENT_NAME\" = \"pull_request\" ]; then",
  "  should_run_trigger=false",
  "  if [ \"$PR_ACTION\" = \"ready_for_review\" ] || { [ \"$PR_ACTION\" = \"labeled\" ] && { [ \"$PR_LABEL_NAME\" = \"ready-for-ci\" ] || [ \"$PR_HAS_READY_FOR_CI\" = \"true\" ]; }; } || { [ \"$PR_ACTION\" = \"synchronize\" ] && [ \"$PR_HAS_READY_FOR_CI\" = \"true\" ]; } || { { [ \"$PR_ACTION\" = \"reopened\" ] || [ \"${PR_BASE_EDIT:-false}\" = \"true\" ]; } && [ \"$PR_HAS_READY_FOR_CI\" = \"true\" ]; }; then",
  "    should_run_trigger=true",
  "  fi",
  "fi",
  "",
  "if [ \"$should_run_trigger\" != \"true\" ]; then",
  "  echo \"trigger_requested=false\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"should_run=false\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"docs_contract_tests=false\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"os_view_parity_tests=false\" >> \"$GITHUB_OUTPUT\"",
  "  echo \"CI trigger not requested; add the ready-for-ci label, mark the PR ready for review, or run manually. Later commits rerun automatically while ready-for-ci remains applied.\"",
  "  exit 0",
  "fi",
  "",
  "echo \"trigger_requested=true\" >> \"$GITHUB_OUTPUT\"",
  "git fetch --no-tags --depth=1 origin \"$GITHUB_BASE_REF\"",
  "changed_files=\"$(git diff --name-only \"origin/$GITHUB_BASE_REF\" \"$GITHUB_SHA\")\"",
  "os_view_parity_tests=\"$(printf '%s\\n' \"$changed_files\" | node scripts/ci/os-view-parity-plan.mjs)\"",
  "",
  "should_run=false",
  "docs_contract_tests=false",
  "while IFS= read -r file; do",
  "  [ -z \"$file\" ] && continue",
  "  case \"$file\" in",
  "    docs/*|specs/*|*.md) docs_contract_tests=true ;;",
  "    *) should_run=true ;;",
  "  esac",
  "done <<EOF",
  "$changed_files",
  "EOF",
  "",
  "echo \"should_run=$should_run\" >> \"$GITHUB_OUTPUT\"",
  "echo \"docs_contract_tests=$docs_contract_tests\" >> \"$GITHUB_OUTPUT\"",
  "echo \"os_view_parity_tests=$os_view_parity_tests\" >> \"$GITHUB_OUTPUT\"",
  "echo \"CI relevant changes: $should_run\"",
  "echo \"Docs contract tests: $docs_contract_tests\"",
  "echo \"OS-view parity tests: $os_view_parity_tests\"",
  "",
].join('\n');
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){
 const result=spawnSync('bash',['-c',sourceChangeScript],{stdio:'inherit',env:process.env,timeout:180000});
 if(result.error)throw result.error;process.exit(result.status??1);
}
