import { LOCAL_CHAT_IMPORT_BATCH_LIMIT, LOCAL_CHAT_DISCOVERY_LIMIT } from "@matrix-os/contracts/local-chat-import";
import { z } from "zod/v4";
export const ChatImportSessionSchema = z.strictObject({ runtimeSlot: z.string().min(1).max(128), authGeneration: z.number().int().nonnegative() });
const Harness = z.enum(["codex", "claude"]);
const count = z.number().int().nonnegative().max(500000);
export const ChatImportPreviewSchema = z.strictObject({ harness: Harness, sourceId: z.uuid(), sourceAgentId: z.string().max(512).optional(), sourceHash: z.string().regex(/^[a-f0-9]{64}$/), rawBytes: z.number().int().min(1).max(20 * 1024 ** 3), title: z.string().max(160), firstVisibleText: z.string().max(500), recordedDirectory: z.string().max(4096).optional(), repositoryUrl: z.string().max(4096).optional(), parserVersion: z.literal(1), counts: z.strictObject({ humanInputs: count, assistantResponses: count, agentInputs: count, toolCalls: count, toolResults: count, attachments: count, externalReferences: count, thinkingRecords: count, contextRecords: count, unknownRecords: count, sourceIssues: count }) });
const Selection = z.strictObject({ selectionId: z.uuid(), preview: ChatImportPreviewSchema });
const Cancelled = z.strictObject({ status: z.literal("cancelled") });
const ErrorResult = z.strictObject({ status: z.literal("error"), message: z.string().max(256) });
export const LOCAL_CHAT_IMPORT_INVOKE = {
    "runtime:chat-import-discover": { request: ChatImportSessionSchema, response: z.discriminatedUnion("status", [Cancelled, ErrorResult, z.strictObject({ status: z.literal("discovered"), sources: z.array(z.strictObject({ sourceKey: z.uuid(), harness: Harness, title: z.string().max(160), rawBytes: z.number().int().min(1).max(20 * 1024 ** 3), updatedAt: z.iso.datetime(), recordedDirectory: z.string().max(4096).optional() })).max(LOCAL_CHAT_DISCOVERY_LIMIT), limited: z.boolean() })]) },
    "runtime:chat-import-reserve": { request: ChatImportSessionSchema.extend({ sourceKeys: z.array(z.uuid()).min(1).max(LOCAL_CHAT_DISCOVERY_LIMIT).refine(keys => new Set(keys).size === keys.length) }), response: z.strictObject({ok:z.boolean()}) },
    "runtime:chat-import-prepare": { request: ChatImportSessionSchema.extend({ sourceKeys: z.array(z.uuid()).min(1).max(LOCAL_CHAT_IMPORT_BATCH_LIMIT).refine(keys => new Set(keys).size === keys.length) }), response: z.discriminatedUnion("status", [Cancelled, ErrorResult, z.strictObject({ status: z.literal("selected-many"), selections: z.array(Selection).max(LOCAL_CHAT_IMPORT_BATCH_LIMIT), errors: z.array(z.string().max(256)).max(LOCAL_CHAT_IMPORT_BATCH_LIMIT) })]) },
    "runtime:chat-import-select": { request: ChatImportSessionSchema.extend({ harness: Harness, multiple: z.boolean().optional() }), response: z.discriminatedUnion("status", [Cancelled, ErrorResult, Selection.extend({ status: z.literal("selected") }), z.strictObject({ status: z.literal("selected-many"), selections: z.array(Selection).max(LOCAL_CHAT_IMPORT_BATCH_LIMIT), errors: z.array(z.string().max(256)).max(LOCAL_CHAT_IMPORT_BATCH_LIMIT) })]) },
    "runtime:chat-import-apply": { request: ChatImportSessionSchema.extend({ selectionId: z.uuid(), title: z.string().trim().min(1).max(160).regex(/^[^\u0000-\u001f\u007f]+$/) }), response: z.discriminatedUnion("status", [Cancelled, ErrorResult, z.strictObject({ status: z.literal("imported"), jobId: z.uuid(), chatId: z.string().regex(/^chat_[A-Za-z0-9_-]{1,128}$/), messageCount: z.number().int().min(1).max(100000) })]) },
    "runtime:chat-import-release": { request: ChatImportSessionSchema.extend({selectionIds:z.array(z.uuid()).min(1).max(LOCAL_CHAT_IMPORT_BATCH_LIMIT)}), response:z.strictObject({ok:z.boolean()}) },
    "runtime:chat-import-pause": { request: ChatImportSessionSchema.extend({ discardSelections: z.boolean().optional() }), response: z.strictObject({ ok: z.boolean() }) },
} as const;
export const LOCAL_CHAT_IMPORT_EVENTS = { "runtime:chat-import-progress": ChatImportSessionSchema.extend({ selectionId: z.uuid(), phase: z.enum(["uploading", "verifying"]), uploadedBytes: z.number().int().nonnegative().max(20 * 1024 ** 3), totalBytes: z.number().int().min(1).max(20 * 1024 ** 3), jobId: z.uuid() }) } as const;
