// @vitest-environment jsdom
import React from 'react';
import type { ChatAgent, ChatAgentListResponse } from '@matrix-os/contracts';
import type { ChatAgentClient } from '../../../packages/ui/src/chat-agents/client.js';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { BotChatPanel } from '../../../packages/ui/src/chat-agents/bots/BotChatPanel.js';
import { clientFixture, saved } from '../../desktop/chat-agents-fixture.js';
import { createCanonicalProviderCatalogFixture } from '../../contracts/fixtures/canonical-chat.js';
afterEach(cleanup);
it('opens persistent bot details and edits only a supported managed model at its revision',async()=>{
 const catalog=createCanonicalProviderCatalogFixture(); const base=catalog.instances[0]!;
 catalog.instances.push({...base,id:'matrix_pi_default',driverKind:'matrix_pi',displayName:'Pi',connectionLabel:'Matrix AI',supports:{...base.supports,interactionModes:['default'],permissionModes:['full_access']},defaultSelection:{instanceId:'matrix_pi_default',model:base.models[0]!.id}});
 const bot={...saved,recipeRef:{recipeId:'writer',version:'1'},selection:{instanceId:'matrix_bot_default',model:'automatic'}};
 const c=clientFixture(); c.list.mockResolvedValue({enabled:true,agents:[bot]}); c.update.mockImplementation(async(_,input)=>({...bot,...input,revision:bot.revision+1}));
 c.bots={directBot:vi.fn(async()=>bot.id),interactions:vi.fn(async()=>[]),tasks:vi.fn(async()=>[]),authority:vi.fn(async()=>({grants:[],connections:[],memory:{items:[]},routines:[],pendingInteractions:[]}))} as never;
 render(<BotChatPanel chatId='chat_bot' client={c} catalog={catalog}/>);
 await screen.findByText(bot.name);
 fireEvent.click(screen.getByRole('button',{name:'Details'}));
 expect(screen.getByText(bot.instructions)).toBeTruthy();
 const picker=screen.getByRole('combobox',{name:'Bot model'});
 expect(screen.queryByRole('option',{name:/Codex/})).toBeNull();
 fireEvent.change(picker,{target:{value:JSON.stringify(['matrix_pi_default',base.models[0]!.id])}});
 await waitFor(()=>expect(c.update).toHaveBeenCalledWith(bot.id,{selection:{instanceId:'matrix_pi_default',model:base.models[0]!.id},baseRevision:bot.revision}));
});
it('ignores an edit response after leaving that Bot',async()=>{
 const {BotEditDialog}=await import('../../../packages/ui/src/chat-agents/bots/BotEditDialog.js');
 HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
 HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
 let finish!:(value:ChatAgent)=>void;
 const c=clientFixture();vi.mocked(c as ChatAgentClient).update.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));
 const onSaved=vi.fn(),onClose=vi.fn();
 const bot={...saved,recipeRef:{recipeId:'writer',version:'1'}};
 const view=render(<BotEditDialog agent={bot} client={c} onSaved={onSaved} onClose={onClose}/>);
 fireEvent.click(screen.getByRole('button',{name:'Save changes'}));
 await waitFor(()=>expect(c.update).toHaveBeenCalledOnce());
 view.unmount();finish({...bot,name:'Old response'});await Promise.resolve();await Promise.resolve();
 expect(onSaved).not.toHaveBeenCalled();expect(onClose).not.toHaveBeenCalled();
});
it('disables retained catalog choices during refresh and keeps a saved revision over an older list response',async()=>{
 const catalog=createCanonicalProviderCatalogFixture();const base=catalog.instances[0]!;
 catalog.instances.push({...base,id:'matrix_pi_default',driverKind:'matrix_pi',displayName:'Pi',connectionLabel:'Matrix AI',supports:{...base.supports,interactionModes:['default'],permissionModes:['full_access']},defaultSelection:{instanceId:'matrix_pi_default',model:base.models[0]!.id}});
 const bot={...saved,recipeRef:{recipeId:'writer',version:'1'},selection:{instanceId:'matrix_bot_default',model:'automatic'}};
 const c=clientFixture();c.list.mockResolvedValue({enabled:true,agents:[bot]});
 c.update.mockImplementation(async(_,input)=>({...bot,...input,revision:bot.revision+1}));
 c.bots={directBot:vi.fn(async()=>bot.id),interactions:vi.fn(async()=>[]),tasks:vi.fn(async()=>[]),authority:vi.fn(async()=>({grants:[],connections:[],memory:{items:[]},routines:[],pendingInteractions:[]}))} as never;
 const view=render(<BotChatPanel chatId='chat_bot' client={c} catalog={catalog} refreshKey={0}/>);
 await screen.findByText(bot.name);fireEvent.click(screen.getByRole('button',{name:'Details'}));
 view.rerender(<BotChatPanel chatId='chat_bot' client={c} catalog={catalog} catalogLoading refreshKey={0}/>);
 expect((screen.getByRole('combobox',{name:'Bot model'}) as HTMLSelectElement).disabled).toBe(true);
 fireEvent.change(screen.getByRole('combobox',{name:'Bot model'}),{target:{value:JSON.stringify(['matrix_pi_default',base.models[0]!.id])}});
 expect(c.update).not.toHaveBeenCalled();
 let finish!:(value:ChatAgentListResponse)=>void;vi.mocked(c as ChatAgentClient).list.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));
 view.rerender(<BotChatPanel chatId='chat_bot' client={c} catalog={catalog} refreshKey={1}/>);
 await waitFor(()=>expect(finish).toBeTypeOf('function'));
 fireEvent.change(screen.getByRole('combobox',{name:'Bot model'}),{target:{value:JSON.stringify(['matrix_pi_default',base.models[0]!.id])}});
 await waitFor(()=>expect(c.update).toHaveBeenCalledOnce());
 await waitFor(()=>expect((screen.getByRole('combobox',{name:'Bot model'}) as HTMLSelectElement).value).toBe(JSON.stringify(['matrix_pi_default',base.models[0]!.id])));
 finish({enabled:true,agents:[bot]});await Promise.resolve();await Promise.resolve();
 expect((screen.getByRole('combobox',{name:'Bot model'}) as HTMLSelectElement).value).toBe(JSON.stringify(['matrix_pi_default',base.models[0]!.id]));
});
