// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@react-navigation/elements",
              message: "Use Expo Router and React Native safe-area primitives in the mobile app.",
            },
          ],
        },
      ],
    },
  },
  {
    // Generated by scripts/bundle-xterm.mjs — a ~500KB inlined vendor dist.
    ignores: ["dist/*", "components/terminal/xterm-bundle.ts"],
  }
]);
