import React, {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useMemo,
  useRef,
} from "react";
import { StyleSheet } from "react-native-unistyles";
import { WebView, type WebViewMessageEvent } from "react-native-webview";
import { AnalyticsMask } from "@/lib/analytics";
import { colors } from "@/lib/theme";
import { FIT_ADDON_JS, XTERM_CSS, XTERM_JS } from "@/components/terminal/xterm-bundle";

/**
 * Imperative handle for pushing server output into the embedded xterm.js
 * emulator. The WebView owns the screen grid, so RN never has to model ANSI.
 */
export interface TerminalSurfaceHandle {
  write: (data: string) => void;
  clear: () => void;
  reset: () => void;
  /** Lay the emulator out on the computer's grid; it is scaled or panned to fit the screen. */
  resize: (cols: number, rows: number) => void;
  focus: () => void;
  blur: () => void;
  scrollLines: (lines: number) => void;
  scrollToBottom: () => void;
  /** Ask the emulator to report the cursor position (see onCursor). */
  reportCursor: () => void;
}

interface TerminalSurfaceProps {
  fontScale: number;
  /** Raw keystrokes typed directly into the emulator (hardware keyboard / tap). */
  onInput: (data: string) => void;
  /** Byte-valued xterm protocol replies such as OSC and binary mouse reports. */
  onBinary: (data: string) => void;
  /**
   * Reports the grid that fits the surface at the configured font size, when
   * it lays out or resizes. Once the computer's grid has been applied the
   * emulator keeps that grid; this is only what the screen could show.
   */
  onResize: (cols: number, rows: number) => void;
  /** Cursor bottom edge in surface-local pixels; throttled by the emulator. */
  onCursor?: (bottomPx: number) => void;
}

const T = colors.terminal;
// A grid wider than the screen is scaled down until its text would be smaller
// than this, then panned. Matches the readable floor of the web terminal.
const MINIMUM_READABLE_FONT_PX = 10;
// xterm draws its scrollbar over the right edge of the emulator. The fit addon
// reserves this much beside the last column for it, so the grid keeps the same.
const SCROLLBAR_GUTTER_PX = 14;
// Output that arrives before the emulator has booted is held, up to this much.
const MAX_PENDING_WRITE_CHARS = 2 * 1024 * 1024;

// xterm.js + fit addon are inlined from the committed bundle (see
// components/terminal/xterm-bundle.ts, regenerated by scripts/bundle-xterm.mjs)
// so the terminal renders even offline or with a CDN blocked. Neutralize any
// literal tag-closer so the inlined dist cannot break out of its <script>/<style>.
function inlineScript(js: string): string {
  return js.replace(/<\/(script)/gi, "<\\/$1");
}
function inlineStyle(css: string): string {
  return css.replace(/<\/(style)/gi, "<\\/$1");
}

function buildHtml(fontScale: number): string {
  const fontSize = Math.round(13 * fontScale);
  // Dark botanical console — a proper terminal surface that reads as "code"
  // against the light shell chrome around it.
  const theme = {
    background: T.bg,
    foreground: T.fg,
    cursor: T.cursor,
    cursorAccent: T.bg,
    selectionBackground: T.selection,
    black: T.black,
    red: T.red,
    green: T.green,
    yellow: T.yellow,
    blue: T.blue,
    magenta: T.magenta,
    cyan: T.cyan,
    white: T.white,
    brightBlack: T.brightBlack,
    brightRed: T.brightRed,
    brightGreen: T.brightGreen,
    brightYellow: T.brightYellow,
    brightBlue: T.brightBlue,
    brightMagenta: T.brightMagenta,
    brightCyan: T.brightCyan,
    brightWhite: T.brightWhite,
  };
  return `<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<style>${inlineStyle(XTERM_CSS)}</style>
<style>
  html, body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: ${theme.background};
    overflow: hidden;
    overscroll-behavior: none;
    -webkit-user-select: none;
    user-select: none;
  }
  #term { height: 100%; width: 100%; padding: 8px 10px; box-sizing: border-box; position: relative; }
  .xterm .xterm-viewport {
    background: ${theme.background} !important;
    overflow-y: scroll !important;
    -webkit-overflow-scrolling: touch;
    overscroll-behavior: contain;
    /* The touch→wheel bridge below owns pan gestures so alternate-screen TUIs
       (zellij scrollback, coding agents) receive scroll too. */
    touch-action: none;
  }
  .xterm-viewport::-webkit-scrollbar { width: 0; height: 0; }
</style>
</head>
<body>
<div id="term"></div>
<script>${inlineScript(XTERM_JS)}</script>
<script>${inlineScript(FIT_ADDON_JS)}</script>
<script>
  (function () {
    function post(msg) {
      if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage(JSON.stringify(msg));
    }
    function boot() {
      if (!window.Terminal || !window.FitAddon) { setTimeout(boot, 30); return; }
      var term = new window.Terminal({
        fontFamily: "Menlo, Monaco, 'Courier New', monospace",
        fontSize: ${fontSize},
        lineHeight: 1.15,
        cursorBlink: true,
        scrollback: 12000,
        convertEol: false,
        theme: ${JSON.stringify(theme)},
      });
      var fit = new window.FitAddon.FitAddon();
      term.loadAddon(fit);
      term.open(document.getElementById("term"));
      window.__term = term;

      // The computer owns the grid: every renderer of a tab shows the same
      // cols x rows. Until it has been applied the emulator fills the screen;
      // afterwards it is never resized locally, only scaled and panned to fit.
      var host = document.getElementById("term");
      var gridApplied = false;
      var scale = 1;
      var pan = { x: 0, y: 0 };
      var maxPan = { x: 0, y: 0 };

      function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
      // The space the grid may cover. The fit addon measures the host including
      // its padding, so a grid it proposed can reach into the right and bottom
      // padding; counting that here keeps such a grid at full size.
      function viewportBox() {
        var style = window.getComputedStyle(host);
        return {
          w: host.clientWidth - (parseFloat(style.paddingLeft) || 0),
          h: host.clientHeight - (parseFloat(style.paddingTop) || 0),
        };
      }
      function gridBox() {
        var screen = term.element && term.element.querySelector(".xterm-screen");
        return screen ? { w: screen.offsetWidth, h: screen.offsetHeight } : { w: 0, h: 0 };
      }
      function applyTransform() {
        var el = term.element;
        if (!el) return;
        el.style.transformOrigin = "0 0";
        el.style.transform = "translate(" + (-pan.x) + "px," + (-pan.y) + "px) scale(" + scale + ")";
      }
      function followCursor(grid, box) {
        if (!term.rows || !grid.h) return;
        var rowHeight = (grid.h / term.rows) * scale;
        var top = term.buffer.active.cursorY * rowHeight;
        if (top + rowHeight - pan.y > box.h) pan.y = top + rowHeight - box.h;
        else if (top < pan.y) pan.y = top;
        pan.y = clamp(pan.y, 0, maxPan.y);
      }
      function layoutGrid() {
        var el = term.element;
        if (!el || !gridApplied) return;
        var grid = gridBox();
        var box = viewportBox();
        if (!(grid.w > 0) || !(grid.h > 0) || !(box.w > 0) || !(box.h > 0)) return;
        // Nothing inside the emulator may clip columns the transform still has
        // to show, and its scrollbar stays beside the last column, not over it.
        el.style.width = (grid.w + ${SCROLLBAR_GUTTER_PX}) + "px";
        el.style.height = grid.h + "px";
        var fontSize = Number(term.options.fontSize) || ${fontSize};
        scale = Math.max(Math.min(1, box.w / grid.w), Math.min(1, ${MINIMUM_READABLE_FONT_PX} / fontSize));
        maxPan = { x: Math.max(0, grid.w * scale - box.w), y: Math.max(0, grid.h * scale - box.h) };
        pan.x = clamp(pan.x, 0, maxPan.x);
        followCursor(grid, box);
        applyTransform();
      }
      function proposeViewport() {
        try {
          var proposed = fit.proposeDimensions();
          if (proposed && isFinite(proposed.cols) && isFinite(proposed.rows) && proposed.cols > 0 && proposed.rows > 0) {
            return { cols: Math.floor(proposed.cols), rows: Math.floor(proposed.rows) };
          }
        } catch (e) {}
        return null;
      }
      function reportViewport() {
        var proposed = proposeViewport();
        if (!proposed) return;
        if (!gridApplied) {
          try { term.resize(proposed.cols, proposed.rows); } catch (e) {}
        }
        post({ type: "resize", cols: proposed.cols, rows: proposed.rows });
        layoutGrid();
      }
      // The keyboard animates the surface through many sizes; only the settled one is reported.
      var viewportTimer = null;
      function scheduleViewportReport() {
        layoutGrid();
        if (viewportTimer) clearTimeout(viewportTimer);
        viewportTimer = setTimeout(function () { viewportTimer = null; reportViewport(); }, 120);
      }

      window.__matrixTerminal = {
        applyGrid: function (cols, rows) {
          gridApplied = true;
          try {
            if (term.cols !== cols || term.rows !== rows) term.resize(cols, rows);
          } catch (e) {}
          layoutGrid();
          requestAnimationFrame(layoutGrid);
        },
        focus: function () { term.focus(); },
        blur: function () {
          try { term.blur(); } catch (e) {}
          try {
            var textarea = document.querySelector(".xterm-helper-textarea");
            if (textarea && textarea.blur) textarea.blur();
            var active = document.activeElement;
            if (active && active.blur) active.blur();
            document.body.setAttribute("tabindex", "-1");
            document.body.focus({ preventScroll: true });
          } catch (e) {}
        },
        scrollLines: function (lines) {
          try { term.scrollLines(lines); } catch (e) {}
        },
        scrollToBottom: function () {
          try { term.scrollToBottom(); } catch (e) {}
        },
        reportCursor: function () { reportCursor(); }
      };

      reportViewport();
      window.addEventListener("resize", scheduleViewportReport);
      term.onData(function (data) { post({ type: "input", data: data }); });
      term.onBinary(function (data) { post({ type: "binary", data: data }); });

      // Cursor bottom edge in page pixels so the RN side can lift the view
      // only as much as needed to keep typing visible above the keyboard.
      function reportCursor() {
        try {
          var screen = term.element && term.element.querySelector(".xterm-screen");
          if (!screen || !term.rows) return;
          var rect = screen.getBoundingClientRect();
          var cell = rect.height / term.rows;
          var bottom = rect.top + (term.buffer.active.cursorY + 1) * cell;
          post({ type: "cursor", bottom: Math.round(bottom) });
        } catch (e) {}
      }
      var cursorTimer = null;
      term.onCursorMove(function () {
        if (cursorTimer) return;
        cursorTimer = setTimeout(function () {
          cursorTimer = null;
          // A grid taller than the screen keeps the line being typed in view.
          if (maxPan.y > 0) layoutGrid();
          reportCursor();
        }, 160);
      });

      // Touch → wheel bridge: xterm scrolls its own viewport in the normal
      // buffer and forwards wheel as mouse-scroll reports in the alternate
      // buffer (zellij scrollback, coding-agent TUIs), so synthesizing wheel
      // events gives touch scrolling in both modes. A sideways drag instead
      // pans a grid that is still wider than the screen at its smallest scale.
      var touchX = null;
      var touchY = null;
      var touchAxis = null;
      var termEl = host;
      function endTouch() { touchX = null; touchY = null; touchAxis = null; }
      termEl.addEventListener("touchstart", function (e) {
        if (e.touches.length !== 1) { endTouch(); return; }
        touchX = e.touches[0].clientX;
        touchY = e.touches[0].clientY;
        touchAxis = null;
      }, { passive: true });
      termEl.addEventListener("touchmove", function (e) {
        if (touchY === null || touchX === null || e.touches.length !== 1) return;
        var x = e.touches[0].clientX;
        var y = e.touches[0].clientY;
        var deltaX = touchX - x;
        var delta = touchY - y;
        if (touchAxis === null) {
          if (Math.abs(deltaX) < 4 && Math.abs(delta) < 4) return;
          touchAxis = maxPan.x > 0 && Math.abs(deltaX) > Math.abs(delta) ? "x" : "y";
        }
        if (touchAxis === "x") {
          touchX = x;
          touchY = y;
          pan.x = clamp(pan.x + deltaX, 0, maxPan.x);
          applyTransform();
          e.preventDefault();
          return;
        }
        if (Math.abs(delta) < 1) return;
        touchX = x;
        touchY = y;
        var target = term.element && (term.element.querySelector(".xterm-screen") || term.element);
        if (!target) return;
        try {
          target.dispatchEvent(new WheelEvent("wheel", { deltaY: delta, deltaMode: 0, bubbles: true, cancelable: true }));
        } catch (err) {}
        e.preventDefault();
      }, { passive: false });
      termEl.addEventListener("touchend", endTouch, { passive: true });
      termEl.addEventListener("touchcancel", endTouch, { passive: true });

      post({ type: "ready", cols: term.cols, rows: term.rows });
    }
    boot();
  })();
</script>
</body>
</html>`;
}

export const TerminalSurface = forwardRef<TerminalSurfaceHandle, TerminalSurfaceProps>(
  function TerminalSurface({ fontScale, onInput, onBinary, onResize, onCursor }, ref) {
    const webRef = useRef<WebView | null>(null);
    const readyRef = useRef(false);
    // What the emulator has to run once it has booted, in order: a grid applied
    // before the output that was laid out for it. `chars` is 0 for anything
    // that is not output.
    const pendingRef = useRef<{ js: string; chars: number }[]>([]);
    const pendingCharsRef = useRef(0);
    // Rebuild the document only when the font size bucket changes (keeps the
    // emulator stable while typing).
    const html = useMemo(() => buildHtml(fontScale), [fontScale]);

    const inject = useCallback((js: string) => {
      webRef.current?.injectJavaScript(`${js};true;`);
    }, []);

    const scrollLines = useCallback((lines: number) => {
      if (!Number.isFinite(lines) || lines === 0) return;
      inject(`window.__matrixTerminal && window.__matrixTerminal.scrollLines(${Math.trunc(lines)})`);
    }, [inject]);

    const run = useCallback((js: string, chars = 0) => {
      if (readyRef.current) {
        inject(js);
        return;
      }
      pendingRef.current.push({ js, chars });
      pendingCharsRef.current += chars;
      while (pendingCharsRef.current > MAX_PENDING_WRITE_CHARS) {
        const oldest = pendingRef.current.findIndex((entry) => entry.chars > 0);
        if (oldest === -1) break;
        pendingCharsRef.current -= pendingRef.current[oldest]!.chars;
        pendingRef.current.splice(oldest, 1);
      }
    }, [inject]);

    const flush = useCallback(() => {
      if (!readyRef.current || pendingRef.current.length === 0) return;
      const script = pendingRef.current.map((entry) => entry.js).join(";");
      pendingRef.current = [];
      pendingCharsRef.current = 0;
      inject(script);
    }, [inject]);

    // Output held for an emulator that has not booted is superseded by a clear.
    const discardPendingWrites = useCallback(() => {
      pendingRef.current = pendingRef.current.filter((entry) => entry.chars === 0);
      pendingCharsRef.current = 0;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        write: (data: string) => {
          if (!data) return;
          run(`window.__term && window.__term.write(${JSON.stringify(data)})`, data.length);
        },
        clear: () => {
          discardPendingWrites();
          if (readyRef.current) inject("window.__term && window.__term.clear()");
        },
        reset: () => {
          discardPendingWrites();
          if (readyRef.current) inject("window.__term && window.__term.reset()");
        },
        resize: (cols: number, rows: number) => {
          if (!Number.isInteger(cols) || !Number.isInteger(rows)) return;
          if (cols < 1 || cols > 500 || rows < 1 || rows > 200) return;
          run(`window.__matrixTerminal && window.__matrixTerminal.applyGrid(${cols},${rows})`);
        },
        focus: () => inject("window.__matrixTerminal && window.__matrixTerminal.focus()"),
        blur: () => inject("window.__matrixTerminal && window.__matrixTerminal.blur()"),
        scrollLines,
        scrollToBottom: () => inject("window.__matrixTerminal && window.__matrixTerminal.scrollToBottom()"),
        reportCursor: () => inject("window.__matrixTerminal && window.__matrixTerminal.reportCursor()"),
      }),
      [discardPendingWrites, inject, run, scrollLines],
    );

    const handleMessage = useCallback(
      (event: WebViewMessageEvent) => {
        let msg: { type?: string; data?: string; cols?: number; rows?: number; bottom?: number };
        try {
          msg = JSON.parse(event.nativeEvent.data) as typeof msg;
        } catch {
          return;
        }
        if (msg.type === "ready") {
          readyRef.current = true;
          if (typeof msg.cols === "number" && typeof msg.rows === "number") {
            onResize(msg.cols, msg.rows);
          }
          flush();
          return;
        }
        if (msg.type === "input" && typeof msg.data === "string") {
          onInput(msg.data);
          return;
        }
        if (msg.type === "binary" && typeof msg.data === "string") {
          onBinary(msg.data);
          return;
        }
        if (msg.type === "resize" && typeof msg.cols === "number" && typeof msg.rows === "number") {
          onResize(msg.cols, msg.rows);
          return;
        }
        if (msg.type === "cursor" && typeof msg.bottom === "number" && Number.isFinite(msg.bottom)) {
          onCursor?.(msg.bottom);
        }
      },
      [flush, onInput, onBinary, onResize, onCursor],
    );

    return (
      // Terminal output is never recorded in session replay.
      <AnalyticsMask style={styles.container}>
        <WebView
          key="terminal-webview-accessory-enabled"
          ref={webRef}
          originWhitelist={["*"]}
          source={{ html }}
          onMessage={handleMessage}
          // Terminal owns scrolling; the RN side should not bounce.
          scrollEnabled
          overScrollMode="never"
          bounces={false}
          hideKeyboardAccessoryView={false}
          keyboardDisplayRequiresUserAction={false}
          androidLayerType="hardware"
          setBuiltInZoomControls={false}
          style={styles.web}
          containerStyle={styles.web}
        />
      </AnalyticsMask>
    );
  },
);

const styles = StyleSheet.create((theme) => ({
  container: { flex: 1, backgroundColor: theme.terminal.bg, overflow: "hidden" },
  web: { flex: 1, backgroundColor: theme.terminal.bg },
}));
