import React, {
  forwardRef,
  useCallback,
  useImperativeHandle,
  useMemo,
  useRef,
} from "react";
import { StyleSheet } from "react-native-unistyles";
import { WebView, type WebViewMessageEvent } from "react-native-webview";
import { AnalyticsMask } from "@/lib/analytics";
import { colors } from "@/lib/theme";
import { FIT_ADDON_JS, XTERM_CSS, XTERM_JS } from "@/components/terminal/xterm-bundle";

/**
 * Imperative handle for pushing server output into the embedded xterm.js
 * emulator. The WebView owns the screen grid, so RN never has to model ANSI.
 */
export interface TerminalSurfaceHandle {
  write: (data: string) => void;
  clear: () => void;
  focus: () => void;
  blur: () => void;
  scrollLines: (lines: number) => void;
  scrollToBottom: () => void;
  /** Ask the emulator to report the cursor position (see onCursor). */
  reportCursor: () => void;
}

interface TerminalSurfaceProps {
  fontScale: number;
  /** Raw keystrokes typed directly into the emulator (hardware keyboard / tap). */
  onInput: (data: string) => void;
  /** Reports the fitted grid size whenever the surface lays out or resizes. */
  onResize: (cols: number, rows: number) => void;
  /** Cursor bottom edge in surface-local pixels; throttled by the emulator. */
  onCursor?: (bottomPx: number) => void;
}

const T = colors.terminal;

// xterm.js + fit addon are inlined from the committed bundle (see
// components/terminal/xterm-bundle.ts, regenerated by scripts/bundle-xterm.mjs)
// so the terminal renders even offline or with a CDN blocked. Neutralize any
// literal tag-closer so the inlined dist cannot break out of its <script>/<style>.
function inlineScript(js: string): string {
  return js.replace(/<\/(script)/gi, "<\\/$1");
}
function inlineStyle(css: string): string {
  return css.replace(/<\/(style)/gi, "<\\/$1");
}

function buildHtml(fontScale: number): string {
  const fontSize = Math.round(13 * fontScale);
  // Dark botanical console — a proper terminal surface that reads as "code"
  // against the light shell chrome around it.
  const theme = {
    background: T.bg,
    foreground: T.fg,
    cursor: T.cursor,
    cursorAccent: T.bg,
    selectionBackground: T.selection,
    black: T.black,
    red: T.red,
    green: T.green,
    yellow: T.yellow,
    blue: T.blue,
    magenta: T.magenta,
    cyan: T.cyan,
    white: T.white,
    brightBlack: T.brightBlack,
    brightRed: T.brightRed,
    brightGreen: T.brightGreen,
    brightYellow: T.brightYellow,
    brightBlue: T.brightBlue,
    brightMagenta: T.brightMagenta,
    brightCyan: T.brightCyan,
    brightWhite: T.brightWhite,
  };
  return `<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<style>${inlineStyle(XTERM_CSS)}</style>
<style>
  html, body {
    margin: 0;
    padding: 0;
    height: 100%;
    background: ${theme.background};
    overflow: hidden;
    overscroll-behavior: none;
    -webkit-user-select: none;
    user-select: none;
  }
  #term { height: 100%; width: 100%; padding: 8px 10px; box-sizing: border-box; position: relative; }
  .xterm .xterm-viewport {
    background: ${theme.background} !important;
    overflow-y: scroll !important;
    -webkit-overflow-scrolling: touch;
    overscroll-behavior: contain;
    /* The touch→wheel bridge below owns pan gestures so alternate-screen TUIs
       (zellij scrollback, coding agents) receive scroll too. */
    touch-action: none;
  }
  .xterm-viewport::-webkit-scrollbar { width: 0; height: 0; }
</style>
</head>
<body>
<div id="term"></div>
<script>${inlineScript(XTERM_JS)}</script>
<script>${inlineScript(FIT_ADDON_JS)}</script>
<script>
  (function () {
    function post(msg) {
      if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage(JSON.stringify(msg));
    }
    function boot() {
      if (!window.Terminal || !window.FitAddon) { setTimeout(boot, 30); return; }
      var term = new window.Terminal({
        fontFamily: "Menlo, Monaco, 'Courier New', monospace",
        fontSize: ${fontSize},
        lineHeight: 1.15,
        cursorBlink: true,
        scrollback: 12000,
        convertEol: false,
        theme: ${JSON.stringify(theme)},
      });
      var fit = new window.FitAddon.FitAddon();
      term.loadAddon(fit);
      term.open(document.getElementById("term"));
      window.__term = term;
      window.__matrixTerminal = {
        focus: function () { term.focus(); },
        blur: function () {
          try { term.blur(); } catch (e) {}
          try {
            var textarea = document.querySelector(".xterm-helper-textarea");
            if (textarea && textarea.blur) textarea.blur();
            var active = document.activeElement;
            if (active && active.blur) active.blur();
            document.body.setAttribute("tabindex", "-1");
            document.body.focus({ preventScroll: true });
          } catch (e) {}
        },
        scrollLines: function (lines) {
          try { term.scrollLines(lines); } catch (e) {}
        },
        scrollToBottom: function () {
          try { term.scrollToBottom(); } catch (e) {}
        },
        reportCursor: function () { reportCursor(); }
      };

      function doFit() {
        try { fit.fit(); post({ type: "resize", cols: term.cols, rows: term.rows }); } catch (e) {}
      }
      doFit();
      window.addEventListener("resize", doFit);
      term.onData(function (data) { post({ type: "input", data: data }); });

      // Cursor bottom edge in page pixels so the RN side can lift the view
      // only as much as needed to keep typing visible above the keyboard.
      function reportCursor() {
        try {
          var screen = term.element && term.element.querySelector(".xterm-screen");
          if (!screen || !term.rows) return;
          var rect = screen.getBoundingClientRect();
          var cell = rect.height / term.rows;
          var bottom = rect.top + (term.buffer.active.cursorY + 1) * cell;
          post({ type: "cursor", bottom: Math.round(bottom) });
        } catch (e) {}
      }
      var cursorTimer = null;
      term.onCursorMove(function () {
        if (cursorTimer) return;
        cursorTimer = setTimeout(function () { cursorTimer = null; reportCursor(); }, 160);
      });

      // Touch → wheel bridge: xterm scrolls its own viewport in the normal
      // buffer and forwards wheel as mouse-scroll reports in the alternate
      // buffer (zellij scrollback, coding-agent TUIs), so synthesizing wheel
      // events gives touch scrolling in both modes.
      var touchY = null;
      var termEl = document.getElementById("term");
      termEl.addEventListener("touchstart", function (e) {
        touchY = e.touches.length === 1 ? e.touches[0].clientY : null;
      }, { passive: true });
      termEl.addEventListener("touchmove", function (e) {
        if (touchY === null || e.touches.length !== 1) return;
        var y = e.touches[0].clientY;
        var delta = touchY - y;
        if (Math.abs(delta) < 1) return;
        touchY = y;
        var target = term.element && (term.element.querySelector(".xterm-screen") || term.element);
        if (!target) return;
        try {
          target.dispatchEvent(new WheelEvent("wheel", { deltaY: delta, deltaMode: 0, bubbles: true, cancelable: true }));
        } catch (err) {}
        e.preventDefault();
      }, { passive: false });
      termEl.addEventListener("touchend", function () { touchY = null; }, { passive: true });
      termEl.addEventListener("touchcancel", function () { touchY = null; }, { passive: true });

      post({ type: "ready", cols: term.cols, rows: term.rows });
    }
    boot();
  })();
</script>
</body>
</html>`;
}

export const TerminalSurface = forwardRef<TerminalSurfaceHandle, TerminalSurfaceProps>(
  function TerminalSurface({ fontScale, onInput, onResize, onCursor }, ref) {
    const webRef = useRef<WebView | null>(null);
    const readyRef = useRef(false);
    const pendingRef = useRef<string[]>([]);
    // Rebuild the document only when the font size bucket changes (keeps the
    // emulator stable while typing).
    const html = useMemo(() => buildHtml(fontScale), [fontScale]);

    const inject = useCallback((js: string) => {
      webRef.current?.injectJavaScript(`${js};true;`);
    }, []);

    const scrollLines = useCallback((lines: number) => {
      if (!Number.isFinite(lines) || lines === 0) return;
      inject(`window.__matrixTerminal && window.__matrixTerminal.scrollLines(${Math.trunc(lines)})`);
    }, [inject]);

    const flush = useCallback(() => {
      if (!readyRef.current || pendingRef.current.length === 0) return;
      const buffered = pendingRef.current.join("");
      pendingRef.current = [];
      inject(`window.__term && window.__term.write(${JSON.stringify(buffered)})`);
    }, [inject]);

    useImperativeHandle(
      ref,
      () => ({
        write: (data: string) => {
          pendingRef.current.push(data);
          flush();
        },
        clear: () => {
          pendingRef.current = [];
          inject("window.__term && window.__term.clear()");
        },
        focus: () => inject("window.__matrixTerminal && window.__matrixTerminal.focus()"),
        blur: () => inject("window.__matrixTerminal && window.__matrixTerminal.blur()"),
        scrollLines,
        scrollToBottom: () => inject("window.__matrixTerminal && window.__matrixTerminal.scrollToBottom()"),
        reportCursor: () => inject("window.__matrixTerminal && window.__matrixTerminal.reportCursor()"),
      }),
      [flush, inject, scrollLines],
    );

    const handleMessage = useCallback(
      (event: WebViewMessageEvent) => {
        let msg: { type?: string; data?: string; cols?: number; rows?: number; bottom?: number };
        try {
          msg = JSON.parse(event.nativeEvent.data) as typeof msg;
        } catch {
          return;
        }
        if (msg.type === "ready") {
          readyRef.current = true;
          if (typeof msg.cols === "number" && typeof msg.rows === "number") {
            onResize(msg.cols, msg.rows);
          }
          flush();
          return;
        }
        if (msg.type === "input" && typeof msg.data === "string") {
          onInput(msg.data);
          return;
        }
        if (msg.type === "resize" && typeof msg.cols === "number" && typeof msg.rows === "number") {
          onResize(msg.cols, msg.rows);
          return;
        }
        if (msg.type === "cursor" && typeof msg.bottom === "number" && Number.isFinite(msg.bottom)) {
          onCursor?.(msg.bottom);
        }
      },
      [flush, onInput, onResize, onCursor],
    );

    return (
      // Terminal output is never recorded in session replay.
      <AnalyticsMask style={styles.container}>
        <WebView
          key="terminal-webview-accessory-enabled"
          ref={webRef}
          originWhitelist={["*"]}
          source={{ html }}
          onMessage={handleMessage}
          // Terminal owns scrolling; the RN side should not bounce.
          scrollEnabled
          overScrollMode="never"
          bounces={false}
          hideKeyboardAccessoryView={false}
          keyboardDisplayRequiresUserAction={false}
          androidLayerType="hardware"
          setBuiltInZoomControls={false}
          style={styles.web}
          containerStyle={styles.web}
        />
      </AnalyticsMask>
    );
  },
);

const styles = StyleSheet.create((theme) => ({
  container: { flex: 1, backgroundColor: theme.terminal.bg, overflow: "hidden" },
  web: { flex: 1, backgroundColor: theme.terminal.bg },
}));
