import {
  FIT_ADDON_JS,
  FIT_ADDON_VERSION,
  XTERM_CSS,
  XTERM_JS,
  XTERM_VERSION,
} from "@/components/terminal/xterm-bundle";

// The bundle is generated by scripts/bundle-xterm.mjs from the installed
// @xterm/xterm (^6.0.0) and @xterm/addon-fit (^0.11.0). If either dep is bumped
// without regenerating, these version markers drift out of range and fail here.
describe("inlined xterm bundle", () => {
  it("pins the expected xterm + addon-fit versions", () => {
    expect(XTERM_VERSION).toMatch(/^6\.\d+\.\d+$/);
    expect(FIT_ADDON_VERSION).toMatch(/^0\.11\.\d+$/);
  });

  it("inlines non-empty xterm dist assets", () => {
    // Guards against shipping a truncated/empty bundle that would render blank.
    expect(XTERM_JS.length).toBeGreaterThan(100_000);
    expect(XTERM_CSS).toContain(".xterm");
    expect(FIT_ADDON_JS).toContain("FitAddon");
  });

  it("exposes the globals the WebView boot code depends on", () => {
    // xterm's UMD wrapper spreads its exports onto globalThis; addon-fit assigns
    // globalThis.FitAddon. The boot code polls window.Terminal / window.FitAddon.
    expect(XTERM_JS).toContain("globalThis");
    expect(FIT_ADDON_JS).toContain("globalThis");
  });
});
