export const mobileQueryKeys = {
  activeComputer: (userId: string) => ["mobile", "computers", "active", userId] as const,
  canonicalChats: (userId: string, computerKey: string) => [
    "mobile",
    "chats",
    userId,
    computerKey,
  ] as const,
  // The two keys below extend `canonicalChats`, so refreshing the chat list
  // (a sent message, a chat event) marks them stale along with it.
  canonicalChatsOlder: (userId: string, computerKey: string) => [
    "mobile",
    "chats",
    userId,
    computerKey,
    "older",
  ] as const,
  projectChats: (userId: string, computerKey: string, projectId: string) => [
    "mobile",
    "chats",
    userId,
    computerKey,
    "project",
    projectId,
  ] as const,
  canonicalChatDetail: (userId: string, computerKey: string, chatId: string) => [
    "mobile",
    "chats",
    "detail",
    userId,
    computerKey,
    chatId,
  ] as const,
  /** `scope` is a project id, "global" for chats in no project, or "all". */
  chatSearch: (userId: string, computerKey: string, scope: string, query: string) => [
    "mobile",
    "chats",
    "search",
    userId,
    computerKey,
    scope,
    query,
  ] as const,
  botChat: (userId: string, gatewayUrl: string, chatId: string) => [
    "native-bot-chat", userId, gatewayUrl, chatId,
  ] as const,
  chatProviderCatalog: (userId: string, computerKey: string) => [
    "mobile",
    "chat-providers",
    userId,
    computerKey,
  ] as const,
  projects: (userId: string, computerKey: string) => [
    "mobile",
    "projects",
    userId,
    computerKey,
  ] as const,
  matrixCredit: (userId: string, computerKey: string) => [
    "mobile",
    "credit",
    userId,
    computerKey,
  ] as const,
  agents: (userId: string, computerKey: string) => [
    "mobile",
    "agents",
    userId,
    computerKey,
  ] as const,
  /** `agentIds` names the agents the statuses were read for, so a changed list reads again. */
  agentStatuses: (userId: string, computerKey: string, agentIds: string) => [
    "mobile",
    "agents",
    "status",
    userId,
    computerKey,
    agentIds,
  ] as const,
  files: (userId: string, computerKey: string, path: string) => [
    "mobile",
    "files",
    userId,
    computerKey,
    path,
  ] as const,
  filePreview: (userId: string, computerKey: string, path: string) => [
    "mobile",
    "files",
    "preview",
    userId,
    computerKey,
    path,
  ] as const,
  terminals: (userId: string, computerKey: string) => [
    "mobile",
    "terminals",
    userId,
    computerKey,
  ] as const,
  integrations: (userId: string, computerKey: string) => [
    "mobile",
    "integrations",
    userId,
    computerKey,
  ] as const,
  apps: (userId: string, computerKey: string) => [
    "mobile",
    "apps",
    userId,
    computerKey,
  ] as const,
  appSession: (userId: string, computerKey: string, slug: string) => [
    "mobile",
    "apps",
    "session",
    userId,
    computerKey,
    slug,
  ] as const,
  systemInfo: (userId: string, computerKey: string) => [
    "mobile",
    "settings",
    "system",
    userId,
    computerKey,
  ] as const,
  billing: (userId: string, runtimeSlot: string) => [
    "mobile",
    "settings",
    "billing",
    userId,
    runtimeSlot,
  ] as const,
  accountDeletion: (userId: string) => [
    "mobile",
    "settings",
    "account-deletion",
    userId,
  ] as const,
};
