export const mobileQueryKeys = {
  activeComputer: (userId: string) => ["mobile", "computers", "active", userId] as const,
  conversations: (userId: string, computerKey: string) => [
    "mobile",
    "conversations",
    userId,
    computerKey,
  ] as const,
  files: (userId: string, computerKey: string, path: string) => [
    "mobile",
    "files",
    userId,
    computerKey,
    path,
  ] as const,
  filePreview: (userId: string, computerKey: string, path: string) => [
    "mobile",
    "files",
    "preview",
    userId,
    computerKey,
    path,
  ] as const,
  terminals: (userId: string, computerKey: string) => [
    "mobile",
    "terminals",
    userId,
    computerKey,
  ] as const,
  integrations: (userId: string, computerKey: string) => [
    "mobile",
    "integrations",
    userId,
    computerKey,
  ] as const,
  apps: (userId: string, computerKey: string) => [
    "mobile",
    "apps",
    userId,
    computerKey,
  ] as const,
  appSession: (userId: string, computerKey: string, slug: string) => [
    "mobile",
    "apps",
    "session",
    userId,
    computerKey,
    slug,
  ] as const,
  systemInfo: (userId: string, computerKey: string) => [
    "mobile",
    "settings",
    "system",
    userId,
    computerKey,
  ] as const,
  billing: (userId: string, runtimeSlot: string) => [
    "mobile",
    "settings",
    "billing",
    userId,
    runtimeSlot,
  ] as const,
};
