import { describe, expect, it, vi } from 'vitest';
import { createHmac } from 'node:crypto';
import { AccountDeletionConflictError } from '../../packages/platform/src/account-deletion/repository.js';
import { createAccountDeletionRoutes } from '../../packages/platform/src/account-deletion/routes.js';
const owner = 'user_test123';
const status = { status: 'scheduled' as const, completesBy: '2026-10-10T10:00:00.000Z', billingStopped: true };
function fixture(overrides = {}) {
  const service = { schedule: vi.fn(async () => status), get: vi.fn(async () => status), cancel: vi.fn(async () => ({...status, status:'cancelled' as const})), reconcile: vi.fn(), isBlocked: vi.fn() };
  const app = createAccountDeletionRoutes({service, verify: async (token:string) => token === 'valid' ? owner : null, webhookSecret:'whsec_'+Buffer.from('s'.repeat(32)).toString('base64'), publishableKey:'pk_live_example', exportData: async () => ({downloads:[], migrationUrl:'/runtime'}), ...overrides});
  return {app, service};
}
function post(body:unknown, token='valid') { return {method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)}; }
describe('account deletion ingress', () => {
 it('requires a verified bearer, never accepts a caller-selected owner', async()=>{const {app,service}=fixture();expect((await app.request('/api/account/delete',post({confirm:true},'invalid'))).status).toBe(401);expect((await app.request('/api/account/delete',post({confirm:true,userId:'user_other'}))).status).toBe(422);expect(service.schedule).not.toHaveBeenCalled();});
 it('schedules confirmed requests for the verified subject',async()=>{const {app,service}=fixture();const response=await app.request('/api/account/delete',post({confirm:true}));expect(response.status).toBe(202);expect(await response.json()).toEqual(status);expect(service.schedule).toHaveBeenCalledWith(owner);});
 it('rejects absent confirmation, malformed and oversized bodies before scheduling',async()=>{const {app,service}=fixture();expect((await app.request('/api/account/delete',post({confirm:false}))).status).toBe(422);expect((await app.request('/api/account/delete',{...post({}),body:'{'})).status).toBe(400);expect((await app.request('/api/account/delete',post({confirm:true,pad:'a'.repeat(2048)}))).status).toBe(413);expect(service.schedule).not.toHaveBeenCalled();});
 it('supports status/export and cancellation on the same owner flow',async()=>{const {app,service}=fixture();expect((await app.request('/api/account/delete',{headers:{Authorization:'Bearer valid'}})).status).toBe(200);expect((await app.request('/api/account/delete/export',{headers:{Authorization:'Bearer valid'}})).status).toBe(200);expect((await app.request('/api/account/delete/cancel',post({confirm:true}))).status).toBe(200);expect(service.cancel).toHaveBeenCalledWith(owner);});
 it('returns coarse errors without leaking dependencies',async()=>{const {app,service}=fixture();service.schedule.mockRejectedValueOnce(new Error('/private/secret postgres password'));const response=await app.request('/api/account/delete',post({confirm:true}));expect(response.status).toBe(503);expect(await response.json()).toEqual({error:'Account deletion is unavailable. Please try again.'});});
 it('verifies raw webhook signatures before scheduling',async()=>{const {app,service}=fixture();const body=JSON.stringify({type:'user.deleted',data:{id:owner,deleted:true,object:'user'}});const timestamp=String(Math.floor(Date.now()/1000));const sig=createHmac('sha256',Buffer.from('s'.repeat(32))).update('evt_1.'+timestamp+'.'+body).digest('base64');expect((await app.request('/webhooks/clerk/users',{method:'POST',headers:{'svix-id':'evt_1','svix-timestamp':timestamp,'svix-signature':'v1,'+sig},body})).status).toBe(200);expect(service.schedule).toHaveBeenCalledWith(owner,true);expect((await app.request('/webhooks/clerk/users',{method:'POST',body})).status).toBe(401);});
 it('does not acknowledge a failed durable webhook schedule',async()=>{const {app,service}=fixture();service.schedule.mockRejectedValue(new Error('db down'));const body=JSON.stringify({type:'user.deleted',data:{id:owner,deleted:true}});const timestamp=String(Math.floor(Date.now()/1000));const sig=createHmac('sha256',Buffer.from('s'.repeat(32))).update('evt_2.'+timestamp+'.'+body).digest('base64');expect((await app.request('/webhooks/clerk/users',{method:'POST',headers:{'svix-id':'evt_2','svix-timestamp':timestamp,'svix-signature':'v1,'+sig},body})).status).toBe(503);});
 it('closes both exports when erasure starts',async()=>{const {app,service}=fixture({exportPlatformData:async()=>({private:true})});service.get.mockResolvedValue({...status,status:'processing'} as never);for(const path of ['/api/account/delete/export','/api/account/delete/export/platform'])expect((await app.request(path,{headers:{Authorization:'Bearer valid'}})).status).toBe(409);});
 it('closes both exports when the grace deadline passes before worker claim',async()=>{const exportData=vi.fn();const exportPlatformData=vi.fn();const {app,service}=fixture({exportData,exportPlatformData});service.get.mockResolvedValue({...status,erasesAfter:new Date(Date.now()-1000).toISOString()} as never);for(const path of ['/api/account/delete/export','/api/account/delete/export/platform'])expect((await app.request(path,{headers:{Authorization:'Bearer valid'}})).status).toBe(409);expect(exportData).not.toHaveBeenCalled();expect(exportPlatformData).not.toHaveBeenCalled();});
 it('returns a safe conflict when cancellation is closed',async()=>{const {app,service}=fixture();service.cancel.mockRejectedValue(new AccountDeletionConflictError());expect((await app.request('/api/account/delete/cancel',post({confirm:true}))).status).toBe(409);});
 it('validates and forwards bounded export cursors',async()=>{const exportData=vi.fn(async()=>({downloads:[],migrationUrl:'/runtime',nextCursor:'next'}));const {app}=fixture({exportData});expect((await app.request('/api/account/delete/export?cursor=abc',{headers:{Authorization:'Bearer valid'}})).status).toBe(200);expect(exportData).toHaveBeenCalledWith(owner,'abc');expect((await app.request('/api/account/delete/export?userId=other',{headers:{Authorization:'Bearer valid'}})).status).toBe(422);});
 it('captures native Apple authorization only for the bearer subject',async()=>{const registerAppleAuthorization=vi.fn(async()=>{});const {app}=fixture({registerAppleAuthorization});expect((await app.request('/api/account/apple-token',post({code:'apple-authorization-code'}))).status).toBe(200);expect(registerAppleAuthorization).toHaveBeenCalledWith(owner,'apple-authorization-code');expect((await app.request('/api/account/apple-token',post({code:'x',userId:'user_other'}))).status).toBe(422);expect((await app.request('/api/account/apple-token',post({code:'x'},'invalid'))).status).toBe(401);});
 it('serves the public deletion page with a restricted CSP and no-store',async()=>{const {app}=fixture();const response=await app.request('/account/delete');expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toContain('no-store');expect(response.headers.get('content-security-policy')).toContain("frame-ancestors 'none'");const html=await response.text();expect(html).toContain('five days');expect(html).toContain('Download');expect(html).toContain('migration');expect(html).toContain('/api/account/delete');});
});
