import { z } from 'zod/v4';

export const CUSTOMER_VPS_BOOTSTRAP_STAGES = [
  'cloud_init_started',
  'packages_ready',
  'bundle_downloaded',
  'bundle_installed',
  'database_ready',
  'restore_starting',
  'restore_ready',
  'gateway_starting',
  'gateway_preflight_checking_exec',
  'gateway_preflight_checking_paths',
  'gateway_preflight_checking_environment',
  'gateway_preflight_ready',
  'gateway_unit_failed_chdir',
  'gateway_unit_failed_exec',
  'gateway_unit_failed_user',
  'gateway_unit_failed_group',
  'gateway_unit_failed_environment',
  'gateway_unit_failed_exit',
  'gateway_unit_failed_timeout',
  'gateway_unit_failed_resource',
  'gateway_unit_failed_signal',
  'gateway_unit_failed_other',
  'gateway_unit_started',
  'gateway_wrapper_started',
  'gateway_environment_ready',
  'gateway_home_sync_started',
  'gateway_home_assets_failed_template',
  'gateway_home_assets_failed_home',
  'gateway_home_assets_failed_copy',
  'gateway_home_assets_failed_commit',
  'gateway_home_assets_failed_status_1',
  'gateway_home_assets_failed_status_2',
  'gateway_home_assets_failed_status_9',
  'gateway_home_assets_failed_status_47',
  'gateway_home_assets_failed_status_48',
  'gateway_home_assets_failed_status_49',
  'gateway_home_assets_failed_status_50',
  'gateway_home_assets_failed_status_51',
  'gateway_home_assets_failed_status_125',
  'gateway_home_assets_failed_status_126',
  'gateway_home_assets_failed_status_127',
  'gateway_home_assets_failed_status_134',
  'gateway_home_assets_failed_status_139',
  'gateway_home_assets_failed_status_143',
  'gateway_home_assets_failed_node_missing',
  'gateway_home_assets_failed_node_unusable',
  'gateway_home_assets_failed_node_program',
  'gateway_home_assets_failed_other',
  'gateway_home_assets_timed_out',
  'gateway_home_assets_ready',
  'gateway_home_ownership_started',
  'gateway_home_ownership_ready',
  'gateway_home_ready',
  'gateway_launch_ready',
  'gateway_process_started',
  'gateway_healthy',
  'registration_ready',
  'registered',
] as const;

export const CustomerVpsBootstrapStageSchema = z.enum(CUSTOMER_VPS_BOOTSTRAP_STAGES);
export type CustomerVpsBootstrapStage = z.infer<typeof CustomerVpsBootstrapStageSchema>;

export function customerVpsBootstrapStageRank(stage: CustomerVpsBootstrapStage): number {
  return CUSTOMER_VPS_BOOTSTRAP_STAGES.indexOf(stage) + 1;
}
