import { StyleSheet } from "react-native-unistyles";

export const agentProjectKanbanStyles = StyleSheet.create((theme) => ({
  segmentedControl: {
    minHeight: 44,
    flexDirection: "row",
    padding: 3,
    borderRadius: 22,
    borderCurve: "continuous",
    backgroundColor: theme.colors.secondary,
  },
  segment: {
    flex: 1,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 19,
  },
  segmentSelected: {
    backgroundColor: theme.colors.card,
    boxShadow: theme.shadows.sm,
  },
  segmentText: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 13,
    color: theme.colors.mutedForeground,
  },
  segmentTextSelected: {
    color: theme.colors.foreground,
  },
  board: {
    gap: 12,
  },
  tabletBoard: {
    flexDirection: "row",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  column: {
    width: "100%",
    gap: 8,
    padding: 12,
    borderRadius: 16,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.secondary,
  },
  tabletColumn: {
    width: "48.5%",
    minWidth: 300,
    flexGrow: 1,
  },
  columnHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  columnTitle: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 14,
    color: theme.colors.foreground,
  },
  columnCount: {
    minWidth: 24,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
    textAlign: "center",
    fontFamily: theme.fonts.mono,
    fontSize: 11,
    color: theme.colors.mutedForeground,
    backgroundColor: theme.colors.card,
    fontVariant: ["tabular-nums"],
  },
  emptyText: {
    fontFamily: theme.fonts.sans,
    fontSize: 12,
    color: theme.colors.mutedForeground,
  },
  taskCard: {
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.card,
  },
  taskHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  taskHeadingCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  taskTitle: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 14,
    color: theme.colors.foreground,
  },
  taskMeta: {
    fontFamily: theme.fonts.sans,
    fontSize: 11,
    color: theme.colors.mutedForeground,
  },
  addButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: theme.colors.secondary,
  },
  aggregateRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  aggregate: {
    minWidth: 58,
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: theme.colors.secondary,
  },
  aggregateAttention: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.glow,
  },
  aggregateValue: {
    fontFamily: theme.fonts.mono,
    fontSize: 12,
    color: theme.colors.foreground,
    fontVariant: ["tabular-nums"],
  },
  aggregateLabel: {
    fontFamily: theme.fonts.sans,
    fontSize: 10,
    color: theme.colors.mutedForeground,
  },
  threadList: {
    gap: 6,
  },
  threadRow: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRadius: 11,
    backgroundColor: theme.colors.secondary,
  },
  threadCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  threadTitle: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 12,
    color: theme.colors.foreground,
  },
  threadMeta: {
    fontFamily: theme.fonts.sans,
    fontSize: 10,
    color: theme.colors.mutedForeground,
  },
  attentionDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: theme.colors.glow,
  },
}));
