import { StyleSheet } from "react-native-unistyles";

export const agentProjectWorkspaceStyles = StyleSheet.create((theme) => ({
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: 24,
    backgroundColor: theme.colors.background,
  },
  centerTitle: {
    maxWidth: 320,
    textAlign: "center",
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 15,
    color: theme.colors.foreground,
  },
  content: {
    width: "100%",
    gap: 18,
    padding: 16,
    paddingBottom: 40,
    backgroundColor: theme.colors.background,
  },
  tabletContent: {
    maxWidth: 920,
    alignSelf: "center",
    paddingHorizontal: 28,
  },
  entrySection: {
    gap: 10,
  },
  entryHeading: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 17,
    color: theme.colors.foreground,
  },
  projectEntry: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 16,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.card,
    boxShadow: theme.shadows.sm,
  },
  projectIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    borderCurve: "continuous",
    backgroundColor: theme.colors.secondary,
  },
  projectEntryText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  pressed: {
    opacity: 0.72,
  },
  attentionText: {
    fontFamily: theme.fonts.sansMedium,
    fontSize: 12,
    color: theme.colors.glow,
  },
  emptyText: {
    fontFamily: theme.fonts.sans,
    fontSize: 13,
    lineHeight: 19,
    color: theme.colors.mutedForeground,
  },
  offlineBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderCurve: "continuous",
    backgroundColor: theme.colors.secondary,
  },
  offlineText: {
    flex: 1,
    fontFamily: theme.fonts.sansMedium,
    fontSize: 12,
    color: theme.colors.foreground,
  },
  bannerButton: {
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 12,
    borderRadius: 17,
    backgroundColor: theme.colors.card,
  },
  bannerButtonText: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 12,
    color: theme.colors.forest,
  },
  warningText: {
    fontFamily: theme.fonts.sansMedium,
    fontSize: 12,
    color: theme.colors.glow,
  },
  projectHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  projectHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  heading: {
    fontFamily: theme.fonts.display,
    fontSize: 26,
    color: theme.colors.foreground,
  },
  subheading: {
    fontFamily: theme.fonts.sans,
    fontSize: 13,
    color: theme.colors.mutedForeground,
  },
  primaryButton: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 13,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
  },
  primaryButtonText: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 12,
    color: theme.colors.primaryForeground,
  },
  projectSelector: {
    gap: 8,
  },
  projectPill: {
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.card,
  },
  projectPillSelected: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.secondary,
  },
  projectPillText: {
    fontFamily: theme.fonts.sansMedium,
    fontSize: 13,
    color: theme.colors.mutedForeground,
  },
  projectPillTextSelected: {
    color: theme.colors.foreground,
  },
  section: {
    gap: 8,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionHeading: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 16,
    color: theme.colors.foreground,
  },
  countText: {
    minWidth: 24,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
    overflow: "hidden",
    textAlign: "center",
    fontFamily: theme.fonts.mono,
    fontSize: 11,
    color: theme.colors.mutedForeground,
    backgroundColor: theme.colors.secondary,
    fontVariant: ["tabular-nums"],
  },
  taskList: {
    gap: 10,
  },
  taskCard: {
    gap: 8,
    padding: 12,
    borderRadius: 16,
    borderCurve: "continuous",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.card,
    boxShadow: theme.shadows.sm,
  },
  taskHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  taskHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  secondaryButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 17,
    backgroundColor: theme.colors.secondary,
  },
  threadRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 13,
    borderCurve: "continuous",
    backgroundColor: theme.colors.secondary,
  },
  threadIcon: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: theme.colors.card,
  },
  threadText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  rowTitle: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 14,
    color: theme.colors.foreground,
  },
  rowSubtitle: {
    fontFamily: theme.fonts.sans,
    fontSize: 12,
    color: theme.colors.mutedForeground,
  },
  attentionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.colors.glow,
  },
  retryButton: {
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: theme.colors.primary,
  },
  retryButtonText: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 13,
    color: theme.colors.primaryForeground,
  },
}));
