/**
 * Company Brain store: table shapes, domain values, inputs, limits, and the
 * error class. This file is the contract between database.ts, repository.ts,
 * and the tests. Changes here must be mirrored in database.ts (CHECK
 * constraints) and schemas.ts (Zod bounds).
 */
import type { ColumnType, Generated } from "kysely";
import type { BrainClaimTables } from "./claims/types.js";

export * from "./ref-match-types.js";

type Timestamp = ColumnType<Date | string, Date | string, Date | string>;
type NullableTimestamp = ColumnType<Date | string | null, Date | string | null, Date | string | null>;

// Limits. SQL CHECK constraints in database.ts and Zod schemas mirror these.
export const BRAIN_OWNER_ID_MAX_CHARS = 256;
export const BRAIN_SCOPE_ID_MAX_CHARS = 256;
export const BRAIN_TITLE_MAX_CHARS = 300;
/** Combined utf8 byte size of title + body for one live document. */
export const BRAIN_DOCUMENT_MAX_BYTES = 65_536;
export const BRAIN_PERMALINK_MAX_CHARS = 2048;
export const BRAIN_SOURCE_LABEL_MAX_CHARS = 300;
export const BRAIN_SOURCE_EXTERNAL_REF_MAX_CHARS = 512;
export const BRAIN_CURSOR_MAX_CHARS = 2048;
export const BRAIN_NEXT_ACTION_MAX_CHARS = 500;
export const BRAIN_MAX_REVISION = 2_147_483_646;
export const BRAIN_DEFAULT_MAX_DOCUMENTS_PER_SCOPE = 10_000;
export const BRAIN_MAX_DOCUMENTS_PER_SCOPE_CEILING = 100_000;
/** 256 MiB of live title + body bytes per scope; tombstones count 0 bytes. */
export const BRAIN_DEFAULT_MAX_BYTES_PER_SCOPE = 268_435_456;
/** Prior-state snapshots retained per document id, newest first. */
export const BRAIN_REVISIONS_PER_DOCUMENT = 10;
/** Sync receipts retained per source, newest first; running rows are never pruned. */
export const BRAIN_RECEIPTS_PER_SOURCE = 50;
export const BRAIN_LIST_DEFAULT_LIMIT = 50;
export const BRAIN_LIST_MAX_LIMIT = 100;
export const BRAIN_SEARCH_MAX_LIMIT = 50;
export const BRAIN_SEARCH_QUERY_MAX_CHARS = 500;
/** Upserts and deletions are each capped at this many per sync batch. */
export const BRAIN_SYNC_BATCH_MAX_ITEMS = 200;
export const BRAIN_EVIDENCE_PROOFS_MAX = 100;
/** Refs one synced document may carry (paths, PR numbers, spec ids); the adapter truncates beyond this. */
export const BRAIN_DOCUMENT_REFS_MAX = 200;
/** Refs across all upserts of one sync batch; keeps the scope-lock hold short. */
export const BRAIN_SYNC_BATCH_MAX_REFS = 10_000;
/** utf8 bytes; keeps the refs primary-key btree tuple under Postgres' ~2.7 KB index row limit. */
export const BRAIN_REF_VALUE_MAX_BYTES = 512;

// Identifier rules. Document ids are sha256 hex chosen by the adapter from a
// stable external identity tuple, never from content. Source and receipt ids
// are generated by the repository.
export const BRAIN_DOCUMENT_ID_PATTERN = /^[a-f0-9]{64}$/;
export const BRAIN_SOURCE_ID_PATTERN = /^src_[a-f0-9]{32}$/;
export const BRAIN_RECEIPT_ID_PATTERN = /^rcp_[a-f0-9]{32}$/;
export const BRAIN_CONTENT_HASH_PATTERN = /^[a-f0-9]{64}$/;
/** Source kind and document provenance share this vocabulary shape. */
export const BRAIN_KIND_PATTERN = /^[a-z][a-z0-9_]{0,31}$/;
export const BRAIN_ERROR_CODE_PATTERN = /^[a-z][a-z0-9_]{0,63}$/;
export const BRAIN_UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export type BrainSourceStatus = "active" | "paused" | "disabled";
export const BRAIN_SOURCE_STATUSES: readonly BrainSourceStatus[] = ["active", "paused", "disabled"];

export type BrainSyncReceiptStatus = "running" | "succeeded" | "partial" | "failed" | "interrupted";
export const BRAIN_SYNC_RECEIPT_STATUSES: readonly BrainSyncReceiptStatus[] = [
  "running", "succeeded", "partial", "failed", "interrupted",
];
/** Terminal statuses a caller may close a receipt with. */
export type BrainSyncReceiptOutcome = "succeeded" | "partial" | "failed";

/** Why a prior-state snapshot was taken: the revision was updated or tombstoned. */
export type BrainDocumentChange = "updated" | "deleted";

// Kysely tables. Every row carries (owner_id, scope_id) and every query filters
// on both. Timestamps are written explicitly by the repository clock.

export interface BrainSourcesTable {
  owner_id: string;
  scope_id: string;
  source_id: string;
  kind: string;
  external_ref: string;
  label: string;
  status: BrainSourceStatus;
  revision: number;
  created_at: Timestamp;
  updated_at: Timestamp;
  deleted_at: NullableTimestamp;
}

export interface BrainDocumentsTable {
  owner_id: string;
  scope_id: string;
  document_id: string;
  source_id: string | null;
  incarnation: string;
  title: string;
  body: string;
  permalink: string;
  content_hash: string;
  byte_count: number;
  provenance: string;
  revision: number;
  source_updated_at: Timestamp;
  published_at: Timestamp;
  updated_at: Timestamp;
  deleted_at: NullableTimestamp;
}

export interface BrainDocumentRevisionsTable {
  owner_id: string;
  scope_id: string;
  document_id: string;
  /** The source that owned the document when the snapshot was taken; null for manual publication. */
  source_id: string | null;
  incarnation: string;
  revision: number;
  change: BrainDocumentChange;
  title: string;
  body: string;
  permalink: string;
  content_hash: string;
  byte_count: number;
  provenance: string;
  source_updated_at: Timestamp;
  superseded_at: Timestamp;
}

export interface BrainSyncCursorsTable {
  owner_id: string;
  scope_id: string;
  source_id: string;
  cursor: string;
  updated_at: Timestamp;
}

export interface BrainSyncReceiptsTable {
  owner_id: string;
  scope_id: string;
  source_id: string;
  receipt_id: string;
  status: BrainSyncReceiptStatus;
  read_count: Generated<number>;
  written_count: Generated<number>;
  unchanged_count: Generated<number>;
  deleted_count: Generated<number>;
  failed_count: Generated<number>;
  next_action: Generated<string>;
  error_code: string | null;
  cursor_before: string | null;
  cursor_after: string | null;
  started_at: Timestamp;
  finished_at: NullableTimestamp;
}

/** What a live synced document touches; replaced wholesale by applySyncBatch, removed with every tombstone. */
export interface BrainDocumentRefsTable {
  owner_id: string;
  scope_id: string;
  document_id: string;
  kind: string;
  value: string;
}

export interface BrainDatabase extends BrainClaimTables {
  brain_sources: BrainSourcesTable;
  brain_documents: BrainDocumentsTable;
  brain_document_revisions: BrainDocumentRevisionsTable;
  brain_document_refs: BrainDocumentRefsTable;
  brain_sync_cursors: BrainSyncCursorsTable;
  brain_sync_receipts: BrainSyncReceiptsTable;
}

// Domain values. Timestamps are ISO-8601 strings.

/** Resolved by the caller (route/service) before any repository call. */
export interface BrainScopeKey {
  readonly scopeId: string;
  readonly ownerId: string;
}

export interface BrainSource {
  readonly scopeId: string;
  readonly ownerId: string;
  readonly sourceId: string;
  readonly kind: string;
  readonly externalRef: string;
  readonly label: string;
  readonly status: BrainSourceStatus;
  readonly revision: number;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
}

export interface BrainCitation {
  readonly documentId: string;
  readonly scopeId: string;
  readonly revision: number;
  readonly incarnation: string;
  readonly permalink: string;
  readonly sourceUpdatedAt: string;
  readonly publishedAt: string;
}

export interface BrainDocumentSummary extends BrainCitation {
  readonly ownerId: string;
  readonly sourceId: string | null;
  readonly title: string;
  readonly provenance: string;
  readonly contentHash: string;
  readonly byteCount: number;
  readonly updatedAt: string;
  readonly deletedAt: string | null;
}

export interface BrainDocument extends BrainDocumentSummary {
  readonly body: string;
}

export interface BrainDocumentRevision {
  readonly scopeId: string;
  readonly documentId: string;
  readonly incarnation: string;
  readonly revision: number;
  readonly change: BrainDocumentChange;
  readonly title: string;
  readonly body: string;
  readonly permalink: string;
  readonly provenance: string;
  readonly contentHash: string;
  readonly byteCount: number;
  readonly sourceUpdatedAt: string;
  readonly supersededAt: string;
}

export interface BrainSyncCursor {
  readonly scopeId: string;
  readonly sourceId: string;
  readonly cursor: string;
  readonly updatedAt: string;
}

export interface BrainSyncCounts {
  readonly read: number;
  readonly written: number;
  readonly unchanged: number;
  readonly deleted: number;
  readonly failed: number;
}

export interface BrainSyncReceipt {
  readonly scopeId: string;
  readonly sourceId: string;
  readonly receiptId: string;
  readonly status: BrainSyncReceiptStatus;
  readonly counts: BrainSyncCounts;
  readonly nextAction: string;
  readonly errorCode: string | null;
  readonly cursorBefore: string | null;
  readonly cursorAfter: string | null;
  readonly startedAt: string;
  readonly finishedAt: string | null;
}

/** What a caller must present to prove a citation is still current. */
export interface BrainEvidenceProof {
  readonly documentId: string;
  readonly incarnation: string;
  readonly revision: number;
}

// Repository inputs. Zod schemas in schemas.ts bound every field.

export interface BrainCreateSourceInput {
  readonly kind: string;
  readonly externalRef: string;
  readonly label: string;
  readonly status?: BrainSourceStatus;
}

export interface BrainUpdateSourceInput {
  readonly sourceId: string;
  readonly expectedRevision: number;
  readonly label?: string;
  readonly status?: BrainSourceStatus;
}

export interface BrainDeleteSourceInput {
  readonly sourceId: string;
  readonly expectedRevision: number;
}

export interface BrainDocumentContentInput {
  readonly documentId: string;
  readonly title: string;
  readonly body: string;
  /** Empty string when the document has no external link. */
  readonly permalink: string;
  readonly sourceUpdatedAt: string;
  readonly provenance: string;
}

export interface BrainUpsertDocumentInput extends BrainDocumentContentInput {
  /** Null for manual publication; otherwise a live source in the same scope. */
  readonly sourceId: string | null;
  /** Omitted: unconditional. 0: must not exist live. N: live revision must equal N. */
  readonly expectedRevision?: number;
}

export interface BrainReviseDocumentInput {
  readonly documentId: string;
  readonly expectedRevision: number;
  readonly title?: string;
  readonly body?: string;
  readonly permalink?: string;
  readonly sourceUpdatedAt?: string;
}

export interface BrainDeleteDocumentInput {
  readonly documentId: string;
  /** Omitted: tombstone whatever live revision exists. */
  readonly expectedRevision?: number;
}

/** A ref kind follows BRAIN_KIND_PATTERN (`path`, `pr`, `spec`); the value is opaque text. */
export interface BrainDocumentRef {
  readonly kind: string;
  readonly value: string;
}
