// Actual app components captured with fictional example data or an empty workspace.
// Capture steps: specs/362-default-app-sculpted-family/preview/README.md.
export const previewScreenshots: Readonly<Record<string, "example" | "empty">> = {
  "folio": "example",
  "atlas": "example",
  "agenda": "empty",
  "follow-ups": "empty",
  "subscriptions": "empty",
  "deliveries": "empty",
  "reading-library": "empty",
  "people": "empty",
  "files": "empty",
  "notes": "empty",
  "habits": "empty",
  "focus": "empty",
  "cashflow": "example",
  "revenue": "empty",
  "pipeline": "empty",
  "projects": "example",
  "meeting-briefs": "empty",
  "support": "empty",
  "hiring": "empty",
  "company-spend": "empty",
  "releases": "empty",
  "knowledge": "empty",
  "campaigns": "empty",
  "analytics": "empty",
  "workout-coach": "empty",
  "paycheck-runway": "empty",
  "meal-planner": "empty",
  "job-search": "empty",
  "study-notes": "empty",
  "journal-memory": "empty",
  "chess-coach": "empty"
};
