import { HugeiconsIcon } from "@hugeicons/react";
import { Note01Icon as Note01Data } from "@hugeicons/core-free-icons";
import type { ComponentProps, ComponentType } from "react";
import type { IconSvgElement } from "@hugeicons/react";

import { Activity as ActivityData } from "@hugeicons/core-free-icons";
import { ActivityIcon as ActivityIconData } from "@hugeicons/core-free-icons";
import { AlertCircle as AlertCircleData } from "@hugeicons/core-free-icons";
import { AlertCircleIcon as AlertCircleIconData } from "@hugeicons/core-free-icons";
import { AlertTriangle as AlertTriangleData } from "@hugeicons/core-free-icons";
import { TriangleAlertIcon as AlertTriangleIconData } from "@hugeicons/core-free-icons";
import { AppWindowIcon as AppWindowData } from "@hugeicons/core-free-icons";
import { AppWindowIcon as AppWindowIconData } from "@hugeicons/core-free-icons";
import { Archive as ArchiveData } from "@hugeicons/core-free-icons";
import { ArchiveRestore as ArchiveRestoreData } from "@hugeicons/core-free-icons";
import { ArrowDown as ArrowDownData } from "@hugeicons/core-free-icons";
import { ArrowDownIcon as ArrowDownIconData } from "@hugeicons/core-free-icons";
import { ArrowLeft as ArrowLeftData } from "@hugeicons/core-free-icons";
import { ArrowLeftIcon as ArrowLeftIconData } from "@hugeicons/core-free-icons";
import { ArrowRight as ArrowRightData } from "@hugeicons/core-free-icons";
import { ArrowUp as ArrowUpData } from "@hugeicons/core-free-icons";
import { ArrowUp01Icon as ArrowUpCircleIconData } from "@hugeicons/core-free-icons";
import { ArrowUpIcon as ArrowUpIconData } from "@hugeicons/core-free-icons";
import { ArrowUpRightIcon as ArrowUpRightIconData } from "@hugeicons/core-free-icons";
import { AudioLinesIcon as AudioLinesIconData } from "@hugeicons/core-free-icons";
import { AudioWaveformIcon as AudioWaveformIconData } from "@hugeicons/core-free-icons";
import { BatteryFullIcon as BatteryFullIconData } from "@hugeicons/core-free-icons";
import { BatteryMediumIcon as BatteryMediumIconData } from "@hugeicons/core-free-icons";
import { Bell as BellData } from "@hugeicons/core-free-icons";
import { BlocksIcon as BlocksData } from "@hugeicons/core-free-icons";
import { Bot as BotData } from "@hugeicons/core-free-icons";
import { BotIcon as BotIconData } from "@hugeicons/core-free-icons";
import { Box as BoxData } from "@hugeicons/core-free-icons";
import { BoxIcon as BoxIconData } from "@hugeicons/core-free-icons";
import { Braces as BracesData } from "@hugeicons/core-free-icons";
import { Brain as BrainData } from "@hugeicons/core-free-icons";
import { BrushIcon as BrushIconData } from "@hugeicons/core-free-icons";
import { Bug as BugData } from "@hugeicons/core-free-icons";
import { CableIcon as CableIconData } from "@hugeicons/core-free-icons";
import { CalendarIcon as CalendarIconData } from "@hugeicons/core-free-icons";
import { Check as CheckData } from "@hugeicons/core-free-icons";
import { CheckmarkCircle02Icon as CheckCircle2Data } from "@hugeicons/core-free-icons";
import { CheckmarkCircle02Icon as CheckCircle2IconData } from "@hugeicons/core-free-icons";
import { CheckmarkCircleIcon as CheckCircleIconData } from "@hugeicons/core-free-icons";
import { CheckIcon as CheckIconData } from "@hugeicons/core-free-icons";
import { ChevronDown as ChevronDownData } from "@hugeicons/core-free-icons";
import { ChevronDownIcon as ChevronDownIconData } from "@hugeicons/core-free-icons";
import { ChevronLeft as ChevronLeftData } from "@hugeicons/core-free-icons";
import { ChevronLeftIcon as ChevronLeftIconData } from "@hugeicons/core-free-icons";
import { ChevronRight as ChevronRightData } from "@hugeicons/core-free-icons";
import { ChevronRightIcon as ChevronRightIconData } from "@hugeicons/core-free-icons";
import { ChevronUp as ChevronUpData } from "@hugeicons/core-free-icons";
import { ChevronUpIcon as ChevronUpIconData } from "@hugeicons/core-free-icons";
import { ChevronsLeftIcon as ChevronsLeftIconData } from "@hugeicons/core-free-icons";
import { ChevronsRightIcon as ChevronsRightIconData } from "@hugeicons/core-free-icons";
import { CircleAlert as CircleAlertData } from "@hugeicons/core-free-icons";
import { AlertCircleIcon as CircleAlertIconData } from "@hugeicons/core-free-icons";
import { CircleCheck as CircleCheckData } from "@hugeicons/core-free-icons";
import { CircleCheckIcon as CircleCheckIconData } from "@hugeicons/core-free-icons";
import { CircleDollarSignIcon as CircleDollarSignIconData } from "@hugeicons/core-free-icons";
import { CircleDot as CircleDotData } from "@hugeicons/core-free-icons";
import { CircleQuestionMarkIcon as CircleHelpData } from "@hugeicons/core-free-icons";
import { CircleQuestionMarkIcon as CircleHelpIconData } from "@hugeicons/core-free-icons";
import { CircleIcon as CircleIconData } from "@hugeicons/core-free-icons";
import { CircleStop as CircleStopData } from "@hugeicons/core-free-icons";
import { Clipboard as ClipboardData } from "@hugeicons/core-free-icons";
import { ClipboardCheck as ClipboardCheckData } from "@hugeicons/core-free-icons";
import { ClipboardIcon as ClipboardIconData } from "@hugeicons/core-free-icons";
import { ClipboardPasteIcon as ClipboardPasteIconData } from "@hugeicons/core-free-icons";
import { Clock as ClockData } from "@hugeicons/core-free-icons";
import { Clock03Icon as Clock3IconData } from "@hugeicons/core-free-icons";
import { ClockIcon as ClockIconData } from "@hugeicons/core-free-icons";
import { Cloud as CloudData } from "@hugeicons/core-free-icons";
import { CloudIcon as CloudIconData } from "@hugeicons/core-free-icons";
import { CodeIcon as Code2Data } from "@hugeicons/core-free-icons";
import { CodeIcon as Code2IconData } from "@hugeicons/core-free-icons";
import { CodeIcon as CodeIconData } from "@hugeicons/core-free-icons";
import { TableColumnsSplitIcon as ColumnsIconData } from "@hugeicons/core-free-icons";
import { Copy as CopyData } from "@hugeicons/core-free-icons";
import { CopyIcon as CopyIconData } from "@hugeicons/core-free-icons";
import { CornerDownLeft as CornerDownLeftData } from "@hugeicons/core-free-icons";
import { Cpu as CpuData } from "@hugeicons/core-free-icons";
import { CpuIcon as CpuIconData } from "@hugeicons/core-free-icons";
import { CreditCard as CreditCardData } from "@hugeicons/core-free-icons";
import { CreditCardIcon as CreditCardIconData } from "@hugeicons/core-free-icons";
import { DatabaseIcon as DatabaseIconData } from "@hugeicons/core-free-icons";
import { Download as DownloadData } from "@hugeicons/core-free-icons";
import { DownloadIcon as DownloadIconData } from "@hugeicons/core-free-icons";
import { Edit02Icon as Edit3Data } from "@hugeicons/core-free-icons";
import { EllipsisIcon as EllipsisIconData } from "@hugeicons/core-free-icons";
import { ExternalLink as ExternalLinkData } from "@hugeicons/core-free-icons";
import { ExternalLinkIcon as ExternalLinkIconData } from "@hugeicons/core-free-icons";
import { Eye as EyeData } from "@hugeicons/core-free-icons";
import { EyeIcon as EyeIconData } from "@hugeicons/core-free-icons";
import { EyeOff as EyeOffData } from "@hugeicons/core-free-icons";
import { EyeOffIcon as EyeOffIconData } from "@hugeicons/core-free-icons";
import { File as FileData } from "@hugeicons/core-free-icons";
import { FileArchive as FileArchiveData } from "@hugeicons/core-free-icons";
import { FileAudioIcon as FileAudioData } from "@hugeicons/core-free-icons";
import { FileCodeIcon as FileCode2Data } from "@hugeicons/core-free-icons";
import { FileCodeIcon as FileCodeIconData } from "@hugeicons/core-free-icons";
import { FileDiffIcon as FileDiffData } from "@hugeicons/core-free-icons";
import { FileIcon as FileIconData } from "@hugeicons/core-free-icons";
import { FileIcon as FileIconBaseData } from "@hugeicons/core-free-icons";
import { FileIcon as FileJsonIconData } from "@hugeicons/core-free-icons";
import { FilePenLineIcon as FilePenLineData } from "@hugeicons/core-free-icons";
import { FileQuestionMarkIcon as FileQuestionData } from "@hugeicons/core-free-icons";
import { FileText as FileTextData } from "@hugeicons/core-free-icons";
import { FileTextIcon as FileTextIconData } from "@hugeicons/core-free-icons";
import { FileVideoIcon as FileVideoData } from "@hugeicons/core-free-icons";
import { FilesIcon as FilesIconData } from "@hugeicons/core-free-icons";
import { FilmIcon as FilmIconData } from "@hugeicons/core-free-icons";
import { Filter as FilterData } from "@hugeicons/core-free-icons";
import { Folder as FolderData } from "@hugeicons/core-free-icons";
import { FolderArchiveIcon as FolderArchiveData } from "@hugeicons/core-free-icons";
import { FolderGitIcon as FolderGit2Data } from "@hugeicons/core-free-icons";
import { FolderIcon as FolderIconData } from "@hugeicons/core-free-icons";
import { FolderKanbanIcon as FolderKanbanData } from "@hugeicons/core-free-icons";
import { FolderOpen as FolderOpenData } from "@hugeicons/core-free-icons";
import { FolderOpenIcon as FolderOpenIconData } from "@hugeicons/core-free-icons";
import { FolderPlus as FolderPlusData } from "@hugeicons/core-free-icons";
import { FolderPlusIcon as FolderPlusIconData } from "@hugeicons/core-free-icons";
import { FolderTreeIcon as FolderTreeData } from "@hugeicons/core-free-icons";
import { GaugeIcon as GaugeData } from "@hugeicons/core-free-icons";
import { GitBranch as GitBranchData } from "@hugeicons/core-free-icons";
import { GitBranchIcon as GitBranchIconData } from "@hugeicons/core-free-icons";
import { GitCommitHorizontal as GitCommitHorizontalData } from "@hugeicons/core-free-icons";
import { GitFork as GitForkData } from "@hugeicons/core-free-icons";
import { GitGraph as GitGraphIconData } from "@hugeicons/core-free-icons";
import { GitPullRequest as GitPullRequestData } from "@hugeicons/core-free-icons";
import { Github as GithubData } from "@hugeicons/core-free-icons";
import { GithubIcon as GithubIconData } from "@hugeicons/core-free-icons";
import { Globe as GlobeData } from "@hugeicons/core-free-icons";
import { Globe02Icon as Globe2Data } from "@hugeicons/core-free-icons";
import { Grid3X3Icon as Grid3X3Data } from "@hugeicons/core-free-icons";
import { GripVertical as GripVerticalData } from "@hugeicons/core-free-icons";
import { GripVerticalIcon as GripVerticalIconData } from "@hugeicons/core-free-icons";
import { Hammer as HammerData } from "@hugeicons/core-free-icons";
import { Hand as HandData } from "@hugeicons/core-free-icons";
import { HardDrive as HardDriveData } from "@hugeicons/core-free-icons";
import { HardDriveIcon as HardDriveIconData } from "@hugeicons/core-free-icons";
import { HashIcon as HashIconData } from "@hugeicons/core-free-icons";
import { Home as HomeData } from "@hugeicons/core-free-icons";
import { HomeIcon as HomeIconData } from "@hugeicons/core-free-icons";
import { Hourglass as HourglassData } from "@hugeicons/core-free-icons";
import { House as HouseData } from "@hugeicons/core-free-icons";
import { Image as ImageData } from "@hugeicons/core-free-icons";
import { ImageIcon as ImageIconData } from "@hugeicons/core-free-icons";
import { Info as InfoData } from "@hugeicons/core-free-icons";
import { InfoIcon as InfoIconData } from "@hugeicons/core-free-icons";
import { Kanban as KanbanData } from "@hugeicons/core-free-icons";
import { KeyRound as KeyRoundData } from "@hugeicons/core-free-icons";
import { KeyRoundIcon as KeyRoundIconData } from "@hugeicons/core-free-icons";
import { KeyboardIcon as KeyboardIconData } from "@hugeicons/core-free-icons";
import { Layers as LayersData } from "@hugeicons/core-free-icons";
import { LayersIcon as LayersIconData } from "@hugeicons/core-free-icons";
import { LayoutGrid as LayoutGridData } from "@hugeicons/core-free-icons";
import { LayoutGridIcon as LayoutGridIconData } from "@hugeicons/core-free-icons";
import { Link2 as Link2Data } from "@hugeicons/core-free-icons";
import { LinkIcon as LinkIconData } from "@hugeicons/core-free-icons";
import { List as ListData } from "@hugeicons/core-free-icons";
import { ListIcon as ListIconData } from "@hugeicons/core-free-icons";
import { ListTodo as ListTodoData } from "@hugeicons/core-free-icons";
import { ListTree as ListTreeData } from "@hugeicons/core-free-icons";
import { LoaderIcon as Loader2IconData } from "@hugeicons/core-free-icons";
import { LoaderCircle as LoaderCircleData } from "@hugeicons/core-free-icons";
import { LoaderCircleIcon as LoaderCircleIconData } from "@hugeicons/core-free-icons";
import { LoaderIcon as LoaderIconData } from "@hugeicons/core-free-icons";
import { LockIcon as LockIconData } from "@hugeicons/core-free-icons";
import { LogOut as LogOutData } from "@hugeicons/core-free-icons";
import { LogOutIcon as LogOutIconData } from "@hugeicons/core-free-icons";
import { MailIcon as MailIconData } from "@hugeicons/core-free-icons";
import { MapPinIcon as MapPinIconData } from "@hugeicons/core-free-icons";
import { Maximize as MaximizeData } from "@hugeicons/core-free-icons";
import { Maximize2 as Maximize2Data } from "@hugeicons/core-free-icons";
import { MaximizeIcon as MaximizeIconData } from "@hugeicons/core-free-icons";
import { MemoryStick as MemoryStickData } from "@hugeicons/core-free-icons";
import { MessageCircle as MessageCircleData } from "@hugeicons/core-free-icons";
import { MessageCircleIcon as MessageCircleIconData } from "@hugeicons/core-free-icons";
import { MessageSquare as MessageSquareData } from "@hugeicons/core-free-icons";
import { MessageSquareIcon as MessageSquareIconData } from "@hugeicons/core-free-icons";
import { MessageSquarePlus as MessageSquarePlusData } from "@hugeicons/core-free-icons";
import { MicIcon as MicIconData } from "@hugeicons/core-free-icons";
import { MicOffIcon as MicOffIconData } from "@hugeicons/core-free-icons";
import { Minimize2 as Minimize2Data } from "@hugeicons/core-free-icons";
import { Minus as MinusData } from "@hugeicons/core-free-icons";
import { MinusIcon as MinusIconData } from "@hugeicons/core-free-icons";
import { Monitor as MonitorData } from "@hugeicons/core-free-icons";
import { MonitorCheck as MonitorCheckData } from "@hugeicons/core-free-icons";
import { MonitorCog as MonitorCogData } from "@hugeicons/core-free-icons";
import { MonitorIcon as MonitorIconData } from "@hugeicons/core-free-icons";
import { MoonIcon as MoonIconData } from "@hugeicons/core-free-icons";
import { MoreHorizontal as MoreHorizontalData } from "@hugeicons/core-free-icons";
import { MoreHorizontalIcon as MoreHorizontalIconData } from "@hugeicons/core-free-icons";
import { MousePointer as MousePointerData } from "@hugeicons/core-free-icons";
import { MousePointer2 as MousePointer2Data } from "@hugeicons/core-free-icons";
import { MusicIcon as MusicIconData } from "@hugeicons/core-free-icons";
import { OctagonXIcon as OctagonXIconData } from "@hugeicons/core-free-icons";
import { Palette as PaletteData } from "@hugeicons/core-free-icons";
import { PaletteIcon as PaletteIconData } from "@hugeicons/core-free-icons";
import { PanelLeft as PanelLeftData } from "@hugeicons/core-free-icons";
import { PanelLeftCloseIcon as PanelLeftCloseIconData } from "@hugeicons/core-free-icons";
import { PanelLeftIcon as PanelLeftIconData } from "@hugeicons/core-free-icons";
import { PanelLeftOpenIcon as PanelLeftOpenIconData } from "@hugeicons/core-free-icons";
import { PanelRightCloseIcon as PanelRightCloseIconData } from "@hugeicons/core-free-icons";
import { PanelRightOpen as PanelRightOpenData } from "@hugeicons/core-free-icons";
import { PanelRightOpenIcon as PanelRightOpenIconData } from "@hugeicons/core-free-icons";
import { PanelsTopLeftIcon as PanelsTopLeftData } from "@hugeicons/core-free-icons";
import { Paperclip as PaperclipData } from "@hugeicons/core-free-icons";
import { PaperclipIcon as PaperclipIconData } from "@hugeicons/core-free-icons";
import { PencilIcon as PencilIconData } from "@hugeicons/core-free-icons";
import { Pi as PiData } from "@hugeicons/core-free-icons";
import { PinIcon as PinIconData } from "@hugeicons/core-free-icons";
import { PinOffIcon as PinOffIconData } from "@hugeicons/core-free-icons";
import { Play as PlayData } from "@hugeicons/core-free-icons";
import { PlayIcon as PlayIconData } from "@hugeicons/core-free-icons";
import { Plug as PlugData } from "@hugeicons/core-free-icons";
import { Plus as PlusData } from "@hugeicons/core-free-icons";
import { AddCircleIcon as PlusCircleIconData } from "@hugeicons/core-free-icons";
import { PlusIcon as PlusIconData } from "@hugeicons/core-free-icons";
import { PowerIcon as PowerIconData } from "@hugeicons/core-free-icons";
import { PuzzleIcon as PuzzleIconData } from "@hugeicons/core-free-icons";
import { Radio as RadioData } from "@hugeicons/core-free-icons";
import { RadioIcon as RadioIconData } from "@hugeicons/core-free-icons";
import { ReceiptTextIcon as ReceiptTextIconData } from "@hugeicons/core-free-icons";
import { RefreshCcwIcon as RefreshCcwIconData } from "@hugeicons/core-free-icons";
import { RefreshCw as RefreshCwData } from "@hugeicons/core-free-icons";
import { RefreshCwIcon as RefreshCwIconData } from "@hugeicons/core-free-icons";
import { RotateCcw as RotateCcwData } from "@hugeicons/core-free-icons";
import { RotateCcwIcon as RotateCcwIconData } from "@hugeicons/core-free-icons";
import { RowsThreeIcon as Rows2IconData } from "@hugeicons/core-free-icons";
import { Save as SaveData } from "@hugeicons/core-free-icons";
import { SaveIcon as SaveIconData } from "@hugeicons/core-free-icons";
import { ScrollText as ScrollTextData } from "@hugeicons/core-free-icons";
import { Search as SearchData } from "@hugeicons/core-free-icons";
import { SearchIcon as SearchIconData } from "@hugeicons/core-free-icons";
import { SendIcon as SendIconData } from "@hugeicons/core-free-icons";
import { Server as ServerData } from "@hugeicons/core-free-icons";
import { ServerIcon as ServerIconData } from "@hugeicons/core-free-icons";
import { Settings as SettingsData } from "@hugeicons/core-free-icons";
import { Settings02Icon as Settings2IconData } from "@hugeicons/core-free-icons";
import { SettingsIcon as SettingsIconData } from "@hugeicons/core-free-icons";
import { ShieldAlert as ShieldAlertData } from "@hugeicons/core-free-icons";
import { ShieldAlertIcon as ShieldAlertIconData } from "@hugeicons/core-free-icons";
import { ShieldCheck as ShieldCheckData } from "@hugeicons/core-free-icons";
import { ShieldCheckIcon as ShieldCheckIconData } from "@hugeicons/core-free-icons";
import { ShieldIcon as ShieldIconData } from "@hugeicons/core-free-icons";
import { SlackIcon as SlackIconData } from "@hugeicons/core-free-icons";
import { SlidersHorizontalIcon as SlidersHorizontalIconData } from "@hugeicons/core-free-icons";
import { SmartphoneIcon as SmartphoneIconData } from "@hugeicons/core-free-icons";
import { Sparkles as SparklesData } from "@hugeicons/core-free-icons";
import { SparklesIcon as SparklesIconData } from "@hugeicons/core-free-icons";
import { Square as SquareData } from "@hugeicons/core-free-icons";
import { SquareIcon as SquareIconData } from "@hugeicons/core-free-icons";
import { SquarePen as SquarePenData } from "@hugeicons/core-free-icons";
import { SquareTerminalIcon as SquareTerminalData } from "@hugeicons/core-free-icons";
import { SquareTerminalIcon as SquareTerminalIconData } from "@hugeicons/core-free-icons";
import { StarIcon as StarIconData } from "@hugeicons/core-free-icons";
import { Terminal as TerminalData } from "@hugeicons/core-free-icons";
import { TerminalIcon as TerminalIconData } from "@hugeicons/core-free-icons";
import { TextSelect as TextSelectData } from "@hugeicons/core-free-icons";
import { Trash2 as Trash2Data } from "@hugeicons/core-free-icons";
import { Delete02Icon as Trash2IconData } from "@hugeicons/core-free-icons";
import { TrashIcon as TrashIconData } from "@hugeicons/core-free-icons";
import { TriangleAlertIcon as TriangleAlertData } from "@hugeicons/core-free-icons";
import { TriangleAlertIcon as TriangleAlertIconData } from "@hugeicons/core-free-icons";
import { Type as TypeData } from "@hugeicons/core-free-icons";
import { Upload as UploadData } from "@hugeicons/core-free-icons";
import { UploadIcon as UploadIconData } from "@hugeicons/core-free-icons";
import { UserIcon as UserIconData } from "@hugeicons/core-free-icons";
import { UserRound as UserRoundData } from "@hugeicons/core-free-icons";
import { UsersIcon as UsersIconData } from "@hugeicons/core-free-icons";
import { VolumeHighIcon as Volume2IconData } from "@hugeicons/core-free-icons";
import { WifiIcon as WifiIconData } from "@hugeicons/core-free-icons";
import { TextWrapIcon as WrapTextData } from "@hugeicons/core-free-icons";
import { Wrench as WrenchData } from "@hugeicons/core-free-icons";
import { WrenchIcon as WrenchIconData } from "@hugeicons/core-free-icons";
import { X as XData } from "@hugeicons/core-free-icons";
import { CancelCircleIcon as XCircleIconData } from "@hugeicons/core-free-icons";
import { XIcon as XIconData } from "@hugeicons/core-free-icons";
import { Zap as ZapData } from "@hugeicons/core-free-icons";
import { ArrowExpand01Icon as ArrowExpand01Data } from "@hugeicons/core-free-icons";

export type LucideProps = Omit<ComponentProps<typeof HugeiconsIcon>, "icon">;
export type LucideIcon = ComponentType<LucideProps>;

function createIcon(icon: IconSvgElement): LucideIcon {
  return function HugeIcon({ size = 24, strokeWidth = 1.5, ...props }: LucideProps) {
    return <HugeiconsIcon icon={icon} size={size} strokeWidth={strokeWidth} {...props} />;
  };
}

const DiscordIconData: IconSvgElement = [[
  "path",
  {
    d: "M20.317 4.37a19.79 19.79 0 0 0-4.885-1.515 14.9 14.9 0 0 0-.626 1.284 18.27 18.27 0 0 0-5.61 0 12.64 12.64 0 0 0-.634-1.284A19.74 19.74 0 0 0 3.678 4.37C.59 8.965-.246 13.45.172 17.886a19.9 19.9 0 0 0 5.993 3.028 14.3 14.3 0 0 0 1.272-1.67 12.9 12.9 0 0 1-2.003-.957c.168-.122.33-.247.488-.373 3.862 1.787 8.05 1.787 11.866 0 .159.13.324.256.487.373-.635.375-1.305.695-2.002.957.372.464.785.987 1.271 1.67a19.85 19.85 0 0 0 6.002-3.028c.493-5.197-.844-9.708-3.549-13.697ZM8.02 15.331c-1.183 0-2.157-1.086-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.095 2.157 2.419 0 1.333-.955 2.419-2.157 2.419Zm7.975 0c-1.183 0-2.157-1.086-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.095 2.157 2.419 0 1.333-.946 2.419-2.157 2.419Z",
    fill: "currentColor",
    stroke: "none",
    key: "discord",
  },
]];

export const Activity: LucideIcon = createIcon(ActivityData);
export const ActivityIcon: LucideIcon = createIcon(ActivityIconData);
export const AlertCircle: LucideIcon = createIcon(AlertCircleData);
export const AlertCircleIcon: LucideIcon = createIcon(AlertCircleIconData);
export const AlertTriangle: LucideIcon = createIcon(AlertTriangleData);
export const AlertTriangleIcon: LucideIcon = createIcon(AlertTriangleIconData);
export const AppWindow: LucideIcon = createIcon(AppWindowData);
export const AppWindowIcon: LucideIcon = createIcon(AppWindowIconData);
export const Archive: LucideIcon = createIcon(ArchiveData);
export const ArchiveRestore: LucideIcon = createIcon(ArchiveRestoreData);
export const ArrowDown: LucideIcon = createIcon(ArrowDownData);
export const ArrowDownIcon: LucideIcon = createIcon(ArrowDownIconData);
export const ArrowLeft: LucideIcon = createIcon(ArrowLeftData);
export const ArrowLeftIcon: LucideIcon = createIcon(ArrowLeftIconData);
export const ArrowRight: LucideIcon = createIcon(ArrowRightData);
export const ArrowUp: LucideIcon = createIcon(ArrowUpData);
export const ArrowUpCircleIcon: LucideIcon = createIcon(ArrowUpCircleIconData);
export const ArrowUpIcon: LucideIcon = createIcon(ArrowUpIconData);
export const ArrowUpRightIcon: LucideIcon = createIcon(ArrowUpRightIconData);
export const AudioLinesIcon: LucideIcon = createIcon(AudioLinesIconData);
export const AudioWaveformIcon: LucideIcon = createIcon(AudioWaveformIconData);
export const BatteryFullIcon: LucideIcon = createIcon(BatteryFullIconData);
export const BatteryMediumIcon: LucideIcon = createIcon(BatteryMediumIconData);
export const Bell: LucideIcon = createIcon(BellData);
export const Blocks: LucideIcon = createIcon(BlocksData);
export const Bot: LucideIcon = createIcon(BotData);
export const BotIcon: LucideIcon = createIcon(BotIconData);
export const Box: LucideIcon = createIcon(BoxData);
export const BoxIcon: LucideIcon = createIcon(BoxIconData);
export const Braces: LucideIcon = createIcon(BracesData);
export const Brain: LucideIcon = createIcon(BrainData);
export const BrushIcon: LucideIcon = createIcon(BrushIconData);
export const Bug: LucideIcon = createIcon(BugData);
export const CableIcon: LucideIcon = createIcon(CableIconData);
export const CalendarIcon: LucideIcon = createIcon(CalendarIconData);
export const Check: LucideIcon = createIcon(CheckData);
export const CheckCircle2: LucideIcon = createIcon(CheckCircle2Data);
export const CheckCircle2Icon: LucideIcon = createIcon(CheckCircle2IconData);
export const CheckCircleIcon: LucideIcon = createIcon(CheckCircleIconData);
export const CheckIcon: LucideIcon = createIcon(CheckIconData);
export const ChevronDown: LucideIcon = createIcon(ChevronDownData);
export const ChevronDownIcon: LucideIcon = createIcon(ChevronDownIconData);
export const ChevronLeft: LucideIcon = createIcon(ChevronLeftData);
export const ChevronLeftIcon: LucideIcon = createIcon(ChevronLeftIconData);
export const ChevronRight: LucideIcon = createIcon(ChevronRightData);
export const ChevronRightIcon: LucideIcon = createIcon(ChevronRightIconData);
export const ChevronUp: LucideIcon = createIcon(ChevronUpData);
export const ChevronUpIcon: LucideIcon = createIcon(ChevronUpIconData);
export const ChevronsLeftIcon: LucideIcon = createIcon(ChevronsLeftIconData);
export const ChevronsRightIcon: LucideIcon = createIcon(ChevronsRightIconData);
export const CircleAlert: LucideIcon = createIcon(CircleAlertData);
export const CircleAlertIcon: LucideIcon = createIcon(CircleAlertIconData);
export const CircleCheck: LucideIcon = createIcon(CircleCheckData);
export const CircleCheckIcon: LucideIcon = createIcon(CircleCheckIconData);
export const CircleDollarSignIcon: LucideIcon = createIcon(CircleDollarSignIconData);
export const CircleDot: LucideIcon = createIcon(CircleDotData);
export const CircleHelp: LucideIcon = createIcon(CircleHelpData);
export const CircleHelpIcon: LucideIcon = createIcon(CircleHelpIconData);
export const CircleIcon: LucideIcon = createIcon(CircleIconData);
export const CircleStop: LucideIcon = createIcon(CircleStopData);
export const Clipboard: LucideIcon = createIcon(ClipboardData);
export const ClipboardCheck: LucideIcon = createIcon(ClipboardCheckData);
export const ClipboardIcon: LucideIcon = createIcon(ClipboardIconData);
export const ClipboardPasteIcon: LucideIcon = createIcon(ClipboardPasteIconData);
export const Clock: LucideIcon = createIcon(ClockData);
export const Clock3Icon: LucideIcon = createIcon(Clock3IconData);
export const ClockIcon: LucideIcon = createIcon(ClockIconData);
export const Cloud: LucideIcon = createIcon(CloudData);
export const CloudIcon: LucideIcon = createIcon(CloudIconData);
export const Code2: LucideIcon = createIcon(Code2Data);
export const Code2Icon: LucideIcon = createIcon(Code2IconData);
export const CodeIcon: LucideIcon = createIcon(CodeIconData);
export const ColumnsIcon: LucideIcon = createIcon(ColumnsIconData);
export const Copy: LucideIcon = createIcon(CopyData);
export const CopyIcon: LucideIcon = createIcon(CopyIconData);
export const CornerDownLeft: LucideIcon = createIcon(CornerDownLeftData);
export const Cpu: LucideIcon = createIcon(CpuData);
export const CpuIcon: LucideIcon = createIcon(CpuIconData);
export const CreditCard: LucideIcon = createIcon(CreditCardData);
export const CreditCardIcon: LucideIcon = createIcon(CreditCardIconData);
export const DatabaseIcon: LucideIcon = createIcon(DatabaseIconData);
export const DiscordIcon: LucideIcon = createIcon(DiscordIconData);
export const Download: LucideIcon = createIcon(DownloadData);
export const DownloadIcon: LucideIcon = createIcon(DownloadIconData);
export const Edit3: LucideIcon = createIcon(Edit3Data);
export const EllipsisIcon: LucideIcon = createIcon(EllipsisIconData);
export const ExternalLink: LucideIcon = createIcon(ExternalLinkData);
export const ExternalLinkIcon: LucideIcon = createIcon(ExternalLinkIconData);
export const Eye: LucideIcon = createIcon(EyeData);
export const EyeIcon: LucideIcon = createIcon(EyeIconData);
export const EyeOff: LucideIcon = createIcon(EyeOffData);
export const EyeOffIcon: LucideIcon = createIcon(EyeOffIconData);
export const File: LucideIcon = createIcon(FileData);
export const FileArchive: LucideIcon = createIcon(FileArchiveData);
export const FileAudio: LucideIcon = createIcon(FileAudioData);
export const FileCode2: LucideIcon = createIcon(FileCode2Data);
export const FileCodeIcon: LucideIcon = createIcon(FileCodeIconData);
export const FileDiff: LucideIcon = createIcon(FileDiffData);
export const FileIcon: LucideIcon = createIcon(FileIconData);
export const FileIconBase: LucideIcon = createIcon(FileIconBaseData);
export const FileJsonIcon: LucideIcon = createIcon(FileJsonIconData);
export const FilePenLine: LucideIcon = createIcon(FilePenLineData);
export const FileQuestion: LucideIcon = createIcon(FileQuestionData);
export const FileText: LucideIcon = createIcon(FileTextData);
export const FileTextIcon: LucideIcon = createIcon(FileTextIconData);
export const FileVideo: LucideIcon = createIcon(FileVideoData);
export const FilesIcon: LucideIcon = createIcon(FilesIconData);
export const FilmIcon: LucideIcon = createIcon(FilmIconData);
export const Filter: LucideIcon = createIcon(FilterData);
export const Folder: LucideIcon = createIcon(FolderData);
export const FolderArchive: LucideIcon = createIcon(FolderArchiveData);
export const FolderGit2: LucideIcon = createIcon(FolderGit2Data);
export const FolderIcon: LucideIcon = createIcon(FolderIconData);
export const FolderKanban: LucideIcon = createIcon(FolderKanbanData);
export const FolderOpen: LucideIcon = createIcon(FolderOpenData);
export const FolderOpenIcon: LucideIcon = createIcon(FolderOpenIconData);
export const FolderPlus: LucideIcon = createIcon(FolderPlusData);
export const FolderPlusIcon: LucideIcon = createIcon(FolderPlusIconData);
export const FolderTree: LucideIcon = createIcon(FolderTreeData);
export const Gauge: LucideIcon = createIcon(GaugeData);
export const GitBranch: LucideIcon = createIcon(GitBranchData);
export const GitBranchIcon: LucideIcon = createIcon(GitBranchIconData);
export const GitCommitHorizontal: LucideIcon = createIcon(GitCommitHorizontalData);
export const GitFork: LucideIcon = createIcon(GitForkData);
export const GitGraphIcon: LucideIcon = createIcon(GitGraphIconData);
export const GitGraph = GitGraphIcon;
export const GitPullRequest: LucideIcon = createIcon(GitPullRequestData);
export const Github: LucideIcon = createIcon(GithubData);
export const GithubIcon: LucideIcon = createIcon(GithubIconData);
export const Globe: LucideIcon = createIcon(GlobeData);
export const Globe2: LucideIcon = createIcon(Globe2Data);
export const Grid3X3: LucideIcon = createIcon(Grid3X3Data);
export const GripVertical: LucideIcon = createIcon(GripVerticalData);
export const GripVerticalIcon: LucideIcon = createIcon(GripVerticalIconData);
export const Hammer: LucideIcon = createIcon(HammerData);
export const Hand: LucideIcon = createIcon(HandData);
export const HardDrive: LucideIcon = createIcon(HardDriveData);
export const HardDriveIcon: LucideIcon = createIcon(HardDriveIconData);
export const HashIcon: LucideIcon = createIcon(HashIconData);
export const Home: LucideIcon = createIcon(HomeData);
export const HomeIcon: LucideIcon = createIcon(HomeIconData);
export const Hourglass: LucideIcon = createIcon(HourglassData);
export const House: LucideIcon = createIcon(HouseData);
export const Image: LucideIcon = createIcon(ImageData);
export const ImageIcon: LucideIcon = createIcon(ImageIconData);
export const Info: LucideIcon = createIcon(InfoData);
export const InfoIcon: LucideIcon = createIcon(InfoIconData);
export const Kanban: LucideIcon = createIcon(KanbanData);
export const KeyRound: LucideIcon = createIcon(KeyRoundData);
export const KeyRoundIcon: LucideIcon = createIcon(KeyRoundIconData);
export const KeyboardIcon: LucideIcon = createIcon(KeyboardIconData);
export const Layers: LucideIcon = createIcon(LayersData);
export const LayersIcon: LucideIcon = createIcon(LayersIconData);
export const LayoutGrid: LucideIcon = createIcon(LayoutGridData);
export const LayoutGridIcon: LucideIcon = createIcon(LayoutGridIconData);
export const Link2: LucideIcon = createIcon(Link2Data);
export const LinkIcon: LucideIcon = createIcon(LinkIconData);
export const List: LucideIcon = createIcon(ListData);
export const ListIcon: LucideIcon = createIcon(ListIconData);
export const ListTodo: LucideIcon = createIcon(ListTodoData);
export const ListTree: LucideIcon = createIcon(ListTreeData);
export const Loader2Icon: LucideIcon = createIcon(Loader2IconData);
export const LoaderCircle: LucideIcon = createIcon(LoaderCircleData);
export const LoaderCircleIcon: LucideIcon = createIcon(LoaderCircleIconData);
export const LoaderIcon: LucideIcon = createIcon(LoaderIconData);
export const LockIcon: LucideIcon = createIcon(LockIconData);
export const LogOut: LucideIcon = createIcon(LogOutData);
export const LogOutIcon: LucideIcon = createIcon(LogOutIconData);
export const MailIcon: LucideIcon = createIcon(MailIconData);
export const MapPinIcon: LucideIcon = createIcon(MapPinIconData);
export const Maximize: LucideIcon = createIcon(MaximizeData);
export const Maximize2: LucideIcon = createIcon(Maximize2Data);
export const MaximizeIcon: LucideIcon = createIcon(MaximizeIconData);
export const MemoryStick: LucideIcon = createIcon(MemoryStickData);
export const MessageCircle: LucideIcon = createIcon(MessageCircleData);
export const MessageCircleIcon: LucideIcon = createIcon(MessageCircleIconData);
export const MessageSquare: LucideIcon = createIcon(MessageSquareData);
export const MessageSquareIcon: LucideIcon = createIcon(MessageSquareIconData);
export const MessageSquarePlus: LucideIcon = createIcon(MessageSquarePlusData);
export const MicIcon: LucideIcon = createIcon(MicIconData);
export const MicOffIcon: LucideIcon = createIcon(MicOffIconData);
export const Minimize2: LucideIcon = createIcon(Minimize2Data);
export const Minus: LucideIcon = createIcon(MinusData);
export const MinusIcon: LucideIcon = createIcon(MinusIconData);
export const Monitor: LucideIcon = createIcon(MonitorData);
export const MonitorCheck: LucideIcon = createIcon(MonitorCheckData);
export const MonitorCog: LucideIcon = createIcon(MonitorCogData);
export const MonitorIcon: LucideIcon = createIcon(MonitorIconData);
export const MoonIcon: LucideIcon = createIcon(MoonIconData);
export const MoreHorizontal: LucideIcon = createIcon(MoreHorizontalData);
export const MoreHorizontalIcon: LucideIcon = createIcon(MoreHorizontalIconData);
export const MousePointer: LucideIcon = createIcon(MousePointerData);
export const MousePointer2: LucideIcon = createIcon(MousePointer2Data);
export const MusicIcon: LucideIcon = createIcon(MusicIconData);
export const OctagonXIcon: LucideIcon = createIcon(OctagonXIconData);
export const Palette: LucideIcon = createIcon(PaletteData);
export const PaletteIcon: LucideIcon = createIcon(PaletteIconData);
export const PanelLeft: LucideIcon = createIcon(PanelLeftData);
export const PanelLeftCloseIcon: LucideIcon = createIcon(PanelLeftCloseIconData);
export const PanelLeftIcon: LucideIcon = createIcon(PanelLeftIconData);
export const PanelLeftOpenIcon: LucideIcon = createIcon(PanelLeftOpenIconData);
export const PanelRightCloseIcon: LucideIcon = createIcon(PanelRightCloseIconData);
export const PanelRightOpen: LucideIcon = createIcon(PanelRightOpenData);
export const PanelRightOpenIcon: LucideIcon = createIcon(PanelRightOpenIconData);
export const PanelsTopLeft: LucideIcon = createIcon(PanelsTopLeftData);
export const Paperclip: LucideIcon = createIcon(PaperclipData);
export const PaperclipIcon: LucideIcon = createIcon(PaperclipIconData);
export const PencilIcon: LucideIcon = createIcon(PencilIconData);
export const Pi: LucideIcon = createIcon(PiData);
export const PinIcon: LucideIcon = createIcon(PinIconData);
export const PinOffIcon: LucideIcon = createIcon(PinOffIconData);
export const Play: LucideIcon = createIcon(PlayData);
export const PlayIcon: LucideIcon = createIcon(PlayIconData);
export const Plug: LucideIcon = createIcon(PlugData);
export const Plus: LucideIcon = createIcon(PlusData);
export const PlusCircleIcon: LucideIcon = createIcon(PlusCircleIconData);
export const PlusIcon: LucideIcon = createIcon(PlusIconData);
export const PowerIcon: LucideIcon = createIcon(PowerIconData);
export const PuzzleIcon: LucideIcon = createIcon(PuzzleIconData);
export const Radio: LucideIcon = createIcon(RadioData);
export const RadioIcon: LucideIcon = createIcon(RadioIconData);
export const ReceiptTextIcon: LucideIcon = createIcon(ReceiptTextIconData);
export const RefreshCcwIcon: LucideIcon = createIcon(RefreshCcwIconData);
export const RefreshCw: LucideIcon = createIcon(RefreshCwData);
export const RefreshCwIcon: LucideIcon = createIcon(RefreshCwIconData);
export const RotateCcw: LucideIcon = createIcon(RotateCcwData);
export const RotateCcwIcon: LucideIcon = createIcon(RotateCcwIconData);
export const Rows2Icon: LucideIcon = createIcon(Rows2IconData);
export const Save: LucideIcon = createIcon(SaveData);
export const SaveIcon: LucideIcon = createIcon(SaveIconData);
export const ScrollText: LucideIcon = createIcon(ScrollTextData);
export const Search: LucideIcon = createIcon(SearchData);
export const SearchIcon: LucideIcon = createIcon(SearchIconData);
export const SendIcon: LucideIcon = createIcon(SendIconData);
export const Server: LucideIcon = createIcon(ServerData);
export const ServerIcon: LucideIcon = createIcon(ServerIconData);
export const Settings: LucideIcon = createIcon(SettingsData);
export const Settings2Icon: LucideIcon = createIcon(Settings2IconData);
export const SettingsIcon: LucideIcon = createIcon(SettingsIconData);
export const ShieldAlert: LucideIcon = createIcon(ShieldAlertData);
export const ShieldAlertIcon: LucideIcon = createIcon(ShieldAlertIconData);
export const ShieldCheck: LucideIcon = createIcon(ShieldCheckData);
export const ShieldCheckIcon: LucideIcon = createIcon(ShieldCheckIconData);
export const ShieldIcon: LucideIcon = createIcon(ShieldIconData);
export const SlackIcon: LucideIcon = createIcon(SlackIconData);
export const SlidersHorizontalIcon: LucideIcon = createIcon(SlidersHorizontalIconData);
export const SmartphoneIcon: LucideIcon = createIcon(SmartphoneIconData);
export const Sparkles: LucideIcon = createIcon(SparklesData);
export const SparklesIcon: LucideIcon = createIcon(SparklesIconData);
export const Square: LucideIcon = createIcon(SquareData);
export const SquareIcon: LucideIcon = createIcon(SquareIconData);
export const SquarePen: LucideIcon = createIcon(SquarePenData);
export const SquareTerminal: LucideIcon = createIcon(SquareTerminalData);
export const SquareTerminalIcon: LucideIcon = createIcon(SquareTerminalIconData);
export const StarIcon: LucideIcon = createIcon(StarIconData);
export const Terminal: LucideIcon = createIcon(TerminalData);
export const TerminalIcon: LucideIcon = createIcon(TerminalIconData);
export const TextSelect: LucideIcon = createIcon(TextSelectData);
export const Trash2: LucideIcon = createIcon(Trash2Data);
export const Trash2Icon: LucideIcon = createIcon(Trash2IconData);
export const TrashIcon: LucideIcon = createIcon(TrashIconData);
export const TriangleAlert: LucideIcon = createIcon(TriangleAlertData);
export const TriangleAlertIcon: LucideIcon = createIcon(TriangleAlertIconData);
export const Type: LucideIcon = createIcon(TypeData);
export const Upload: LucideIcon = createIcon(UploadData);
export const UploadIcon: LucideIcon = createIcon(UploadIconData);
export const UserIcon: LucideIcon = createIcon(UserIconData);
export const UserRound: LucideIcon = createIcon(UserRoundData);
export const UsersIcon: LucideIcon = createIcon(UsersIconData);
export const Volume2Icon: LucideIcon = createIcon(Volume2IconData);
export const WifiIcon: LucideIcon = createIcon(WifiIconData);
export const WrapText: LucideIcon = createIcon(WrapTextData);
export const Wrench: LucideIcon = createIcon(WrenchData);
export const WrenchIcon: LucideIcon = createIcon(WrenchIconData);
export const X: LucideIcon = createIcon(XData);
export const XCircleIcon: LucideIcon = createIcon(XCircleIconData);
export const XIcon: LucideIcon = createIcon(XIconData);
export const Zap: LucideIcon = createIcon(ZapData);
export const ArrowExpand01: LucideIcon = createIcon(ArrowExpand01Data);
export const Notebook: LucideIcon = createIcon(Note01Data);
