import {describe,expect,it,vi} from 'vitest';
import * as api from '../../scripts/ci/dedicated-api.mjs';
const url='https://api.github.com/repos/HamedMP/matrix-os/pulls/2454';
const response=(status:number,etag:string,data:unknown={head:{sha:'old'}},extra={})=>({status,headers:{etag,...extra},url,data});
function fixture(){const get=vi.fn(async(_args:Record<string,unknown>)=>response(200,'"one"'));const source={rest:{pulls:{get},checks:{update:vi.fn()}}};const conditional=api.createConditionalGithub(source,{authenticationContext:'run123:attempt1',maxEntries:2,maxBytes:1024,ttlMilliseconds:1000});return{...conditional,get,source};}
describe('authenticated bounded conditional GitHub API reads',()=>{
 it('uses authenticated 304 only for the matching representation, then sees changed 200 data',async()=>{const f=fixture();const args={owner:'HamedMP',repo:'matrix-os',pull_number:2454,request:{timeout:10000}};await f.github.rest.pulls.get(args);f.get.mockResolvedValueOnce(response(304,'"one"',undefined));expect((await f.github.rest.pulls.get(args)).data).toEqual({head:{sha:'old'}});expect(f.get).toHaveBeenLastCalledWith(expect.objectContaining({headers:{'if-none-match':'"one"'}}));f.get.mockResolvedValueOnce(response(200,'"two"',{head:{sha:'new'}}));expect((await f.github.rest.pulls.get(args)).data).toEqual({head:{sha:'new'}});expect(f.metrics()).toMatchObject({conditionalHits:1});});
 it.each(['url','tag','empty','auth'])('rejects unbound %s 304 and never returns stale data',async kind=>{const f=fixture(),args={owner:'HamedMP',repo:'matrix-os',pull_number:2454};if(kind!=='empty'&&kind!=='auth')await f.github.rest.pulls.get(args);f.get.mockResolvedValueOnce({...response(304,kind==='tag'?'"two"':'"one"',undefined),url:kind==='url'?url+'?different=1':url});const client=kind==='auth'?api.createConditionalGithub(f.source,{authenticationContext:'different-token-scope'}).github:f.github;await expect(client.rest.pulls.get(args)).rejects.toThrow(/304|cache|representation/);});
 it('propagates denial and Octokit 304 responses without a stale-error fallback',async()=>{const f=fixture(),args={pull_number:2454};await f.github.rest.pulls.get(args);f.get.mockRejectedValueOnce(Object.assign(new Error('Not modified'),{status:304,response:response(304,'"one"',undefined)}));await expect(f.github.rest.pulls.get(args)).resolves.toHaveProperty('data.head.sha','old');f.get.mockRejectedValueOnce(Object.assign(new Error('API denied'),{status:403}));await expect(f.github.rest.pulls.get(args)).rejects.toThrow('API denied');});
 it('keeps first post-lock grant unconditional, expires cache and never conditionally writes checks',async()=>{const f=fixture(),args={pull_number:2454};await f.github.rest.pulls.get(args);await f.runUnconditional(()=>f.github.rest.pulls.get(args));expect(f.get.mock.calls.at(-1)![0].headers).toBeUndefined();await f.github.rest.checks.update({check_run_id:10});expect(f.source.rest.checks.update).toHaveBeenCalledWith({check_run_id:10});});
 it('does not retain oversized data or reuse a mutated caller response',async()=>{const f=fixture(),args={pull_number:2454};const first=await f.github.rest.pulls.get(args);(first.data as any).head.sha='mutated';f.get.mockResolvedValueOnce(response(304,'"one"',undefined));expect((await f.github.rest.pulls.get(args)).data).toEqual({head:{sha:'old'}});f.get.mockResolvedValueOnce(response(200,'"huge"','x'.repeat(2000)));await f.github.rest.pulls.get(args);f.get.mockResolvedValueOnce(response(304,'"huge"',undefined));await expect(f.github.rest.pulls.get(args)).rejects.toThrow();});
 it('honors a bounded poll interval and exposes only aggregate public quota metrics',async()=>{vi.useFakeTimers();try{const f=fixture(),args={pull_number:2454};f.get.mockResolvedValueOnce(response(200,'"one"',{}, {'x-poll-interval':'2','x-ratelimit-remaining':'900'}));await f.github.rest.pulls.get(args);const pending=f.github.rest.pulls.get(args);await vi.advanceTimersByTimeAsync(1999);expect(f.get).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(1);await pending;expect(f.metrics()).toMatchObject({maximumPollIntervalSeconds:2,minimumRemaining:900});}finally{vi.useRealTimers();}});
});
it('reads reviewed variables once from a bounded list and rejects duplicate/overflow responses',async()=>{
 const list=vi.fn(async()=>({data:{total_count:2,variables:[{name:'MATRIX_CI_DEDICATED_SHADOW',value:'true'},{name:'MATRIX_CI_CONTROLLER_SHA',value:'a'.repeat(40)}]}}));
 const source={rest:{actions:{listRepoVariables:list}}};expect(await api.readReviewedConfiguration(source,{owner:'HamedMP',repo:'matrix-os'})).toMatchObject({MATRIX_CI_DEDICATED_SHADOW:'true',MATRIX_CI_CONTROLLER_SHA:'a'.repeat(40)});expect(list).toHaveBeenCalledTimes(1);
 list.mockResolvedValueOnce({data:{total_count:2,variables:[{name:'MATRIX_CI_DEDICATED_SHADOW',value:'true'},{name:'MATRIX_CI_DEDICATED_SHADOW',value:'false'}]}});await expect(api.readReviewedConfiguration(source,{owner:'HamedMP',repo:'matrix-os'})).rejects.toThrow(/duplicate/i);
 list.mockResolvedValueOnce({data:{total_count:101,variables:[]}});await expect(api.readReviewedConfiguration(source,{owner:'HamedMP',repo:'matrix-os'})).rejects.toThrow(/bound/i);
});

it('honors poll policy even when GitHub provides no cacheable ETag',async()=>{
 vi.useFakeTimers();try{const f=fixture(),args={pull_number:2454};f.get.mockResolvedValueOnce({...response(200,'',{}, {'x-poll-interval':'2'}),headers:{'x-poll-interval':'2'}} as any);await f.github.rest.pulls.get(args);const pending=f.github.rest.pulls.get(args);await vi.advanceTimersByTimeAsync(1999);expect(f.get).toHaveBeenCalledTimes(1);await vi.advanceTimersByTimeAsync(1);await pending;expect(f.get.mock.calls.at(-1)![0].headers).toBeUndefined();}finally{vi.useRealTimers();}
});
it('evicts expired and least-recently-used representations instead of accepting a stale304',async()=>{
 vi.useFakeTimers();try{const f=fixture();await f.github.rest.pulls.get({pull_number:1});await f.github.rest.pulls.get({pull_number:2});await f.github.rest.pulls.get({pull_number:3});expect(f.metrics().cacheEntries).toBe(2);f.get.mockResolvedValueOnce(response(304,'"one"',undefined));await expect(f.github.rest.pulls.get({pull_number:1})).rejects.toThrow(/304/);await vi.advanceTimersByTimeAsync(1001);f.get.mockResolvedValueOnce(response(304,'"one"',undefined));await expect(f.github.rest.pulls.get({pull_number:3})).rejects.toThrow(/304/);}finally{vi.useRealTimers();}
});
it('rejects a poll interval beyond the reviewed120second lease and aborts a pending poll wait',async()=>{
 const f=fixture();f.get.mockResolvedValueOnce(response(200,'"one"',{}, {'x-poll-interval':'61'}));await expect(f.github.rest.pulls.get({})).rejects.toThrow(/poll/);
 vi.useFakeTimers();try{const aborter=new AbortController(),g=fixture();const client=api.createConditionalGithub(g.source,{authenticationContext:'cancel',signal:aborter.signal});g.get.mockResolvedValueOnce(response(200,'"one"',{}, {'x-poll-interval':'60'}));await client.github.rest.pulls.get({});const pending=client.github.rest.pulls.get({});const rejected=expect(pending).rejects.toThrow(/cancel/i);aborter.abort();await vi.advanceTimersByTimeAsync(1);await rejected;expect(g.get).toHaveBeenCalledTimes(1);}finally{vi.useRealTimers();}
});
