# Matrix OS Terminal - zsh config with Powerlevel10k

export ZSH_PLUGIN_ROOT="/home/matrixos/.zsh"
export PATH="$HOME/.local/bin:$PATH"

HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
setopt appendhistory sharehistory hist_ignore_dups hist_ignore_space

# Key bindings (xterm.js compatibility)
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[3~' delete-char

# Set USER from Matrix handle (Alpine doesn't set USER for service accounts)
export USER="${MATRIX_HANDLE//[\$\`]/}"
export USER="${USER:-matrixos}"

[[ -f "$ZSH_PLUGIN_ROOT/themes/powerlevel10k/powerlevel10k.zsh-theme" ]] && \
  source "$ZSH_PLUGIN_ROOT/themes/powerlevel10k/powerlevel10k.zsh-theme"

# p10k config lives with the active shell home so Matrix terminal sessions can
# keep using a remapped HOME directory.
[[ -f "${ZDOTDIR:-$HOME}/.p10k.zsh" ]] && source "${ZDOTDIR:-$HOME}/.p10k.zsh"

alias ll='ls -la'
alias la='ls -A'
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline -20'

[[ -f "$ZSH_PLUGIN_ROOT/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ]] && \
  source "$ZSH_PLUGIN_ROOT/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
[[ -f "$ZSH_PLUGIN_ROOT/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] && \
  source "$ZSH_PLUGIN_ROOT/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
