# Matrix OS Terminal - zsh config with Oh My Zsh + Powerlevel10k

# Absolute path -- PTY sets HOME to MATRIX_HOME, not /home/matrixos
export ZSH="/home/matrixos/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
setopt appendhistory sharehistory hist_ignore_dups hist_ignore_space

# Key bindings (xterm.js compatibility)
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[3~' delete-char

# Set USER from Matrix handle (Alpine doesn't set USER for service accounts)
export USER="${MATRIX_HANDLE:-matrixos}"

source "$ZSH/oh-my-zsh.sh"

# p10k config (use absolute path, same reason as ZSH)
[[ -f /home/matrixos/.p10k.zsh ]] && source /home/matrixos/.p10k.zsh

alias ll='ls -la'
alias la='ls -A'
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline -20'
